/* Copyright (c) 2008-2018, Quantcast Corp. */
/* Version: 0e9a7da-20191205140709 */
window.__qc=function(d){if(d.__qc)return d.__qc;var xa="a ce cm dst enc fpa fpan je ns ogl rf tzo sr".split(" "),P,db="3097c37ec2c2 9591ee0951f 66322e4c24 497b48442447 8e5fbdcb69 b1cb39936ef 2c9fb934d88".split(" "),eb=["9591ee0951f"],z=d.document,D=d.navigator,aa="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),ya=!1,za=!1,ba=0,ca=[],fb=[],Q=[],x=[],I={},R=0,E=null,da=
{},A={},Aa=null,l,q,r,n,ea,Ba,Ca=!1,F=null,fa=[].slice,Da,ga,S,g,B,ha,Ea,Fa,ia,Ga,J,ja,G,T,Ha,ka,la,Ia,Ja,K,Ka,La,Ma,Na,Oa,Pa,Qa,ma,na,oa,L,Ra,pa,v,Sa,y,Ta,U,Ua,Va,qa,Wa,Xa,M,C,Ya,N,Za,ra,V,$a,ab,W,bb,sa,ta,cb,ua,H,X,Y,O,va,wa,Z;(function(){var a;a=z.createElement("script");P="async"in a?1:a.readyState?2:3})();var w=function(a){try{return{init:T,hash:G,push:Ha,rules:$a,hasRules:W,defaults:cb,__qc:function(){return!0}}[a].apply(null,fa.call(arguments,1))}catch(b){return!1}};w.evts=0;w.v=2;w.SD=aa;
w.qpixelsent=[];V=function(a){var b=a?a.length||0:0,c;for(c=0;c<b;c++)if(!a[c])return!1;return!0};ta=function(a){(a=a||d._qacct)&&(M(x,a)||x.push(a))};M=function(a,b){var c=a.length,f;for(f=0;f<c;f++)if(a[f]===b)return!0;return!1};N=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};Za=function(a){var b,c;b=N(a);if("array"===b)return a.slice(0);if("object"===b){b={};for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}return"string"===b?""+a:a};Ha=function(a,b){v(a,b)};
W=function(a){return M(Q,a)};cb=function(a,b){var c;a&&((c=da[a])&&(b=O(b,c)),b.qacct&&delete b.qacct,da[a]=b)};ua=function(a){var b,c;if(g(a))for(b in a)if("string"==typeof a[b]){b=a.event||"load";c=a.media||"webpage";"rule"!==b&&"load"!==b||"webpage"!==c&&"ad"!==c?v(a):(c=a.qacct||d._qacct,a.qacct=c,b=(b=A[c])?O(b,a):a,A[c]=b);ta(a.qacct);break}else"object"==typeof a[b]&&null!=a[b]&&ua(a[b])};O=function(a,b){var c={};c.qacct=a.qacct||b.qacct;c.event="load"===a.event||"load"===b.event?"load":a.event&&
b.event?a.event||b.event:null;c.media=null;c.media="webpage"===a.media||"webpage"===b.media?"webpage":"ad"===a.media||"ad"===b.media?"ad":a.media||b.media;qa(c,a,b);qa(c,b,a);c.event||delete c.event;c.media||delete c.media;return c};qa=function(a,b,c){var f,d,k,t,g,m;for(f in b)b.hasOwnProperty(f)&&!a.hasOwnProperty(f)&&(d=b[f],k=c[f],t="",g=!!d&&"string"==typeof d,m=!!k&&"string"==typeof k,g&&(t=d),g&&m&&(t+=","),m&&(t+=k),a[f]=t)};H=function(){var a=[],b,c;if(!(0<R)){Ya();for(b in A)A.hasOwnProperty(b)&&
A[b]&&(c=A[b],a.push(c),delete A[b]);1==a.length&&v(a[0]);1<a.length&&v(a)}};X=function(){var a=[],b,c,f;f=x.slice(0);for(b=0;b<f.length;b++)c=f[b],W(c)||a.push(c);if(0===a.length)H();else for(b=0;b<a.length;b++)c=a[b],Q.push(c),Wa(c)};Xa=function(a,b,c,f){var e;a=d.location.protocol+"//"+a;E=E||z.scripts[0];e=z.createElement("script");if(1===P)e.src=a,e.async=!0,e.onload=b,c&&(e.onerror=function(a){e.onerror=null;c(a)}),E.parentNode.insertBefore(e,E);else if(2===P){var k=!1;e.onload=e.onreadystatechange=
function(){k||"loaded"!=e.readyState&&"complete"!=e.readyState||(k=!0,e.onreadystatechange=null,b())};e.src=a;E.parentNode.insertBefore(e,E)}else f&&f()};ra=function(a){for(var b=window;;){try{if(b.frames[a])return b}catch(c){}if(b===window.top)return null;b=b.parent}};Wa=function(a){R++;Xa("rules.quantcount.com/rules-"+a+".js",function(){I[a]=2===P?2:0;Y()},function(b){I[a]=1;Y()},function(){I[a]=4;Y()})};Y=function(){R-=0<R?1:0;H()};$a=function(){var a=!0,b,c,f;if(arguments.length){f=function(b){a?
ua(b):v(b,!0)};for(b=0;b<arguments.length;b++)c=fa.call(arguments[b],0),c.splice(1,0,f),ab.apply(null,c);a=!1;ya&&H()}};ab=function(a,b){var c=[],f=[],d=b||v,k,g,u,m,p;if((k=fa.call(arguments,2))&&k.length){g=k[0]||V;u=k[1];m=k[2];k=m.length;for(p=0;p<k;p++)c.push(!1),f.push(null);c={p:a,f:c,r:g,c:m,a:u,v:f};W(a)||Q.push(a);fb.push(c);bb(c,d)}else Q.push(a),I[a]=6};bb=function(a,b){var c=a?a.c?a.c.length:0:0,d;for(d=0;d<c;d++)(function(c){var d,f;try{d=a.c[c][0],f=a.c[c].slice(1),f.splice(0,0,function(d){a.f[c]=
!0;a.v[c]=d;sa(a,b)}),d.apply(null,f)}catch(u){a.f[c]=!0,a.v[c]=!1,sa(a,b)}})(d)};sa=function(a,b){var c=a.a,d=a.v,e=a.r||V,k,g,u,m,p,h;(k=V(a.f))&&(k=k&&e(d));if(k)for(d=0;d<c.length;d++)try{g=c[d][0];u=1<c[d].length?c[d].slice(1):[];u=u.concat(a.v);m=g.apply(null,u);p={qacct:a.p,event:"rule"};for(h in m)m.hasOwnProperty(h)&&"qacct"!==h&&(p[h]=m[h]);b(p)}catch(gb){}};Da=function(){return ga(0)!==ga(6)?1:0};ga=function(a){a=new Date(2E3,a,1,0,0,0,0);var b=a.toGMTString(),b=new Date(b.substring(0,
b.lastIndexOf(" ")-1));return a-b};S=function(a){return a.replace(/\./g,"%2E").replace(/,/g,"%2C")};B="function"===typeof encodeURIComponent?encodeURIComponent:S;g=function(a){return"undefined"!=typeof a&&null!=a};ha=function(){return Math.round(2147483647*Math.random())};Ea=function(a){var b="",c=z.cookie,d;if(!c)return b;d=c.indexOf(a+"=");a=d+a.length+1;-1<d&&(b=c.indexOf(";",a),0>b&&(b=c.length),b=c.substring(a,b));return b};Ia=function(a){return"P0-"+ha()+"-"+a.getTime()};la=function(a,b,c){return["__qca=",
a,"; expires=",b.toGMTString(),"; path=/; domain=",c].join("")};ka=function(){var a=["",""],b=J(),c,d;if(1===ba)return a[0]=";fpan=u;fpa=",a;c=G(b);for(d=0;d<aa.length;d++)if(aa[d]===c)return a[0]=";fpan=u;fpa=",a;c=new Date;d=Ea("__qca");0<d.length||F?(0===d.length&&(d=F,a[1]=la(F,new Date(c.getTime()+338688E5),b)),a[0]=";fpan=0;fpa="+d):(F=Ia(c),a[1]=la(F,new Date(c.getTime()+338688E5),b),a[0]=";fpan=1;fpa="+F);return a};Fa=function(){var a=ka()[1];a&&(z.cookie=a)};ia=function(a){z.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/; domain="+
J()};J=function(){var a,b,c,d;a=z.domain;"www."===a.substring(0,4)&&(a=a.substring(4,a.length));b=a.split(".");d=b.length;if(3>d)return a;c=b[d-1];return 3>c.length?a:a=b[d-2]+"."+c};ja=function(a,b){var c;for(c=0;c<b.length;c++)a^=b.charCodeAt(c),a+=(a<<1)+(a<<4)+(a<<7)+(a<<8)+(a<<24);return a};G=function(a){var b;b=ja(2166136261,a);a=ja(3386659096,a);return Math.round(Math.abs(b*a)/65536).toString(16)};Ua=function(a){var b,c;if(a&&"object"===N(a))for(c=0;c<xa.length;c++)b=xa[c],a.hasOwnProperty(b)&&
a[b]&&delete a[b]};U=function(a,b,c){var f={},e,k=null,t="webpage",u="load",m={},p,h;e=b?b.qacct||d._qacct:d._qacct;p=A[e];b?p&&(b=O(b,p)):b=p;e&&delete A[e];Ua(b);if(null!=b)for(h in b)m[h]=void 0!==b[h],b.hasOwnProperty(h)&&"string"===typeof h&&"string"===typeof b[h]&&("uid"===h||"uh"===h?(Ja()||(k=G(b[h])),delete b[h]):"qacct"!==h&&(0<b[h].length?f[h+a]=B(b[h]):m[h]=!1,"media"===h&&(t=b[h]),"event"===h&&(u=b[h])));if("string"!==typeof e){if(!g(d._qacct)||0===d._qacct.length)return null;e=d._qacct}if(e){if(p=
da[e])for(h in p)"string"===typeof h&&p.hasOwnProperty(h)&&!m[h]&&(f[h+a]=B(p[h]),"media"===h&&(t=p[h]),"event"===h&&(u=p[h]))}else return null;m=I[e];g(m)||(m=3);f["rf"+a]=""+m;"string"===typeof k&&(b.uh=k,f["uh"+a]=B(k));if("webpage"===t&&"load"===u){for(b=0;b<w.qpixelsent.length;b++)if(w.qpixelsent[b]===e&&!c)return null;w.qpixelsent.push(e)}"ad"===t&&(ba=1);f["a"+a]=e;return f};Ta=function(a){var b=[],c;for(c in a)a[c]&&a.hasOwnProperty(c)&&b.push(c+"="+a[c]);return b.join(";")};Va=function(){var a=
z.getElementsByTagName("meta"),b="",c,d,e,k;for(c=0;c<a.length;c++){e=a[c];if(1E3<=b.length)return b;g(e)&&g(e.attributes)&&g(e.attributes.property)&&g(e.attributes.property.value)&&g(e.content)&&(d=e.attributes.property.value,e=e.content,3<d.length&&"og:"===d.substring(0,3)&&(0<b.length&&(b+=","),k=80<e.length?80:e.length,b+=S(d.substring(3,d.length))+"."+S(e.substring(0,k))))}return B(b)};Ga=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):
""};Ja=function(){var a=!1;g(d.external)&&(a=d.external,a="function"===typeof a.InPrivateFilteringEnabled&&!0===a.InPrivateFilteringEnabled());return a||"1"==D.doNotTrack||"yes"===D.doNotTrack||"1"==D.msDoNotTrack};v=function(a,b){var c="function"===typeof encodeURIComponent?"n":"s",f=ha(),e="",k="",t="",u="",m="",p="u",h="1",q=[],l,n,r,v,x;ba=0;g(w.qpixelsent)||(w.qpixelsent=[]);if(g(a))if(l=N(a),"object"===l)n=U("",a,b);else{if("array"===l)for(l=0;l<a.length;l++)r=U("."+(l+1),a[l],b),n=0===l?r:
O(n,r)}else"string"===typeof _qacct&&(n=U("",null,b));n&&(l=D.cookieEnabled?"1":"0","undefined"!=typeof D.javaEnabled&&(p=D.javaEnabled()?"1":"0"),g(d._qmeta)&&(k=";m="+B(d._qmeta),d._qmeta=null),self.screen&&(e=screen.width+"x"+screen.height+"x"+screen.colorDepth),r=new Date,v=Da(),x=ka()[0],d.location&&d.location.href&&(t=B(d.location.href)),z&&z.referrer&&(m=B(z.referrer)),d.self===d.top&&(h="0"),n.url?u=t:n.url=t,n.ref||(n.ref=m||""),t=Va(),m=Ta(n),q.push("/pixel;r="+f+";"+m+x+";ns="+h+";ce="+
l+";qjs=1;qv=0e9a7da-20191205140709"),q.push((n.ref?"":";ref=")+";je="+p+";sr="+e+";enc="+c+";dst="+v+";et="+r.getTime()+";tzo="+r.getTimezoneOffset()+(u?";ourl="+u:"")+k+";ogl="+t),ca.push(q),y())};Sa=function(a){if(q){var b=new Image;a=[d.location.protocol,"//pixel.",Ka(l)?"quantserve.com":"quantcount.com",a[0],";cm=",Ga(l),g(r)&&""!==r?";gdpr=1;gdpr_consent="+r:"",n?";us_privacy="+n:"",a[1]].join("");b.alt="";b.src=a;b.onload=function(){b&&"number"==typeof b.width&&3===b.width?ia("__qca"):Fa()}}};
y=function(){if(l&&g(q)&&g(r)&&void 0!==n)for(q||ia("__qca");ca.length;)Sa(ca.shift());else Oa()};Ka=function(a){return!0===a||1===a||1===a||g(a)&&"approved"===a.consent?!0:!1};La=function(){if(15271956E5<=(new Date).getTime())return!0;for(var a=0;a<x.length;a++)if(M(db,G(x[a])))return!0;return!1};ma=function(){for(var a=0;a<x.length;a++)if(M(eb,G(x[a])))return!0;return!1};Oa=function(){if(!Ca){Ca=!0;var a=La();if(d.top===d.self)if(a?"function"===typeof __cmp?__cmp("getVendorConsents",[11],function(a,
c){na(a,c);__cmp("getConsentData",null,oa)}):(q=!ma(),r=""):(q=!0,r=""),"object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi?Ma("getConsent","advertising"):l=!0,"function"===typeof __uspapi)try{__uspapi("getUSPData",1,pa)}catch(b){n=null}else n=null;else d.postMessage&&"object"===typeof d.JSON?Na("getConsent","advertising",a):(l=1,q=!a,r="",n=null);y()}};Ma=function(a,b){l=PrivacyManagerAPI.callApi(a,"quantserve.com",J(),"truste.com",b);y()};Na=function(a,b,c){if(c)if(ea=
ra("__cmpLocator"))try{ea.postMessage(d.JSON.stringify({__cmpCall:{command:"getVendorConsents",parameter:[11],callId:1}}),"*")}catch(f){q=!1}else q=!ma(),r="";else q=!0,r="";if(Ba=ra("__uspapiLocator"))try{Ba.postMessage({__uspapiCall:{command:"getUSPData",version:1,callId:3}},"*")}catch(f){n=null}else n=null;if(d.addEventListener)d.addEventListener("message",K,!1);else if(d.attachEvent)d.attachEvent("onmessage",K);else return l=!0,c&&!g(q)&&(q=!1),y();try{d.top.postMessage(d.JSON.stringify({PrivacyManagerAPI:{timestamp:(new Date).getTime(),
action:a,self:"quantserve.com",domain:J(),authority:"truste.com",type:b}}),"*")}catch(f){l=1}g(l)||(Aa=setTimeout(function(){g(l)||(l=!0,y())},25));y()};K=function(a){if(a.data&&a.data.__uspapiReturn)return Ra(a.data.__uspapiReturn);if("string"===typeof a.data&&0!==a.data.length){var b;try{b=d.JSON.parse(a.data)}catch(c){return}if(b.__cmpReturn)return Pa(b.__cmpReturn);Qa(b)}};Qa=function(a){a&&"object"===typeof a.PrivacyManagerAPI&&(clearTimeout(Aa),L(),l=a.PrivacyManagerAPI,y())};Ra=function(a){L();
if("object"!==typeof a)return n=null,y();3===a.callId&&pa(a.returnValue,a.success)};pa=function(a,b){n=null;!0===b&&void 0!==a&&"string"===typeof a.uspString&&(n=a.uspString);y()};Pa=function(a){1===a.callId?(na(a.returnValue,a.success),ea.postMessage(d.JSON.stringify({__cmpCall:{command:"getConsentData",parameter:null,callId:2}}),"*")):2===a.callId&&oa(a.returnValue,a.success)};oa=function(a,b){r=b?a.consentData||"":"";L();y()};na=function(a,b){var c=a.gdprApplies,d=a.vendorConsents,d=d?d[11]:void 0,
e=a.purposeConsents,g;e&&(g=e[1]);q=b&&(!c||d&&g);"boolean"!==typeof c&&(q=!1);L();y()};L=function(){g(q)&&g(l)&&g(r)&&void 0!==n&&(d.removeEventListener?window.removeEventListener("message",K,!1):d.detachEvent&&window.detachEvent("onmessage",K))};va=function(){var a=arguments,b,c;C([].slice.call(a));for(c=0;c<a.length;c++)b=a[c],v(b);x.length?X():H()};C=function(a){var b=N(a);if("array"===b)for(b=0;b<a.length;b++)C(a[b]);else"object"===b&&ta(a.qacct||d._qacct)};Ya=function(){var a;za||d._qevents.length||
d.ezt.length||"undefined"===typeof _qacct||(v({qacct:d._qacct}),za=!0);if(!w.evts){for(a in d._qevents)d._qevents[a]!==d._qevents.push&&d._qevents.hasOwnProperty(a)&&v(d._qevents[a]);for(a in d.ezt)d.ezt[a]!==d.ezt.push&&d.ezt.hasOwnProperty(a)&&v(d.ezt[a]);d._qevents={push:va};d.ezt.push=function(){var a=arguments,c;if(g(d.queueManager))for(c=0;c<a.length;c++)d.queueManager.push(a[c]);else va.apply(this,arguments)};w.evts=1}};Z=function(a){var b;a&&(b=Za(a),C(a),d._qevents.push(b))};wa=function(a){a.push=
function(){C([].slice.call(arguments));X();return[].push.apply(a,arguments)}};T=function(){g(d._qevents)||(d._qevents=[]);g(d.ezt)||(d.ezt=[]);Z(d._qoptions);Z(d.qcdata);Z(d.smarttagdata);w.evts||(wa(d._qevents),wa(d.ezt));C(d.ezt);C(d._qevents);C({qacct:d._qacct});d._qoptions=null;x.length?X():H();ya=!0};d.quantserve=d.quantserve||T;w.quantserve=T;return w}(window);quantserve();
