(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},f;if("function"==typeof Object.setPrototypeOf)f=Object.setPrototypeOf;else{var g;a:{var ea={h:!0},h={};try{h.__proto__=ea;g=h.h;break a}catch(a){}g=!1}f=g?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var k=f;
function l(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(k)k(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]}var m=this||self;
function fa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}var ha=Date.now||function(){return+new Date};function ia(a){var b=["mys","design","init"],c=m;b[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+b[0]);for(var d;b.length&&(d=b.shift());)b.length||void 0===a?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=a}function n(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};var ka=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};function q(a){q[" "](a);return a}q[" "]=function(){};function r(){}var la="function"==typeof Uint8Array;function t(a,b,c){a.b=null;b||(b=[]);a.j=void 0;a.f=-1;a.a=b;a:{if(b=a.a.length){--b;var d=a.a[b];if(!(null===d||"object"!=typeof d||Array.isArray(d)||la&&d instanceof Uint8Array)){a.g=b-a.f;a.c=d;break a}}a.g=Number.MAX_VALUE}a.i={};if(c)for(b=0;b<c.length;b++)if(d=c[b],d<a.g)d+=a.f,a.a[d]=a.a[d]||u;else{var e=a.g+a.f;a.a[e]||(a.c=a.a[e]={});a.c[d]=a.c[d]||u}}var u=[];
function v(a,b){if(b<a.g){b+=a.f;var c=a.a[b];return c===u?a.a[b]=[]:c}if(a.c)return c=a.c[b],c===u?a.c[b]=[]:c}function w(a){a=v(a,2);return null==a?0:a}function x(a,b){a=v(a,b);a=null==a?a:!!a;return null==a?!1:a}function y(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=v(a,c);d&&(a.b[c]=new b(d))}return a.b[c]}function z(a){if(a.b)for(var b in a.b){var c=a.b[b];if("array"==fa(c))for(var d=0;d<c.length;d++)c[d]&&A(c[d]);else c&&A(c)}}function A(a){z(a);return a.a}
function B(a){return new C(a?JSON.parse(a):null)}r.prototype.toString=function(){z(this);return this.a.toString()};function D(a){t(this,a,ma)}n(D,r);var ma=[17];function E(a){t(this,a,na)}n(E,r);var na=[27];function C(a){t(this,a,oa)}n(C,r);var oa=[8];var F=document;function G(){var a=H;try{var b;if(b=!!a&&null!=a.location.href)a:{try{q(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}};var I=!!window.google_async_iframe_id,H=I&&window.parent||window;var J=null;function pa(a,b,c){this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0};var K=m.performance,qa=!!(K&&K.mark&&K.measure&&K.clearMarks),L=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a;if(a=qa){var b;if(null===J){J="";try{a="";try{a=m.top.location.hash}catch(c){a=m.location.hash}a&&(J=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=J;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});
function M(){var a=N;this.a=[];this.c=a||m;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.a=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.b=L()||(null!=b?b:1>Math.random())}function ra(a){a&&K&&L()&&(K.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),K.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))}
M.prototype.start=function(a,b){if(!this.b)return null;var c=void 0===c?m:c;c=c.performance;(c=c&&c.now?c.now():null)||(c=(c=m.performance)&&c.now&&c.timing?Math.floor(c.now()+c.timing.navigationStart):ha());a=new pa(a,b,c);b="goog_"+a.label+"_"+a.uniqueId+"_start";K&&L()&&K.mark(b);return a};if(I&&!G()){var O="."+F.domain;try{for(;2<O.split(".").length&&!G();)F.domain=O=O.substr(O.indexOf(".")+1),H=window.parent}catch(a){}G()||(H=window)}var N=H,P=new M;function Q(){N.google_measure_js_timing||(P.b=!1,P.a!=P.c.google_js_reporting_queue&&(L()&&ka(P.a,ra),P.a.length=0))}"number"!==typeof N.google_srt&&(N.google_srt=Math.random());if("complete"==N.document.readyState)Q();else if(P.b){var sa=function(){Q()},R=N;R.addEventListener&&R.addEventListener("load",sa,!1)};function ta(){};function S(a,b){a=a.getElementsByTagName("META");for(var c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content");return""}function T(a,b,c){for(var d=a.getElementsByTagName("META"),e=0;e<d.length;++e)if(d[e].getAttribute("name")===b){d[e].setAttribute("content",c);return}d=document.createElement("META");d.setAttribute("name",b);d.setAttribute("content",c);a.appendChild(d)};function U(a,b){this.b=a;this.a=b;a=S(b,"namespace");a||(a="ns-"+Math.random().toString(36).substr(2,5),T(b,"namespace",a))}U.prototype.dispatchEvent=function(a,b){a=null==b?new CustomEvent(a):new CustomEvent(a,{detail:b});this.a.dispatchEvent(a)};function V(){this.a={};this.b={};this.c={}}V.prototype.set=function(a,b){this.a[a]=b};V.prototype.get=function(a){return this.a[a]};function W(a,b){if(b){b=JSON.parse(b);for(var c in b)a.set(c,b[c])}};function X(a){this.context=a;this.a=new V}l(X,ta);function ua(a,b){this.b=a;this.a=b}function va(a){if(!mys.Engine)throw Error("MysidiaJsError[2] ");var b=a.a.b,c=a.a.a;W(a.b.a,S(c,"runtime_data"));var d=S(c,"render_config");if(!d)throw Error("MysidiaJsError[35] ");var e=B(d),p=mys.Engine.create(b,c,A(e)),ba=0;c.addEventListener("browserRender",function(){++ba;if(1==ba)a.a.dispatchEvent("overallStart"),wa(a,e),p.enable().then(function(){a.a.dispatchEvent("overallQuiet")});else{var ca=c.clientWidth,da=c.clientHeight;ca&&da&&p.enable(ca,da)}})}
function wa(a,b){if(!(2==w(b)||y(y(b,E,1),D,10)&&x(y(y(b,E,1),D,10),16))){var c=a.a.a;c.addEventListener("browserStart",function(){if(y(y(b,E,1),D,10)&&x(y(y(b,E,1),D,10),15)){var d=a.b.a;for(var e in d.c)d.a.hasOwnProperty(e)||d.set(e,JSON.stringify(d.c[e]));for(var p in d.b)d.a.hasOwnProperty(p)||d.set(p,JSON.stringify(d.b[p]));(d=(d=JSON.stringify(d.a))&&"{}"!=d?d:"")&&T(c,"runtime_data",d)}});c.addEventListener("browserReady",function(){});c.addEventListener("browserQuiet",function(){})}}
function xa(a,b){2==w(b)||y(y(b,E,1),D,10)&&x(y(y(b,E,1),D,10),16)||(b=0,mys.engine&&(b=mys.engine.stage()),a=a.a.a,0==(b&1)&&a.addEventListener("overallStart",function(){}),a.addEventListener("browserStart",function(){}),a.addEventListener("browserReady",function(){}),a.addEventListener("browserQuiet",function(){}))};function Y(a){X.call(this,a)}l(Y,X);function Z(){Y.apply(this,arguments)}l(Z,Y);function ya(){Z.apply(this,arguments)}l(ya,Z);(function(a){var b=document.getElementById("mys-content");if(b){b=new U(document.head,b);var c=a(b);c=new ua(c,b);W(c.b.a,S(b.a,"runtime_data"));if("true"===c.b.a.get("EXP_async_load_design")){b=B(S(b.a,"render_config")||"[]");xa(c,b);return}}ia(function(d,e){d=new U(d,e);e=a(d);va(new ua(e,d))})})(function(a){return new ya(a)});}).call(this);
