
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"1",
  
  "macros":[],
  "tags":[],
  "predicates":[],
  "rules":[]
},
"runtime":[]




};
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa,ba="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ca;if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var ha;a:{var ia={pf:!0},ja={};try{ja.__proto__=ia;ha=ja.pf;break a}catch(a){}ha=!1}ca=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=ca,la=this||self,na=/^[\w+/_-]+[=]{0,2}$/,oa=null;var qa=function(){},ra=function(a){return"function"==typeof a},g=function(a){return"string"==typeof a},sa=function(a){return"number"==typeof a&&!isNaN(a)},va=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},q=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},wa=function(a,b){if(a&&va(a))for(var c=0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},xa=function(a,b){if(!sa(a)||
!sa(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},za=function(a,b){for(var c=new ya,d=0;d<a.length;d++)c.set(a[d],!0);for(var e=0;e<b.length;e++)if(c.get(b[e]))return!0;return!1},Aa=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])},Ba=function(a){return Math.round(Number(a))||0},Ca=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Ea=function(a){var b=[];if(va(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Fa=function(a){return a?
a.replace(/^\s+|\s+$/g,""):""},Ga=function(){return(new Date).getTime()},ya=function(){this.prefix="gtm.";this.values={}};ya.prototype.set=function(a,b){this.values[this.prefix+a]=b};ya.prototype.get=function(a){return this.values[this.prefix+a]};
var Ha=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Ia=function(a){var b=!1;return function(){if(!b)try{a()}catch(c){}b=!0}},Ja=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Ka=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1},La=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Ma=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c},Na=function(a){var b=
[];Aa(a,function(c,d){10>c.length&&d&&b.push(c)});return b.join(",")};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Oa=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Pa=function(a){if(null==a)return String(a);var b=Oa.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Qa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Ra=function(a){if(!a||"object"!=Pa(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Qa(a,"constructor")&&!Qa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Qa(a,b)},C=function(a,b){var c=b||("array"==Pa(a)?[]:{}),d;for(d in a)if(Qa(a,d)){var e=a[d];"array"==Pa(e)?("array"!=Pa(c[d])&&(c[d]=[]),c[d]=C(e,c[d])):Ra(e)?(Ra(c[d])||(c[d]={}),c[d]=C(e,c[d])):c[d]=e}return c};var qb;
var rb=[],sb=[],tb=[],ub=[],wb=[],xb={},yb,zb,Ab,Bb=function(a,b){var c={};c["function"]="__"+a;for(var d in b)b.hasOwnProperty(d)&&(c["vtp_"+d]=b[d]);return c},Cb=function(a,b){var c=a["function"];if(!c)throw Error("Error: No function name given for function call.");var d=xb[c],e={},f;for(f in a)a.hasOwnProperty(f)&&0===f.indexOf("vtp_")&&(e[void 0!==d?f:f.substr(4)]=a[f]);return void 0!==d?d(e):qb(c,e,b)},Eb=function(a,b,c){c=c||[];var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=Db(a[e],b,c));
return d},Fb=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=xb[b];return c?c.priorityOverride||0:0},Db=function(a,b,c){if(va(a)){var d;switch(a[0]){case "function_id":return a[1];case "list":d=[];for(var e=1;e<a.length;e++)d.push(Db(a[e],b,c));return d;case "macro":var f=a[1];if(c[f])return;var h=rb[f];if(!h||b.Lc(h))return;c[f]=!0;try{var k=Eb(h,b,c);k.vtp_gtmEventId=b.id;d=Cb(k,b);Ab&&(d=Ab.Of(d,k))}catch(y){b.ue&&b.ue(y,Number(f)),d=!1}c[f]=
!1;return d;case "map":d={};for(var l=1;l<a.length;l+=2)d[Db(a[l],b,c)]=Db(a[l+1],b,c);return d;case "template":d=[];for(var m=!1,n=1;n<a.length;n++){var r=Db(a[n],b,c);zb&&(m=m||r===zb.ub);d.push(r)}return zb&&m?zb.Rf(d):d.join("");case "escape":d=Db(a[1],b,c);if(zb&&va(a[1])&&"macro"===a[1][0]&&zb.og(a))return zb.Kg(d);d=String(d);for(var u=2;u<a.length;u++)Sa[a[u]]&&(d=Sa[a[u]](d));return d;case "tag":var p=a[1];if(!ub[p])throw Error("Unable to resolve tag reference "+p+".");return d={he:a[2],
index:p};case "zb":var t={arg0:a[2],arg1:a[3],ignore_case:a[5]};t["function"]=a[1];var v=Gb(t,b,c),w=!!a[4];return w||2!==v?w!==(1===v):null;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},Gb=function(a,b,c){try{return yb(Eb(a,b,c))}catch(d){JSON.stringify(a)}return 2};var Ib=function(){var a=function(b){return{toString:function(){return b}}};return{rd:a("convert_case_to"),sd:a("convert_false_to"),td:a("convert_null_to"),ud:a("convert_true_to"),vd:a("convert_undefined_to"),sh:a("debug_mode_metadata"),ra:a("function"),Re:a("instance_name"),Ve:a("live_only"),Xe:a("malware_disabled"),Ye:a("metadata"),th:a("original_vendor_template_id"),bf:a("once_per_event"),Ed:a("once_per_load"),Md:a("setup_tags"),Od:a("tag_id"),Pd:a("teardown_tags")}}();var Jb=null,Mb=function(a){function b(r){for(var u=0;u<r.length;u++)d[r[u]]=!0}var c=[],d=[];Jb=Kb(a);for(var e=0;e<sb.length;e++){var f=sb[e],h=Lb(f);if(h){for(var k=f.add||[],l=0;l<k.length;l++)c[k[l]]=!0;b(f.block||[])}else null===h&&b(f.block||[])}for(var m=[],n=0;n<ub.length;n++)c[n]&&!d[n]&&(m[n]=!0);return m},Lb=function(a){for(var b=a["if"]||[],c=0;c<b.length;c++){var d=Jb(b[c]);if(0===d)return!1;if(2===d)return null}for(var e=a.unless||[],f=0;f<e.length;f++){var h=Jb(e[f]);if(2===h)return null;
if(1===h)return!1}return!0},Kb=function(a){var b=[];return function(c){void 0===b[c]&&(b[c]=Gb(tb[c],a));return b[c]}};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var D=window,E=document,gc=navigator,hc=E.currentScript&&E.currentScript.src,ic=function(a,b){var c=D[a];D[a]=void 0===c?b:c;return D[a]},jc=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},kc=function(a,b,c){var d=E.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;jc(d,b);c&&(d.onerror=c);var e;if(null===oa)b:{var f=la.document,h=f.querySelector&&f.querySelector("script[nonce]");
if(h){var k=h.nonce||h.getAttribute("nonce");if(k&&na.test(k)){oa=k;break b}}oa=""}e=oa;e&&d.setAttribute("nonce",e);var l=E.getElementsByTagName("script")[0]||E.body||E.head;l.parentNode.insertBefore(d,l);return d},lc=function(){if(hc){var a=hc.toLowerCase();if(0===a.indexOf("https://"))return 2;if(0===a.indexOf("http://"))return 3}return 1},mc=function(a,b){var c=E.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=E.body&&E.body.lastChild||
E.body||E.head;d.parentNode.insertBefore(c,d);jc(c,b);void 0!==a&&(c.src=a);return c},nc=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a;return d},oc=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},pc=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},G=function(a){D.setTimeout(a,0)},qc=function(a,b){return a&&
b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},sc=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},tc=function(a){var b=E.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},uc=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;for(var f=a,h=0;f&&h<=c;h++){if(d[String(f.tagName).toLowerCase()])return f;
f=f.parentElement}return null},vc=function(a){gc.sendBeacon&&gc.sendBeacon(a)||nc(a)},wc=function(a,b){var c=a[b];c&&"string"===typeof c.animVal&&(c=c.animVal);return c};var yc=function(a){return xc?E.querySelectorAll(a):null},zc=function(a,b){if(!xc)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!E.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);
return null},Ac=!1;if(E.querySelectorAll)try{var Bc=E.querySelectorAll(":root");Bc&&1==Bc.length&&Bc[0]==E.documentElement&&(Ac=!0)}catch(a){}var xc=Ac;var H={qa:"_ee",nc:"event_callback",tb:"event_timeout",D:"gtag.config",X:"allow_ad_personalization_signals",oc:"restricted_data_processing",Qa:"allow_google_signals",Y:"cookie_expires",sb:"cookie_update",Ra:"session_duration",ba:"user_properties"};
H.bd="page_view";H.Yg="user_engagement";H.la="purchase";H.Cb="refund";H.Sa="begin_checkout";H.Ab="add_to_cart";H.Bb="remove_from_cart";H.Dg="view_cart";H.Ad="add_to_wishlist";H.Ta="view_item";H.Rg="view_promotion";H.Qg="select_promotion";H.Ig="click_item_list";H.$c="view_item_list";H.zd="add_payment_info";H.Bg="add_shipping_info";H.eh="allow_custom_scripts";H.hh="allow_display_features";H.jh="allow_enhanced_conversions";H.Wd="enhanced_conversions";H.Eb="client_id";H.P="cookie_domain";H.Fb="cookie_name";
H.Da="cookie_path";H.Ld="cookie_flags";H.fa="currency";H.Hb="custom_params";H.qh="custom_map";H.nd="groups";H.Ea="language";H.ph="country";H.wh="non_interaction";H.Ya="page_location";H.Za="page_referrer";H.jc="page_title";H.$a="send_page_view";H.na="send_to";H.kc="session_engaged";H.Pb="session_id";H.mc="session_number";H.ef="tracking_id";H.ma="linker";H.Ua="accept_incoming";H.C="domains";H.Xa="url_position";H.Va="decorate_forms";H.Zd="phone_conversion_number";H.Yd="phone_conversion_callback";H.pd=
"phone_conversion_css_class";H.be="phone_conversion_options";H.We="phone_conversion_ids";H.Ue="phone_conversion_country_code";H.Bd="aw_remarketing";H.Cd="aw_remarketing_only";H.W="value";H.Ze="quantity";H.Je="affiliation";H.Vd="tax";H.Ne="shipping";H.hd="list_name";H.Ud="checkout_step";H.Sd="checkout_option";H.Ke="coupon";H.Me="promotions";H.ab="transaction_id";H.cb="user_id";H.Ca="conversion_linker";H.Aa="conversion_cookie_prefix";H.S="cookie_prefix";H.M="items";H.Id="aw_merchant_id";H.Fd="aw_feed_country";
H.Hd="aw_feed_language";H.Dd="discount";H.Rd="disable_merchant_reported_purchases";H.ic="new_customer";H.Nd="customer_lifetime_value";H.He="dc_natural_search";H.rh="dc_custom_params";H.ff="trip_type";H.Xd="passengers";H.Se="method";H.df="search_term";H.lh="content_type";H.Te="optimize_id";H.Oe="experiments";H.Nb="google_signals";H.md="google_tld";H.Qb="update";H.ld="firebase_id";H.Lb="ga_restrict_domain";H.jd="event_settings";H.$e="screen_name";H.Qe="_x_19";H.Pe="_x_20";H.oa="transport_url";H.me=
[H.X,H.Qa,H.oc,H.P,H.Y,H.Ld,H.Fb,H.Da,H.S,H.sb,H.Hb,H.nc,H.jd,H.tb,H.Lb,H.Nb,H.md,H.nd,H.ma,H.na,H.$a,H.Ra,H.Qb,H.ba,H.oa];H.ee=[H.Ya,H.Za,H.jc,H.Ea,H.$e,H.cb,H.ld];H.hf=[H.la,H.Cb,H.Sa,H.Ab,H.Bb,H.Dg,H.Ad,H.Ta,H.Rg,H.Qg,H.$c,H.Ig,H.zd,H.Bg];H.yd=[H.na,H.Bd,H.Cd,H.Hb,H.$a,H.Ea,H.W,H.fa,H.ab,H.cb,H.Ca,H.Aa,H.S,H.P,H.Y,H.Ld,H.Ya,H.Za,H.Zd,H.Yd,H.pd,H.be,H.M,H.Id,H.Fd,H.Hd,H.Dd,H.Rd,H.ic,H.Nd,H.X,
H.oc,H.Qb,H.ld,H.Wd,H.oa];H.fe=[H.X,H.Qa,H.sb];H.ne=[H.Y,H.tb,H.Ra];var Rc=/[A-Z]+/,Sc=/\s/,Tc=function(a){if(g(a)&&(a=Fa(a),!Sc.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(Rc.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],o:d}}}}},Vc=function(a){for(var b={},c=0;c<a.length;++c){var d=Tc(a[c]);d&&(b[d.id]=d)}Uc(b);var e=[];Aa(b,function(f,h){e.push(h)});return e};
function Uc(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];"AW"===d.prefix&&d.o[1]&&b.push(d.containerId)}for(var e=0;e<b.length;++e)delete a[b[e]]};var Wc={},I=null,Xc=Math.random();Wc.s="AW-798847511";Wc.yb="2q2";var Yc={__cl:!0,__ecl:!0,__ehl:!0,__evl:!0,__fal:!0,__fil:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0,__paused:!0,__tg:!0},Zc="www.googletagmanager.com/gtm.js";Zc="www.googletagmanager.com/gtag/js";var $c=Zc,bd=null,cd=null,dd=null,ed="//www.googletagmanager.com/a?id="+Wc.s+"&cv=1",fd={},gd={},hd=function(){var a=I.sequence||0;I.sequence=a+1;return a};var id={},P=function(a,b){id[a]=id[a]||[];id[a][b]=!0},jd=function(a){for(var b=[],c=id[a]||[],d=0;d<c.length;d++)c[d]&&(b[Math.floor(d/6)]^=1<<d%6);for(var e=0;e<b.length;e++)b[e]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b[e]||0);return b.join("")};
var kd=function(){return"&tc="+ub.filter(function(a){return a}).length},nd=function(){ld||(ld=D.setTimeout(md,500))},md=function(){ld&&(D.clearTimeout(ld),ld=void 0);void 0===od||pd[od]&&!qd&&!rd||(sd[od]||td.qg()||0>=ud--?(P("GTM",1),sd[od]=!0):(td.Tg(),nc(vd()),pd[od]=!0,wd=xd=rd=qd=""))},vd=function(){var a=od;if(void 0===a)return"";var b=jd("GTM"),c=jd("TAGGING");return[yd,pd[a]?"":"&es=1",zd[a],b?"&u="+b:"",c?"&ut="+c:"",kd(),qd,rd,xd,wd,"&z=0"].join("")},Ad=function(){return[ed,"&v=3&t=t","&pid="+
xa(),"&rv="+Wc.yb].join("")},Bd="0.005000">Math.random(),yd=Ad(),Cd=function(){yd=Ad()},pd={},qd="",rd="",wd="",xd="",od=void 0,zd={},sd={},ld=void 0,td=function(a,b){var c=0,d=0;return{qg:function(){if(c<a)return!1;Ga()-d>=b&&(c=0);return c>=a},Tg:function(){Ga()-d>=b&&(c=0);c++;d=Ga()}}}(2,1E3),ud=1E3,Dd=function(a,b){if(Bd&&!sd[a]&&od!==a){md();od=a;wd=qd="";var c;c=0===b.indexOf("gtm.")?encodeURIComponent(b):"*";zd[a]="&e="+c+"&eid="+a;nd()}},Ed=function(a,b,c){if(Bd&&!sd[a]&&
b){a!==od&&(md(),od=a);var d,e=String(b[Ib.ra]||"").replace(/_/g,"");0===e.indexOf("cvt")&&(e="cvt");d=e;var f=c+d;qd=qd?qd+"."+f:"&tr="+f;var h=b["function"];if(!h)throw Error("Error: No function name given for function call.");var k=(xb[h]?"1":"2")+d;wd=wd?wd+"."+k:"&ti="+k;nd();2022<=vd().length&&md()}},Fd=function(a,b,c){if(Bd&&!sd[a]){a!==od&&(md(),od=a);var d=c+b;rd=rd?rd+
"."+d:"&epr="+d;nd();2022<=vd().length&&md()}};var Gd={},Hd=new ya,Id={},Jd={},Md={name:"dataLayer",set:function(a,b){C(Ma(a,b),Id);Kd()},get:function(a){return Ld(a,2)},reset:function(){Hd=new ya;Id={};Kd()}},Ld=function(a,b){if(2!=b){var c=Hd.get(a);if(Bd){var d=Nd(a);c!==d&&P("GTM",5)}return c}return Nd(a)},Nd=function(a,b,c){var d=a.split("."),e=!1,f=void 0;var h=function(k,l){for(var m=0;void 0!==k&&m<d.length;m++){if(null===k)return!1;k=k[d[m]]}return void 0!==k||1<m?k:l.length?h(Od(l.pop()),l):Pd(d)};
e=!0;f=h(Id.eventModel,[b,c]);return e?f:Pd(d)},Pd=function(a){for(var b=Id,c=0;c<a.length;c++){if(null===b)return!1;if(void 0===b)break;b=b[a[c]]}return b};var Od=function(a){if(a){var b=Pd(["gtag","targets",a]);return Ra(b)?b:void 0}},Qd=function(a,b){function c(f){f&&Aa(f,function(h){d[h]=null})}var d={};c(Id);delete d.eventModel;c(Od(a));c(Od(b));c(Id.eventModel);var e=[];Aa(d,function(f){e.push(f)});return e};
var Rd=function(a,b){Jd.hasOwnProperty(a)||(Hd.set(a,b),C(Ma(a,b),Id),Kd())},Kd=function(a){Aa(Jd,function(b,c){Hd.set(b,c);C(Ma(b,void 0),Id);C(Ma(b,c),Id);a&&delete Jd[b]})},Sd=function(a,b,c){Gd[a]=Gd[a]||{};var d=1!==c?Nd(b):Hd.get(b);"array"===Pa(d)||"object"===Pa(d)?Gd[a][b]=C(d):Gd[a][b]=d},Td=function(a,b){if(Gd[a])return Gd[a][b]},Ud=function(a,b){Gd[a]&&delete Gd[a][b]};var Vd=function(){var a=!1;return a};var R=function(a,b,c,d){return(2===Wd()||d||"http:"!=D.location.protocol?a:b)+c},Wd=function(){var a=lc(),b;if(1===a)a:{var c=$c;c=c.toLowerCase();for(var d="https://"+c,e="http://"+c,f=1,h=E.getElementsByTagName("script"),k=0;k<h.length&&100>k;k++){var l=h[k].src;if(l){l=l.toLowerCase();if(0===l.indexOf(e)){b=3;break a}1===f&&0===l.indexOf(d)&&(f=2)}}b=f}else b=a;return b};
var Yd=function(a,b,c){if(D[a.functionName])return b.Rc&&G(b.Rc),D[a.functionName];var d=Xd();D[a.functionName]=d;if(a.Db)for(var e=0;e<a.Db.length;e++)D[a.Db[e]]=D[a.Db[e]]||Xd();a.Ob&&void 0===D[a.Ob]&&(D[a.Ob]=c);kc(R("https://","http://",a.cd),b.Rc,b.Eg);return d},Xd=function(){var a=function(){a.q=a.q||[];a.q.push(arguments)};return a},Zd={functionName:"_googWcmImpl",Ob:"_googWcmAk",cd:"www.gstatic.com/wcm/loader.js"},$d={functionName:"_gaPhoneImpl",Ob:"ga_wpid",cd:"www.gstatic.com/gaphone/loader.js"},
ae={Ie:"",jf:"1"},be={functionName:"_googCallTrackingImpl",Db:[$d.functionName,Zd.functionName],cd:"www.gstatic.com/call-tracking/call-tracking_"+(ae.Ie||ae.jf)+".js"},ce={},de=function(a,b,c,d){P("GTM",22);if(c){d=d||{};var e=Yd(Zd,d,a),f={ak:a,cl:b};void 0===d.ca&&(f.autoreplace=c);e(2,d.ca,f,c,0,new Date,d.options)}},ee=function(a,b,c){P("GTM",23);if(b){c=c||{};var d=Yd($d,c,a),e={};void 0!==c.ca?e.receiver=c.ca:e.replace=b;e.ga_wpid=a;e.destination=b;d(2,new Date,
e)}},fe=function(a,b,c,d){P("GTM",21);if(b&&c){d=d||{};for(var e={countryNameCode:c,destinationNumber:b,retrievalTime:new Date},f=0;f<a.length;f++){var h=a[f];ce[h.id]||(h&&"AW"===h.prefix&&!e.adData&&2<=h.o.length?(e.adData={ak:h.o[0],cl:h.o[1]},ce[h.id]=!0):h&&"UA"===h.prefix&&!e.gaData&&(e.gaData={gaWpid:h.containerId},ce[h.id]=!0))}(e.gaData||e.adData)&&Yd(be,d)(d.ca,e,d.options)}},ge=function(){var a=!1;
return a},he=function(a,b){if(a)if(Vd()){}else{if(g(a)){var c=Tc(a);if(!c)return;a=c}var d=function(x){return b?b.getWithConfig(x):Nd(x,a.containerId,a.id)},e=void 0,f=!1,h=d(H.We);if(h&&va(h)){e=[];for(var k=0;k<h.length;k++){var l=Tc(h[k]);l&&(e.push(l),(a.id===l.id||a.id===a.containerId&&a.containerId===l.containerId)&&(f=!0))}}if(!e||f){var m=d(H.Zd),n;if(m){va(m)?n=m:n=[m];var r=d(H.Yd),u=d(H.pd),p=d(H.be),t=d(H.Ue),
v=r||u,w=1;"UA"!==a.prefix||e||(w=5);for(var y=0;y<n.length;y++)y<w&&(e?fe(e,n[y],t,{ca:v,options:p}):"AW"===a.prefix&&a.o[1]?ge()?fe([a],n[y],t||"US",{ca:v,options:p}):de(a.o[0],a.o[1],n[y],{ca:v,options:p}):"UA"===a.prefix&&(ge()?fe([a],n[y],t||"US",{ca:v}):ee(a.containerId,n[y],{ca:v})))}}}};var ke=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),le={cl:["ecl"],customPixels:["nonGooglePixels"],ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},me={cl:["ecl"],customPixels:["customScripts","html"],
ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},ne="google customPixels customScripts html nonGooglePixels nonGoogleScripts nonGoogleIframes".split(" ");
var pe=function(a){var b=Ld("gtm.whitelist");b&&P("GTM",9);b="google gtagfl lcl zone oid op".split(" ");var c=b&&La(Ea(b),le),d=Ld("gtm.blacklist");d||(d=Ld("tagTypeBlacklist"))&&P("GTM",3);d?
P("GTM",8):d=[];oe()&&(d=Ea(d),d.push("nonGooglePixels","nonGoogleScripts","sandboxedScripts"));0<=q(Ea(d),"google")&&P("GTM",2);var e=d&&La(Ea(d),me),f={};return function(h){var k=h&&h[Ib.ra];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==f[k])return f[k];var l=gd[k]||[],m=a(k,l);if(b){var n;if(n=m)a:{if(0>q(c,k))if(l&&0<l.length)for(var r=0;r<
l.length;r++){if(0>q(c,l[r])){P("GTM",11);n=!1;break a}}else{n=!1;break a}n=!0}m=n}var u=!1;if(d){var p=0<=q(e,k);if(p)u=p;else{var t=za(e,l||[]);t&&P("GTM",10);u=t}}var v=!m||u;v||!(0<=q(l,"sandboxedScripts"))||c&&-1!==q(c,"sandboxedScripts")||(v=za(e,ne));return f[k]=v}},oe=function(){return ke.test(D.location&&D.location.hostname)};var qe={Of:function(a,b){b[Ib.rd]&&"string"===typeof a&&(a=1==b[Ib.rd]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(Ib.td)&&null===a&&(a=b[Ib.td]);b.hasOwnProperty(Ib.vd)&&void 0===a&&(a=b[Ib.vd]);b.hasOwnProperty(Ib.ud)&&!0===a&&(a=b[Ib.ud]);b.hasOwnProperty(Ib.sd)&&!1===a&&(a=b[Ib.sd]);return a}};var re={active:!0,isWhitelisted:function(){return!0}},se=function(a){var b=I.zones;!b&&a&&(b=I.zones=a());return b};var te=function(){};var ue=!1,ve=0,we=[];function xe(a){if(!ue){var b=E.createEventObject,c="complete"==E.readyState,d="interactive"==E.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ue=!0;for(var e=0;e<we.length;e++)G(we[e])}we.push=function(){for(var f=0;f<arguments.length;f++)G(arguments[f]);return 0}}}function ye(){if(!ue&&140>ve){ve++;try{E.documentElement.doScroll("left"),xe()}catch(a){D.setTimeout(ye,50)}}}var ze=function(a){ue?a():we.push(a)};var Ae={},Be={},Ce=function(a,b,c,d){if(!Be[a]||Yc[b]||"__zone"===b)return-1;var e={};Ra(d)&&(e=C(d,e));e.id=c;e.status="timeout";return Be[a].tags.push(e)-1},De=function(a,b,c,d){if(Be[a]){var e=Be[a].tags[b];e&&(e.status=c,e.executionTime=d)}};function Ee(a){for(var b=Ae[a]||[],c=0;c<b.length;c++)b[c]();Ae[a]={push:function(d){d(Wc.s,Be[a])}}}
var He=function(a,b,c){Be[a]={tags:[]};ra(b)&&Fe(a,b);c&&D.setTimeout(function(){return Ee(a)},Number(c));return Ge(a)},Fe=function(a,b){Ae[a]=Ae[a]||[];Ae[a].push(Ia(function(){return G(function(){b(Wc.s,Be[a])})}))};function Ge(a){var b=0,c=0,d=!1;return{add:function(){c++;return Ia(function(){b++;d&&b>=c&&Ee(a)})},Af:function(){d=!0;b>=c&&Ee(a)}}};var Ie=function(){function a(d){return!sa(d)||0>d?0:d}if(!I._li&&D.performance&&D.performance.timing){var b=D.performance.timing.navigationStart,c=sa(Md.get("gtm.start"))?Md.get("gtm.start"):0;I._li={cst:a(c-b),cbt:a(cd-b)}}};var Me={},Ne=function(){return D.GoogleAnalyticsObject&&D[D.GoogleAnalyticsObject]},Oe=!1;
var Pe=function(a){D.GoogleAnalyticsObject||(D.GoogleAnalyticsObject=a||"ga");var b=D.GoogleAnalyticsObject;if(D[b])D.hasOwnProperty(b)||P("GTM",12);else{var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(new Date);D[b]=c}Ie();return D[b]},Qe=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=Ne();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)};
var Se=function(a){},Re=function(){return D.GoogleAnalyticsObject||"ga"};var Ue=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var Ve=/:[0-9]+$/,We=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if(decodeURIComponent(f[0]).replace(/\+/g," ")===b){var h=f.slice(1).join("=");return c?h:decodeURIComponent(h).replace(/\+/g," ")}}},Ze=function(a,b,c,d,e){b&&(b=String(b).toLowerCase());if("protocol"===b||"port"===b)a.protocol=Xe(a.protocol)||Xe(D.location.protocol);"port"===b?a.port=String(Number(a.hostname?a.port:D.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===b&&
(a.hostname=(a.hostname||D.location.hostname).replace(Ve,"").toLowerCase());var f=b,h,k=Xe(a.protocol);f&&(f=String(f).toLowerCase());switch(f){case "url_no_fragment":h=Ye(a);break;case "protocol":h=k;break;case "host":h=a.hostname.replace(Ve,"").toLowerCase();if(c){var l=/^www\d*\./.exec(h);l&&l[0]&&(h=h.substr(l[0].length))}break;case "port":h=String(Number(a.port)||("http"==k?80:"https"==k?443:""));break;case "path":a.pathname||a.hostname||P("TAGGING",1);h="/"==a.pathname.substr(0,1)?a.pathname:
"/"+a.pathname;var m=h.split("/");0<=q(d||[],m[m.length-1])&&(m[m.length-1]="");h=m.join("/");break;case "query":h=a.search.replace("?","");e&&(h=We(h,e,void 0));break;case "extension":var n=a.pathname.split(".");h=1<n.length?n[n.length-1]:"";h=h.split("/")[0];break;case "fragment":h=a.hash.replace("#","");break;default:h=a&&a.href}return h},Xe=function(a){return a?a.replace(":","").toLowerCase():""},Ye=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,c)}return b},
$e=function(a){var b=E.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||P("TAGGING",1),c="/"+c);var d=b.hostname.replace(Ve,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}};function ef(a,b,c,d){var e=ub[a],f=ff(a,b,c,d);if(!f)return null;var h=Db(e[Ib.Md],c,[]);if(h&&h.length){var k=h[0];f=ef(k.index,{B:f,w:1===k.he?b.terminate:f,terminate:b.terminate},c,d)}return f}
function ff(a,b,c,d){function e(){if(f[Ib.Xe])k();else{var w=Eb(f,c,[]),y=Ce(c.id,String(f[Ib.ra]),Number(f[Ib.Od]),w[Ib.Ye]),x=!1;w.vtp_gtmOnSuccess=function(){if(!x){x=!0;var A=Ga()-z;Ed(c.id,ub[a],"5");De(c.id,y,"success",A);h()}};w.vtp_gtmOnFailure=function(){if(!x){x=!0;var A=Ga()-z;Ed(c.id,ub[a],"6");De(c.id,y,"failure",A);k()}};w.vtp_gtmTagId=f.tag_id;
w.vtp_gtmEventId=c.id;Ed(c.id,f,"1");var B=function(){var A=Ga()-z;Ed(c.id,f,"7");De(c.id,y,"exception",A);x||(x=!0,k())};var z=Ga();try{Cb(w,c)}catch(A){B(A)}}}var f=ub[a],h=b.B,k=b.w,l=b.terminate;if(c.Lc(f))return null;var m=Db(f[Ib.Pd],c,[]);if(m&&m.length){var n=m[0],r=ef(n.index,{B:h,w:k,terminate:l},c,d);if(!r)return null;h=r;k=2===n.he?l:r}if(f[Ib.Ed]||f[Ib.bf]){var u=f[Ib.Ed]?wb:c.bh,p=h,t=k;if(!u[a]){e=Ia(e);var v=gf(a,u,e);h=v.B;k=v.w}return function(){u[a](p,t)}}return e}
function gf(a,b,c){var d=[],e=[];b[a]=hf(d,e,c);return{B:function(){b[a]=jf;for(var f=0;f<d.length;f++)d[f]()},w:function(){b[a]=kf;for(var f=0;f<e.length;f++)e[f]()}}}function hf(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function jf(a){a()}function kf(a,b){b()};var nf=function(a,b){for(var c=[],d=0;d<ub.length;d++)if(a.kb[d]){var e=ub[d];var f=b.add();try{var h=ef(d,{B:f,w:f,terminate:f},a,d);h?c.push({Fe:d,Ae:Fb(e),Zf:h}):(lf(d,a),f())}catch(l){f()}}b.Af();c.sort(mf);for(var k=0;k<c.length;k++)c[k].Zf();return 0<c.length};function mf(a,b){var c,d=b.Ae,e=a.Ae;c=d>e?1:d<e?-1:0;var f;if(0!==c)f=c;else{var h=a.Fe,k=b.Fe;f=h>k?1:h<k?-1:0}return f}
function lf(a,b){if(!Bd)return;var c=function(d){var e=b.Lc(ub[d])?"3":"4",f=Db(ub[d][Ib.Md],b,[]);f&&f.length&&c(f[0].index);Ed(b.id,ub[d],e);var h=Db(ub[d][Ib.Pd],b,[]);h&&h.length&&c(h[0].index)};c(a);}
var of=!1,pf=function(a,b,c,d,e){if("gtm.js"==b){if(of)return!1;of=!0}Dd(a,b);var f=He(a,d,e);Sd(a,"event",1);Sd(a,"ecommerce",1);Sd(a,"gtm");var h={id:a,name:b,Lc:pe(c),kb:[],bh:[],ue:function(){P("GTM",6)}};h.kb=Mb(h);var k=nf(h,f);"gtm.js"!==b&&"gtm.sync"!==b||Se(Wc.s);if(!k)return k;for(var l=0;l<h.kb.length;l++)if(h.kb[l]){var m=ub[l];if(m&&!Yc[String(m[Ib.ra])])return!0}return!1};var qf=function(a,b){var c=Bb(a,b);ub.push(c);return ub.length-1};var rf=/^https?:\/\/www\.googletagmanager\.com/;function sf(){var a;return a}function uf(a,b){}
function tf(a){0!==a.indexOf("http://")&&0!==a.indexOf("https://")&&(a="https://"+a);"/"===a[a.length-1]&&(a=a.substring(0,a.length-1));return a}function vf(){var a=!1;return a};var wf=function(){this.eventModel={};this.targetConfig={};this.containerConfig={};this.h={};this.globalConfig={};this.B=function(){};this.w=function(){}},xf=function(a){var b=new wf;b.eventModel=a;return b},yf=function(a,b){a.targetConfig=b;return a},zf=function(a,b){a.containerConfig=b;return a},Af=function(a,b){a.h=b;return a},Bf=function(a,b){a.globalConfig=b;return a},Cf=function(a,b){a.B=b;return a},Df=function(a,b){a.w=b;return a};
wf.prototype.getWithConfig=function(a){if(void 0!==this.eventModel[a])return this.eventModel[a];if(void 0!==this.targetConfig[a])return this.targetConfig[a];if(void 0!==this.containerConfig[a])return this.containerConfig[a];if(void 0!==this.h[a])return this.h[a];if(void 0!==this.globalConfig[a])return this.globalConfig[a]};
var Ef=function(a){function b(e){Aa(e,function(f){c[f]=null})}var c={};b(a.eventModel);b(a.targetConfig);b(a.containerConfig);b(a.globalConfig);var d=[];Aa(c,function(e){d.push(e)});return d};var Ff=function(a,b,c){for(var d=[],e=String(b||document.cookie).split(";"),f=0;f<e.length;f++){var h=e[f].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d},If=function(a,b,c,d){var e=Gf(a,d);if(1===e.length)return e[0].id;if(0!==e.length){e=Hf(e,function(f){return f.Jb},b);if(1===e.length)return e[0].id;e=Hf(e,function(f){return f.lb},c);return e[0]?e[0].id:void 0}};
function Jf(a,b,c){var d=document.cookie;document.cookie=a;var e=document.cookie;return d!=e||void 0!=c&&0<=Ff(b,e).indexOf(c)}
var Mf=function(a,b,c,d,e,f){d=d||"auto";var h={path:c||"/"};e&&(h.expires=e);"none"!==d&&(h.domain=d);var k;a:{var l=b,m;if(void 0==l)m=a+"=deleted; expires="+(new Date(0)).toUTCString();else{f&&(l=encodeURIComponent(l));var n=l;n&&1200<n.length&&(n=n.substring(0,1200));l=n;m=a+"="+l}var r=void 0,u=void 0,p;for(p in h)if(h.hasOwnProperty(p)){var t=h[p];if(null!=t)switch(p){case "secure":t&&(m+="; secure");break;case "domain":r=t;break;default:"path"==p&&(u=t),"expires"==p&&t instanceof Date&&(t=
t.toUTCString()),m+="; "+p+"="+t}}if("auto"===r){for(var v=Kf(),w=0;w<v.length;++w){var y="none"!=v[w]?v[w]:void 0;if(!Lf(y,u)&&Jf(m+(y?"; domain="+y:""),a,l)){k=!0;break a}}k=!1}else r&&"none"!=r&&(m+="; domain="+r),k=!Lf(r,u)&&Jf(m,a,l)}return k};function Hf(a,b,c){for(var d=[],e=[],f,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===f||l<f?(e=[k],f=l):l===f&&e.push(k)}return 0<d.length?d:e}
function Gf(a,b){for(var c=[],d=Ff(a),e=0;e<d.length;e++){var f=d[e].split("."),h=f.shift();if(!b||-1!==b.indexOf(h)){var k=f.shift();k&&(k=k.split("-"),c.push({id:f.join("."),Jb:1*k[0]||1,lb:1*k[1]||1}))}}return c}
var Nf=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Of=/(^|\.)doubleclick\.net$/i,Lf=function(a,b){return Of.test(document.location.hostname)||"/"===b&&Nf.test(a)},Kf=function(){var a=[],b=document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(var d=b.length-2;0<=d;d--)a.push(b.slice(d).join("."));var e=document.location.hostname;Of.test(e)||Nf.test(e)||a.push("none");return a};function Pf(){for(var a=Qf,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function Rf(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}var Qf,Sf;function Tf(a){Qf=Qf||Rf();Sf=Sf||Pf();for(var b=[],c=0;c<a.length;c+=3){var d=c+1<a.length,e=c+2<a.length,f=a.charCodeAt(c),h=d?a.charCodeAt(c+1):0,k=e?a.charCodeAt(c+2):0,l=f>>2,m=(f&3)<<4|h>>4,n=(h&15)<<2|k>>6,r=k&63;e||(r=64,d||(n=64));b.push(Qf[l],Qf[m],Qf[n],Qf[r])}return b.join("")}
function Uf(a){function b(l){for(;d<a.length;){var m=a.charAt(d++),n=Sf[m];if(null!=n)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return l}Qf=Qf||Rf();Sf=Sf||Pf();for(var c="",d=0;;){var e=b(-1),f=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|f>>4);64!=h&&(c+=String.fromCharCode(f<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var Vf;var Zf=function(){var a=Wf,b=Xf,c=Yf(),d=function(h){a(h.target||h.srcElement||{})},e=function(h){b(h.target||h.srcElement||{})};if(!c.init){oc(E,"mousedown",d);oc(E,"keyup",d);oc(E,"submit",e);var f=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(){b(this);f.call(this)};c.init=!0}},$f=function(a,b,c){for(var d=Yf().decorators,e={},f=0;f<d.length;++f){var h=d[f],k;if(k=!c||h.forms)a:{var l=h.domains,m=a;if(l&&(h.sameHost||m!==E.location.hostname))for(var n=0;n<l.length;n++)if(l[n]instanceof
RegExp){if(l[n].test(m)){k=!0;break a}}else if(0<=m.indexOf(l[n])){k=!0;break a}k=!1}if(k){var r=h.placement;void 0==r&&(r=h.fragment?2:1);r===b&&Ja(e,h.callback())}}return e},Yf=function(){var a=ic("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var ag=/(.*?)\*(.*?)\*(.*)/,cg=/^https?:\/\/([^\/]*?)\.?cdn\.ampproject\.org\/?(.*)/,dg=/^(?:www\.|m\.|amp\.)+/,eg=/([^?#]+)(\?[^#]*)?(#.*)?/;function fg(a){return new RegExp("(.*?)(^|&)"+a+"=([^&]*)&?(.*)")}
var hg=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()&&(b.push(c),b.push(Tf(String(d))))}var e=b.join("*");return["1",gg(e),e].join("*")},gg=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:b),a].join("*"),d;if(!(d=Vf)){for(var e=Array(256),f=0;256>f;f++){for(var h=f,k=0;8>k;k++)h=
h&1?h>>>1^3988292384:h>>>1;e[f]=h}d=e}Vf=d;for(var l=4294967295,m=0;m<c.length;m++)l=l>>>8^Vf[(l^c.charCodeAt(m))&255];return((l^-1)>>>0).toString(36)},jg=function(){return function(a){var b=$e(D.location.href),c=b.search.replace("?",""),d=We(c,"_gl",!0)||"";a.query=ig(d)||{};var e=Ze(b,"fragment").match(fg("_gl"));a.fragment=ig(e&&e[3]||"")||{}}},kg=function(){var a=jg(),b=Yf();b.data||(b.data={query:{},fragment:{}},a(b.data));var c={},d=b.data;d&&(Ja(c,d.query),Ja(c,d.fragment));return c},ig=function(a){var b;
b=void 0===b?3:b;try{if(a){var c;a:{for(var d=a,e=0;3>e;++e){var f=ag.exec(d);if(f){c=f;break a}d=decodeURIComponent(d)}c=void 0}var h=c;if(h&&"1"===h[1]){var k=h[3],l;a:{for(var m=h[2],n=0;n<b;++n)if(m===gg(k,n)){l=!0;break a}l=!1}if(l){for(var r={},u=k?k.split("*"):[],p=0;p<u.length;p+=2)r[u[p]]=Uf(u[p+1]);return r}}}}catch(t){}};
function lg(a,b,c,d){function e(n){var r=n,u=fg(a).exec(r),p=r;if(u){var t=u[2],v=u[4];p=u[1];v&&(p=p+t+v)}n=p;var w=n.charAt(n.length-1);n&&"&"!==w&&(n+="&");return n+m}d=void 0===d?!1:d;var f=eg.exec(c);if(!f)return"";var h=f[1],k=f[2]||"",l=f[3]||"",m=a+"="+b;d?l="#"+e(l.substring(1)):k="?"+e(k.substring(1));return""+h+k+l}
function mg(a,b){var c="FORM"===(a.tagName||"").toUpperCase(),d=$f(b,1,c),e=$f(b,2,c),f=$f(b,3,c);if(Ka(d)){var h=hg(d);c?ng("_gl",h,a):og("_gl",h,a,!1)}if(!c&&Ka(e)){var k=hg(e);og("_gl",k,a,!0)}for(var l in f)if(f.hasOwnProperty(l))a:{var m=l,n=f[l],r=a;if(r.tagName){if("a"===r.tagName.toLowerCase()){og(m,n,r,void 0);break a}if("form"===r.tagName.toLowerCase()){ng(m,n,r);break a}}"string"==typeof r&&lg(m,n,r,void 0)}}
function og(a,b,c,d){if(c.href){var e=lg(a,b,c.href,void 0===d?!1:d);Ue.test(e)&&(c.href=e)}}
function ng(a,b,c){if(c&&c.action){var d=(c.method||"").toLowerCase();if("get"===d){for(var e=c.childNodes||[],f=!1,h=0;h<e.length;h++){var k=e[h];if(k.name===a){k.setAttribute("value",b);f=!0;break}}if(!f){var l=E.createElement("input");l.setAttribute("type","hidden");l.setAttribute("name",a);l.setAttribute("value",b);c.appendChild(l)}}else if("post"===d){var m=lg(a,b,c.action);Ue.test(m)&&(c.action=m)}}}
var Wf=function(a){try{var b;a:{for(var c=a,d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var f=e.protocol;"http:"!==f&&"https:"!==f||mg(e,e.hostname)}}catch(h){}},Xf=function(a){try{if(a.action){var b=Ze($e(a.action),"host");mg(a,b)}}catch(c){}},pg=function(a,b,c,d){Zf();var e="fragment"===c?2:1,f={callback:a,domains:b,fragment:2===e,placement:e,forms:!!d,sameHost:!1};Yf().decorators.push(f)},qg=function(){var a=E.location.hostname,
b=cg.exec(E.referrer);if(!b)return!1;var c=b[2],d=b[1],e="";if(c){var f=c.split("/"),h=f[1];e="s"===h?decodeURIComponent(f[2]):decodeURIComponent(h)}else if(d){if(0===d.indexOf("xn--"))return!1;e=d.replace(/-/g,".").replace(/\.\./g,"-")}var k=a.replace(dg,""),l=e.replace(dg,""),m;if(!(m=k===l)){var n="."+l;m=k.substring(k.length-n.length,k.length)===n}return m},rg=function(a,b){return!1===a?!1:a||b||qg()};var sg={};var tg=/^\w+$/,ug=/^[\w-]+$/,vg=/^~?[\w-]+$/,wg={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha",gp:"_gp"};function xg(a){return a&&"string"==typeof a&&a.match(tg)?a:"_gcl"}
var zg=function(){var a=$e(D.location.href),b=Ze(a,"query",!1,void 0,"gclid"),c=Ze(a,"query",!1,void 0,"gclsrc"),d=Ze(a,"query",!1,void 0,"dclid");if(!b||!c){var e=a.hash.replace("#","");b=b||We(e,"gclid",void 0);c=c||We(e,"gclsrc",void 0)}return yg(b,c,d)},yg=function(a,b,c){var d={},e=function(f,h){d[h]||(d[h]=[]);d[h].push(f)};d.gclid=a;d.gclsrc=b;d.dclid=c;if(void 0!==a&&a.match(ug))switch(b){case void 0:e(a,"aw");break;case "aw.ds":e(a,"aw");e(a,"dc");break;case "ds":e(a,"dc");break;case "3p.ds":(void 0==
sg.gtm_3pds?0:sg.gtm_3pds)&&e(a,"dc");break;case "gf":e(a,"gf");break;case "ha":e(a,"ha");break;case "gp":e(a,"gp")}c&&e(c,"dc");return d},Bg=function(a){var b=zg();Ag(b,a)};
function Ag(a,b,c){function d(r,u){var p=Cg(r,e);p&&Mf(p,u,h,f,l,!0)}b=b||{};var e=xg(b.prefix),f=b.domain||"auto",h=b.path||"/",k=void 0==b.Ka?7776E3:b.Ka;c=c||Ga();var l=0==k?void 0:new Date(c+1E3*k),m=Math.round(c/1E3),n=function(r){return["GCL",m,r].join(".")};a.aw&&(!0===b.Mh?d("aw",n("~"+a.aw[0])):d("aw",n(a.aw[0])));a.dc&&d("dc",n(a.dc[0]));a.gf&&d("gf",n(a.gf[0]));a.ha&&d("ha",n(a.ha[0]));a.gp&&d("gp",n(a.gp[0]))}
var Eg=function(a,b,c,d,e){for(var f=kg(),h=xg(b),k=0;k<a.length;++k){var l=a[k];if(void 0!==wg[l]){var m=Cg(l,h),n=f[m];if(n){var r=Math.min(Dg(n),Ga()),u;b:{for(var p=r,t=Ff(m,E.cookie),v=0;v<t.length;++v)if(Dg(t[v])>p){u=!0;break b}u=!1}u||Mf(m,n,c,d,0==e?void 0:new Date(r+1E3*(null==e?7776E3:e)),!0)}}}var w={prefix:b,path:c,domain:d};Ag(yg(f.gclid,f.gclsrc),w)},Cg=function(a,b){var c=wg[a];if(void 0!==c)return b+c},Dg=function(a){var b=a.split(".");return 3!==b.length||"GCL"!==b[0]?0:1E3*(Number(b[1])||
0)};function Fg(a){var b=a.split(".");if(3==b.length&&"GCL"==b[0]&&b[1])return b[2]}
var Gg=function(a,b,c,d,e){if(va(b)){var f=xg(e);pg(function(){for(var h={},k=0;k<a.length;++k){var l=Cg(a[k],f);if(l){var m=Ff(l,E.cookie);m.length&&(h[l]=m.sort()[m.length-1])}}return h},b,c,d)}},Hg=function(a){return a.filter(function(b){return vg.test(b)})},Ig=function(a,b){for(var c=xg(b&&b.prefix),d={},e=0;e<a.length;e++)wg[a[e]]&&(d[a[e]]=wg[a[e]]);Aa(d,function(f,h){var k=Ff(c+h,E.cookie);if(k.length){var l=k[0],m=Dg(l),n={};n[f]=[Fg(l)];Ag(n,b,m)}})};function Jg(){var a=zg(),b=a.gclid,c=a.gclsrc;if(b&&(!c||"aw.ds"===c)){var d;I.reported_gclid||(I.reported_gclid={});d=I.reported_gclid;if(!d[b]){d[b]=!0;var e="/pagead/landing?gclid="+encodeURIComponent(b);c&&(e+="&gclsrc="+encodeURIComponent(c));vc("https://www.google.com"+e)}}};var Kg;if(3===Wc.yb.length)Kg="g";else{var Lg="G";Lg="g";Kg=Lg}
var Mg={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:Kg,OPT:"o"},Ng=function(a){var b=Wc.s.split("-"),c=b[0].toUpperCase(),d=Mg[c]||"i",e=a&&"GTM"===c?b[1]:"OPT"===c?b[1]:"",f;if(3===Wc.yb.length){var h=void 0;h=h||(Vd()?"s":"o");f="2"+(h||"w")}else f=
"";return f+d+Wc.yb+e};
var Og=function(a){var b=uf(a,"/pagead/conversion_async.js");return b?b:-1===navigator.userAgent.toLowerCase().indexOf("firefox")?R("https://","http://","www.googleadservices.com/pagead/conversion_async.js"):"https://www.google.com/pagead/conversion_async.js"},Pg=!1,Qg=[],Rg=["aw","dc"],Sg=function(a){var b=D.google_trackConversion,c=a.gtm_onFailure;"function"==typeof b?b(a)||c():c()},Tg=function(){for(;0<Qg.length;)Sg(Qg.shift())},Ug=function(a){if(!Pg){Pg=!0;Ie();var b=function(){Tg();Qg={push:Sg}};
Vd()?b():kc(a,b,function(){Tg();Pg=!1})}},Vg=function(a){if(a){for(var b=[],c=0;c<a.length;++c){var d=a[c];d&&b.push({item_id:d.id,quantity:d.quantity,value:d.price,start_date:d.start_date,end_date:d.end_date})}return b}},Wg=function(a,b,c,d){var e=Tc(a),f=b==H.D,h=e.o[0],k=e.o[1],l=void 0!==k,m=function(T){return d.getWithConfig(T)},n=!1!==m(H.Ca),r=m(H.Aa)||m(H.S),u=m(H.P),p=m(H.Y),t=m(H.oa),v=Og(t);if(f){var w=m(H.ma)||{};if(n){rg(w[H.Ua],!!w[H.C])&&Eg(Rg,r,void 0,u,p);var y={prefix:r,domain:u,
Ka:p};Bg(y);Ig(["aw","dc"],y)}w[H.C]&&Gg(Rg,w[H.C],w[H.Xa],!!w[H.Va],r);var x=!1;x=!0;x?he(e,d):he(e);}var B=!1===m(H.Bd)||!1===m(H.$a);if(!f||!l&&!B)if(!0===m(H.Cd)&&(l=!1),!1!==m(H.X)||l){var z={google_conversion_id:h,google_remarketing_only:!l,onload_callback:d.B,
gtm_onFailure:d.w,google_conversion_format:"3",google_conversion_color:"ffffff",google_conversion_domain:"",google_conversion_label:k,google_conversion_language:m(H.Ea),google_conversion_value:m(H.W),google_conversion_currency:m(H.fa),google_conversion_order_id:m(H.ab),google_user_id:m(H.cb),google_conversion_page_url:m(H.Ya),google_conversion_referrer_url:m(H.Za),google_gtm:Ng(),google_transport_url:uf(t,"/")};z.google_restricted_data_processing=m(H.oc);
Vd()&&(z.opt_image_generator=function(){return new Image},z.google_enable_display_cookie_match=!1);!1===m(H.X)&&(z.google_allow_ad_personalization_signals=!1);z.google_read_gcl_cookie_opt_out=!n;n&&r&&(z.google_gcl_cookie_prefix=r);var A=function(){var T=m(H.Hb),da={event:b};if(va(T)){P("GTM",26);for(var ea=0;ea<T.length;++ea){var N=T[ea],L=m(N);void 0!==L&&(da[N]=L)}return da}var Q=d.eventModel;if(!Q)return null;C(Q,da);for(var S=0;S<H.yd.length;++S)delete da[H.yd[S]];
return da}();A&&(z.google_custom_params=A);!l&&m(H.M)&&(z.google_gtag_event_data={items:m(H.M),value:m(H.W)});if(l&&b==H.la){z.google_conversion_merchant_id=m(H.Id);z.google_basket_feed_country=m(H.Fd);z.google_basket_feed_language=m(H.Hd);z.google_basket_discount=m(H.Dd);z.google_basket_transaction_type=b;z.google_disable_merchant_reported_conversions=!0===m(H.Rd);Vd()&&(z.google_disable_merchant_reported_conversions=!0);var F=Vg(m(H.M));F&&(z.google_conversion_items=F)}var J=function(T,da){void 0!=
da&&""!==da&&(z.google_additional_conversion_params=z.google_additional_conversion_params||{},z.google_additional_conversion_params[T]=da)};l&&("boolean"===typeof m(H.ic)&&J("vdnc",m(H.ic)),J("vdltv",m(H.Nd)));var M=!0;M&&Qg.push(z)}Ug(v)};var Xg=function(){for(var a=gc.userAgent+(E.cookie||"")+(E.referrer||""),b=a.length,c=D.history.length;0<c;)a+=c--^b++;var d=1,e,f,h;if(a)for(d=0,f=a.length-1;0<=f;f--)h=a.charCodeAt(f),d=(d<<6&268435455)+h+(h<<14),e=d&266338304,d=0!=e?d^e>>21:d;return[Math.round(2147483647*Math.random())^d&2147483647,Math.round(Ga()/1E3)].join(".")},$g=function(a,b,c,d){var e=Yg(b);return If(a,e,Zg(c),d)},ah=function(a,b,c,d){var e=""+Yg(c),f=Zg(d);1<f&&(e+="-"+f);return[b,e,a].join(".")},Yg=function(a){if(!a)return 1;
a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length},Zg=function(a){if(!a||"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1};var bh=["1"],ch={},gh=function(a,b,c,d){var e=dh(a);ch[e]||eh(e,b,c)||(fh(e,Xg(),b,c,d),eh(e,b,c))};function fh(a,b,c,d,e){var f=ah(b,"1",d,c);Mf(a,f,c,d,0==e?void 0:new Date(Ga()+1E3*(void 0==e?7776E3:e)))}function eh(a,b,c){var d=$g(a,b,c,bh);d&&(ch[a]=d);return d}function dh(a){return(a||"_gcl")+"_au"};var hh=function(){for(var a=[],b=E.cookie.split(";"),c=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,d=0;d<b.length;d++){var e=b[d].match(c);e&&a.push({ed:e[1],value:e[2]})}var f={};if(!a||!a.length)return f;for(var h=0;h<a.length;h++){var k=a[h].value.split(".");"1"==k[0]&&3==k.length&&k[1]&&(f[a[h].ed]||(f[a[h].ed]=[]),f[a[h].ed].push({timestamp:k[1],bg:k[2]}))}return f};var ih=/^\d+\.fls\.doubleclick\.net$/;function jh(a){var b=$e(D.location.href),c=Ze(b,"host",!1);if(c&&c.match(ih)){var d=Ze(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function kh(a,b){if("aw"==a||"dc"==a){var c=jh("gcl"+a);if(c)return c.split(".")}var d=xg(b);if("_gcl"==d){var e;e=zg()[a]||[];if(0<e.length)return e}var f=Cg(a,d),h;if(f){var k=[];if(E.cookie){var l=Ff(f,E.cookie);if(l&&0!=l.length){for(var m=0;m<l.length;m++){var n=Fg(l[m]);n&&-1===q(k,n)&&k.push(n)}h=Hg(k)}else h=k}else h=k}else h=[];return h}
var lh=function(){var a=jh("gac");if(a)return decodeURIComponent(a);var b=hh(),c=[];Aa(b,function(d,e){for(var f=[],h=0;h<e.length;h++)f.push(e[h].bg);f=Hg(f);f.length&&c.push(d+":"+f.join(","))});return c.join(";")},mh=function(a,b,c,d,e){gh(b,c,d,e);var f=ch[dh(b)],h=zg().dc||[],k=!1;if(f&&0<h.length){var l=I.joined_au=I.joined_au||{},m=b||"_gcl";if(!l[m])for(var n=0;n<h.length;n++){var r="https://adservice.google.com/ddm/regclk";r=r+"?gclid="+h[n]+"&auiddc="+f;vc(r);k=l[m]=!0}}null==a&&(a=k);if(a&&f){var u=dh(b),
p=ch[u];p&&fh(u,p,c,d,e)}};
var nh=function(a){return!(void 0===a||null===a||0===(a+"").length)},oh=function(a,b){var c;if(2===b.V)return a("ord",xa(1E11,1E13)),!0;if(3===b.V)return a("ord","1"),a("num",xa(1E11,1E13)),!0;if(4===b.V)return nh(b.sessionId)&&a("ord",b.sessionId),!0;if(5===b.V)c="1";else if(6===b.V)c=b.Zc;else return!1;nh(c)&&a("qty",c);nh(b.Gb)&&a("cost",b.Gb);nh(b.transactionId)&&a("ord",b.transactionId);return!0},ph=encodeURIComponent,qh=function(a,b){function c(n,r,u){f.hasOwnProperty(n)||(r+="",e+=";"+n+"="+
(u?r:ph(r)))}var d=a.Ec,e=a.protocol;e+=a.Zb?"//"+d+".fls.doubleclick.net/activityi":"//ad.doubleclick.net/activity";e+=";src="+ph(d)+(";type="+ph(a.Hc))+(";cat="+ph(a.fb));var f=a.Tf||{};Aa(f,function(n,r){e+=";"+ph(n)+"="+ph(r+"")});if(oh(c,a)){nh(a.hc)&&c("u",a.hc);nh(a.fc)&&c("tran",a.fc);c("gtm",Ng());!1===a.xf&&c("npa","1");if(a.Dc){var h=kh("dc",a.Fa);h&&h.length&&c("gcldc",h.join("."));var k=kh("aw",a.Fa);k&&k.length&&c("gclaw",k.join("."));var l=lh();l&&c("gac",l);gh(a.Fa,void 0,a.Pf,a.Qf);
var m=ch[dh(a.Fa)];m&&c("auiddc",m)}nh(a.Vc)&&c("prd",a.Vc,!0);Aa(a.gd,function(n,r){c(n,r)});e+=b||"";nh(a.Ub)&&c("~oref",a.Ub);a.Zb?mc(e+"?",a.B):nc(e+"?",a.B,a.w)}else G(a.w)};
var rh=function(a,b,c,d,e,f){var h={config:a,gtm:Ng()};c&&(gh(d,void 0,e,f),h.auiddc=ch[dh(d)]);b&&(h.loadInsecure=b);void 0===D.__dc_ns_processor&&(D.__dc_ns_processor=[]);D.__dc_ns_processor.push(h);kc((b?"http":"https")+"://www.googletagmanager.com/dclk/ns/v1.js")},sh=function(a,b,c){var d=/^u([1-9]\d?|100)$/,e=a.getWithConfig(H.qh)||{},f=Qd(b,c);var h={},k={};if(Ra(e))for(var l in e)if(e.hasOwnProperty(l)&&
d.test(l)){var m=e[l];g(m)&&(h[l]=m)}for(var n=0;n<f.length;n++){var r=f[n];d.test(r)&&(h[r]=r)}for(var u in h)h.hasOwnProperty(u)&&(k[u]=a.getWithConfig(h[u]));return k},th=function(a){function b(l,m,n){void 0!==n&&0!==(n+"").length&&d.push(l+m+":"+c(n+""))}var c=encodeURIComponent,d=[],e=a(H.M)||[];if(va(e))for(var f=0;f<e.length;f++){var h=e[f],k=f+1;b("i",k,h.id);b("p",k,h.price);b("q",k,h.quantity);b("c",k,a(H.ph));b("l",k,a(H.Ea))}return d.join("|")},uh=function(a){var b=/^DC-(\d+)(\/([\w-]+)\/([\w-]+)\+(\w+))?$/.exec(a);
if(b){var c={standard:2,unique:3,per_session:4,transactions:5,items_sold:6,"":1}[(b[5]||"").toLowerCase()];if(c)return{containerId:"DC-"+b[1],N:b[3]?a:"",rf:b[1],qf:b[3]||"",fb:b[4]||"",V:c}}},wh=function(a,b,c,d){var e=uh(a);if(e){var f=function(M){return d.getWithConfig(M)},h=!1!==f(H.Ca),k=f(H.Aa)||f(H.S),l=f(H.P),m=f(H.Y),n=f(H.He),r=3===Wd();if(b===H.D){var u=f(H.ma)||{},p=f(H.sb),t=void 0===p?!0:!!p;if(h){if(rg(u[H.Ua],!!u[H.C])){Eg(vh,k,void 0,l,
m);}var v={prefix:k,domain:l,Ka:m};Bg(v);Ig(vh,v);mh(t,k,void 0,l,m)}if(u[H.C]){Gg(vh,u[H.C],u[H.Xa],!!u[H.Va],k);}if(n&&n.exclusion_parameters&&n.engines)if(Vd()){}else rh(n,r,h,k,l,m);G(d.B)}else{var w={},y=f(H.rh);if(Ra(y))for(var x in y)if(y.hasOwnProperty(x)){var B=y[x];void 0!==B&&null!==
B&&(w[x]=B)}var z="";if(5===e.V||6===e.V)z=th(f);var A=sh(d,e.containerId,e.N),F=!0===f(H.eh);if(Vd()&&F){F=!1}var J={fb:e.fb,Dc:h,Pf:l,Qf:m,Fa:k,Gb:f(H.W),V:e.V,Tf:w,Ec:e.rf,Hc:e.qf,w:d.w,B:d.B,Ub:Ye($e(D.location.href)),Vc:z,protocol:r?"http:":"https:",Zc:f(H.Ze),Zb:F,sessionId:f(H.Pb),fc:void 0,transactionId:f(H.ab),hc:void 0,gd:A,xf:!1!==f(H.X)};qh(J)}}else G(d.w)},vh=["aw","dc"];
var yh=function(a){var b;if(a.hasOwnProperty("conversion_data"))b="conversion_data";else if(a.hasOwnProperty("price"))b="price";else return;var c=b,d=xh(JSON.stringify(a[c])),e=xh(a.conversion_id),f="https://www.googletraveladservices.com/travel/flights/clk/pagead/conversion";var h=f+"/"+e+"/?"+c+"="+d;if(a.conversionLinkerEnabled){var k=
kh("gf",a.cookiePrefix);if(k&&k.length)for(var l=0;l<k.length;l++)h+="&gclgf="+xh(k[l])}nc(h,a.onSuccess,a.onFailure)},xh=function(a){return null===a||void 0===a||0===String(a).length?"":encodeURIComponent(String(a))};
var zh=/.*\.google\.com(:\d+)?\/booking\/flights.*/,Bh=function(a,b,c,d){var e=function(w){return d.getWithConfig(w)},f=Tc(a).o[0],h=!1!==e(H.Ca),k=e(H.Aa)||e(H.S),l=e(H.P),m=e(H.Y);if(b===H.D){if(h){var n={prefix:k,domain:l,Ka:m};Bg(n);Ig(["aw","dc"],n)}G(d.B)}else{var r={conversion_id:f,onFailure:d.w,onSuccess:d.B,conversionLinkerEnabled:h,cookiePrefix:k},u=zh.test(D.location.href);if(b!==H.la)G(d.w);else{var t={partner_id:f,trip_type:e(H.ff),total_price:e(H.W),currency:e(H.fa),is_direct_booking:u,flight_segment:Ah(e(H.M))},v=e(H.Xd);v&&"object"===typeof v&&(t.passengers_total=Ba(v.total),t.passengers_adult=Ba(v.adult),t.passengers_child=Ba(v.child),t.passengers_infant_in_seat=Ba(v.infant_in_seat),t.passengers_infant_in_lap=Ba(v.infant_in_lap));r.conversion_data=t;yh(r)}}},Ah=
function(a){if(a){for(var b=[],c=0,d=0;d<a.length;++d){var e=a[d];!e||void 0!==e.category&&""!==e.category&&"FlightSegment"!==e.category||(b[c]={cabin:e.travel_class,fare_product:e.fare_product,booking_code:e.booking_code,flight_number:e.flight_number,origin:e.origin,destination:e.destination,departure_date:e.start_date},c++)}return b}};
var Gh=function(a,b,c,d){var e=Tc(a),f=function(w){return d.getWithConfig(w)},h=!1!==f(H.Ca),k=f(H.Aa)||f(H.S),l=f(H.P),m=f(H.Y);if(b===H.D){var n=f(H.ma)||{};if(h){rg(n[H.Ua],!!n[H.C])&&Eg(Ch,k,void 0,l,m);var r={prefix:k,domain:l,Ka:m};Bg(r);Ig(["aw","dc"],r)}if(n[H.C]){Gg(Ch,n[H.C],n[H.Xa],!!n[H.Va],k);}G(d.B)}else{var u=e.o[0];if(/^\d+$/.test(u)){var p="https://www.googletraveladservices.com/travel/clk/pagead/conversion/"+encodeURIComponent(u)+
"/";if(b===H.la){var t=Dh(f(H.ab),f(H.W),f(H.fa),f(H.M));t=encodeURIComponent(Eh(t));p+="?data="+t}else if(b===H.Ta){var v=Fh(u,f(H.W),f(H.Vd),f(H.fa),f(H.M));v=encodeURIComponent(Eh(v));p+="?label=FH&guid=ON&script=0&ord="+xa(0,4294967295)+("&price="+v)}else{G(d.w);return}h&&(p+=kh("ha",k).map(function(w){return"&gclha="+encodeURIComponent(w)}).join(""));nc(p,d.B,d.w)}else G(d.w)}},Dh=function(a,b,c,d){var e={};Hh(a)&&(e.hct_booking_xref=a);g(c)&&(e.hct_currency_code=c);Hh(b)&&(e.hct_total_price=
b,e.hct_base_price=b);if(!va(d)||0===d.length)return e;var f=d[0];if(!Ra(f))return e;Hh(f[Ih.sa])&&(e.hct_partner_hotel_id=f[Ih.sa]);g(f[Ih.ia])&&(e.hct_checkin_date=f[Ih.ia]);g(f[Ih.Pa])&&(e.hct_checkout_date=f[Ih.Pa]);return e},Fh=function(a,b,c,d,e){function f(n){void 0===n&&(n=0);if(Hh(n))return l+n}function h(n,r,u){u(r)&&(k[n]=r)}var k={};k.partner_id=a;var l="USD";g(d)&&(l=k.currency=d);Hh(b)&&(k.base_price_value_string=f(b),k.display_price_value_string=f(b));Hh(c)&&(k.tax_price_value_string=
f(c));g("LANDING_PAGE")&&(k.page_type="LANDING_PAGE");if(!va(e)||0==e.length)return k;var m=e[0];if(!Ra(m))return k;Hh(m[Ih.Gd])&&(k.total_price_value_string=f(m[Ih.Gd]));h("partner_hotel_id",m[Ih.sa],Hh);h("check_in_date",m[Ih.ia],g);h("check_out_date",m[Ih.Pa],g);h("adults",m[Ih.af],Jh);h(Ih.Kd,m[Ih.Kd],g);h(Ih.Jd,m[Ih.Jd],g);return k},Eh=function(a){var b=[];Aa(a,function(c,d){b.push(c+"="+d)});return b.join(";")},Hh=function(a){return g(a)||Jh(a)},Jh=function(a){return"number"===typeof a},Ih=
{sa:"id",Gd:"price",ia:"start_date",Pa:"end_date",af:"occupancy",Kd:"room_id",Jd:"rate_rule_id"},Ch=["ha"];
var Xh=function(a,b,c,d){var e="https://www.google-analytics.com/analytics.js",f=Pe();if(ra(f)){var h="gtag_"+a.split("-").join("_"),k=function(x){var B=[].slice.call(arguments,0);B[0]=h+"."+B[0];f.apply(window,B)},l=function(){var x=function(F,J){for(var M=0;J&&M<J.length;M++)k(F,J[M])},B=Oh(b,d);if(B){var z=B.action;if("impressions"===z)x("ec:addImpression",B.jg);else if("promo_click"===z||"promo_view"===z){var A=B.Wc;x("ec:addPromo",B.Wc);A&&0<A.length&&"promo_click"===z&&k("ec:setAction",z)}else x("ec:addProduct",
B.La),k("ec:setAction",z,B.eb)}},m=function(){if(Vd()){}else{var x=d.getWithConfig(H.Te);x&&(k("require",x,{dataLayer:"dataLayer"}),k("require","render"))}},n=Ph(a,h,b,d);Qh(h,n.Ga)&&(f(function(){Ne()&&Ne().remove(h)}),Rh[h]=!1);f("create",a,n.Ga);(function(){var x=d.getWithConfig("custom_map");f(function(){if(Ra(x)){var B=n.ja,z=Ne().getByName(h),A;for(A in x)if(x.hasOwnProperty(A)&&/^(dimension|metric)\d+$/.test(A)&&void 0!=x[A]){var F=z.get(Sh(x[A]));Th(B,A,F)}}})})();(function(x){if(x){var B={};if(Ra(x))for(var z in Uh)Uh.hasOwnProperty(z)&&Vh(Uh[z],z,x[z],B);k("require","linkid",B)}})(n.linkAttribution);
var u=n[H.ma];if(u&&u[H.C]){var p=u[H.Xa];Qe(h+".",u[H.C],void 0===p?!!u.use_anchor:"fragment"===p,!!u[H.Va])}var t=function(x,B,z){z&&(B=""+B);n.ja[x]=B};if(b===H.bd)m(),k("send","pageview",n.ja);else if(b===H.D){m();var v=!1;v=!0;v?he(a,d):he(a);0!=n.sendPageView&&k("send","pageview",n.ja)}else"screen_view"===b?k("send","screenview",n.ja):"timing_complete"===b?(t("timingCategory",
n.eventCategory,!0),t("timingVar",n.name,!0),t("timingValue",Ba(n.value)),void 0!==n.eventLabel&&t("timingLabel",n.eventLabel,!0),k("send","timing",n.ja)):"exception"===b?k("send","exception",n.ja):"optimize.callback"!==b&&(0<=q([H.$c,"select_content",H.Ta,H.Ab,H.Bb,H.Sa,"set_checkout_option",H.la,H.Cb,"view_promotion","checkout_progress"],b)&&(k("require","ec","ec.js"),l()),t("eventCategory",n.eventCategory,!0),t("eventAction",n.eventAction||b,!0),void 0!==n.eventLabel&&t("eventLabel",n.eventLabel,
!0),void 0!==n.value&&t("eventValue",Ba(n.value)),k("send","event",n.ja));if(!Wh){Wh=!0;Ie();var w=d.w,y=function(){Ne().loaded||w()};Vd()?G(y):kc(e,y,w)}}else G(d.w)},Wh,Rh={},Yh={client_id:1,client_storage:"storage",cookie_name:1,cookie_domain:1,cookie_expires:1,cookie_path:1,cookie_update:1,cookie_flags:1,sample_rate:1,site_speed_sample_rate:1,use_amp_client_id:1,store_gac:1,conversion_linker:"storeGac"},Zh={anonymize_ip:1,app_id:1,app_installer_id:1,app_name:1,app_version:1,campaign:{name:"campaignName",
source:"campaignSource",medium:"campaignMedium",term:"campaignTerm",content:"campaignContent",id:"campaignId"},currency:"currencyCode",description:"exDescription",fatal:"exFatal",language:1,non_interaction:1,page_hostname:"hostname",page_referrer:"referrer",page_path:"page",page_location:"location",page_title:"title",screen_name:1,transport_type:"transport",user_id:1},$h={content_id:1,event_category:1,event_action:1,event_label:1,link_attribution:1,linker:1,method:1,name:1,send_page_view:1,value:1},
Uh={cookie_name:1,cookie_expires:"duration",levels:1},ai={anonymize_ip:1,fatal:1,non_interaction:1,use_amp_client_id:1,send_page_view:1,store_gac:1,conversion_linker:1},Vh=function(a,b,c,d){if(void 0!==c)if(ai[b]&&(c=Ca(c)),"anonymize_ip"!==b||c||(c=void 0),1===a)d[Sh(b)]=c;else if(g(a))d[a]=c;else for(var e in a)a.hasOwnProperty(e)&&void 0!==c[e]&&(d[a[e]]=c[e])},Sh=function(a){return a&&g(a)?a.replace(/(_[a-z])/g,function(b){return b[1].toUpperCase()}):a},bi=function(a){var b="general";0<=q([H.zd,
H.Ab,H.Ad,H.Sa,"checkout_progress",H.la,H.Cb,H.Bb,"set_checkout_option"],a)?b="ecommerce":0<=q("generate_lead login search select_content share sign_up view_item view_item_list view_promotion view_search_results".split(" "),a)?b="engagement":"exception"===a&&(b="error");return b},Th=function(a,b,c){a.hasOwnProperty(b)||(a[b]=c)},ci=function(a){if(va(a)){for(var b=[],c=0;c<a.length;c++){var d=a[c];if(void 0!=d){var e=d.id,f=d.variant;void 0!=e&&void 0!=f&&b.push(String(e)+"."+String(f))}}return 0<
b.length?b.join("!"):void 0}},Ph=function(a,b,c,d){var e=function(A){return d.getWithConfig(A)},f={},h={},k={},l=ci(e(H.Oe));l&&Th(h,"exp",l);var m=e("custom_map");if(Ra(m))for(var n in m)if(m.hasOwnProperty(n)&&/^(dimension|metric)\d+$/.test(n)&&void 0!=m[n]){var r=e(String(m[n]));void 0!==r&&Th(h,n,r)}var u=Qd(a);for(var p=0;p<u.length;++p){var t=u[p],v=e(t);if($h.hasOwnProperty(t))Vh($h[t],
t,v,f);else if(Zh.hasOwnProperty(t))Vh(Zh[t],t,v,h);else if(Yh.hasOwnProperty(t))Vh(Yh[t],t,v,k);else if(/^(dimension|metric|content_group)\d+$/.test(t))Vh(1,t,v,h);else if("developer_id"===t){}else t===H.S&&0>q(u,H.Fb)&&(k.cookieName=v+"_ga")}Th(k,"cookieDomain","auto");Th(h,"forceSSL",!0);Th(f,"eventCategory",bi(c));0<=q(["view_item","view_item_list","view_promotion",
"view_search_results"],c)&&Th(h,"nonInteraction",!0);"login"===c||"sign_up"===c||"share"===c?Th(f,"eventLabel",e(H.Se)):"search"===c||"view_search_results"===c?Th(f,"eventLabel",e(H.df)):"select_content"===c&&Th(f,"eventLabel",e(H.lh));var y=f[H.ma]||{},x=y[H.Ua];x||0!=x&&y[H.C]?k.allowLinker=!0:!1===x&&Th(k,"useAmpClientId",!1);if(!1===e(H.hh)||!1===e(H.X)||!1===e(H.Qa))h.allowAdFeatures=!1;!1===e(H.X)&&P("GTM",27);k.name=b;h["&gtm"]=Ng(!0);h.hitCallback=d.B;var B=e(H.Qe)||Ld("gtag.remote_config."+
a+".url",2),z=e(H.Pe)||Ld("gtag.remote_config."+a+".dualId",2);B&&null!=hc&&(k._x_19=B);z&&(k._x_20=z);f.ja=h;f.Ga=k;return f},Oh=function(a,b){function c(v){var w=C(v);w.list=v.list_name;w.listPosition=v.list_position;w.position=v.list_position||v.creative_slot;w.creative=v.creative_name;return w}function d(v){for(var w=[],y=0;v&&y<v.length;y++)v[y]&&w.push(c(v[y]));return w.length?w:void 0}function e(v){return{id:f(H.ab),affiliation:f(H.Je),revenue:f(H.W),tax:f(H.Vd),shipping:f(H.Ne),coupon:f(H.Ke),
list:f(H.hd)||v}}for(var f=function(v){return b.getWithConfig(v)},h=f(H.M),k,l=0;h&&l<h.length&&!(k=h[l][H.hd]);l++);var m=f("custom_map");if(Ra(m))for(var n=0;h&&n<h.length;++n){var r=h[n],u;for(u in m)m.hasOwnProperty(u)&&/^(dimension|metric)\d+$/.test(u)&&void 0!=m[u]&&Th(r,u,r[m[u]])}var p=null,t=f(H.Me);a===H.la||a===H.Cb?p={action:a,eb:e(),La:d(h)}:a===H.Ab?p={action:"add",La:d(h)}:a===H.Bb?p={action:"remove",La:d(h)}:a===H.Ta?p={action:"detail",eb:e(k),La:d(h)}:a===H.$c?p={action:"impressions",
jg:d(h)}:"view_promotion"===a?p={action:"promo_view",Wc:d(t)}:"select_content"===a&&t&&0<t.length?p={action:"promo_click",Wc:d(t)}:"select_content"===a?p={action:"click",eb:{list:f(H.hd)||k},La:d(h)}:a===H.Sa||"checkout_progress"===a?p={action:"checkout",La:d(h),eb:{step:a===H.Sa?1:f(H.Ud),option:f(H.Sd)}}:"set_checkout_option"===a&&(p={action:"checkout_option",eb:{step:f(H.Ud),option:f(H.Sd)}});p&&(p.zh=f(H.fa));return p},di={},Qh=function(a,b){var c=di[a];di[a]=C(b);if(!c)return!1;for(var d in b)if(b.hasOwnProperty(d)&&
b[d]!==c[d])return!0;for(var e in c)if(c.hasOwnProperty(e)&&c[e]!==b[e])return!0;return!1};var ei={},fi=["G","GP"];ei.Ge="";var gi=ei.Ge.split(",");function hi(){var a=I;return a.gcq=a.gcq||new ii}
var ji=function(a,b,c){hi().register(a,b,c)},ki=function(a,b,c,d){hi().push("event",[b,a],c,d)},li=function(a,b){hi().push("config",[a],b)},mi={},ni=function(){this.status=1;this.containerConfig={};this.targetConfig={};this.i={};this.m=null;this.h=!1},oi=function(a,b,c,d,e){this.type=a;this.m=b;this.N=c||"";this.h=d;this.i=e},ii=function(){this.i={};this.m={};this.h=[]},pi=function(a,b){var c=Tc(b);return a.i[c.containerId]=a.i[c.containerId]||new ni},qi=function(a,b,c,d){if(d.N){var e=pi(a,d.N),
f=e.m;if(f){var h=C(c),k=C(e.targetConfig[d.N]),l=C(e.containerConfig),m=C(e.i),n=C(a.m),r=Ld("gtm.uniqueEventId"),u=Tc(d.N).prefix,p=Df(Cf(Bf(Af(zf(yf(xf(h),k),l),m),n),function(){Fd(r,u,"2");}),function(){Fd(r,u,"3");});try{Fd(r,u,"1");f(d.N,b,d.m,p)}catch(t){
Fd(r,u,"4");}}}};
ii.prototype.register=function(a,b,c){if(3!==pi(this,a).status){pi(this,a).m=b;pi(this,a).status=3;c&&(pi(this,a).i=c);var d=Tc(a),e=mi[d.containerId];if(void 0!==e){var f=I[d.containerId].bootstrap,h=d.prefix.toUpperCase();I[d.containerId]._spx&&(h=h.toLowerCase());var k=Ld("gtm.uniqueEventId"),l=h,m=Ga()-f;if(Bd&&!sd[k]){k!==od&&(md(),od=k);var n=l+"."+Math.floor(f-e)+"."+Math.floor(m);xd=xd?xd+","+n:"&cl="+n}delete mi[d.containerId]}this.flush()}};
ii.prototype.push=function(a,b,c,d){var e=Math.floor(Ga()/1E3);a:if(c){var f=Tc(c),h;if(h=f){var k;if(k=1===pi(this,c).status)b:{var l=f.prefix;k=!0}h=k}if(h)if(pi(this,c).status=2,this.push("require",[],f.containerId),mi[f.containerId]=Ga(),Vd()){}else{var n=encodeURIComponent(f.containerId),r=("http:"!=D.location.protocol?"https:":"http:")+"//www.googletagmanager.com";
kc(r+"/gtag/js?id="+n+"&l=dataLayer&cx=c")}}this.h.push(new oi(a,e,c,b,d));d||this.flush()};
ii.prototype.flush=function(a){for(var b=this;this.h.length;){var c=this.h[0];if(c.i)c.i=!1,this.h.push(c);else switch(c.type){case "require":if(3!==pi(this,c.N).status&&!a)return;break;case "set":Aa(c.h[0],function(l,m){C(Ma(l,m),b.m)});break;case "config":var d=c.h[0],e=!!d[H.Qb];delete d[H.Qb];var f=pi(this,c.N),h=Tc(c.N),k=h.containerId===h.id;e||(k?f.containerConfig={}:f.targetConfig[c.N]={});f.h&&e||qi(this,H.D,d,c);f.h=!0;delete d[H.qa];k?C(d,f.containerConfig):C(d,f.targetConfig[c.N]);break;
case "event":qi(this,c.h[1],c.h[0],c)}this.h.shift()}};var ri=["GP","G"],si="G".split(/,/);var ti=!1;ti=!0;var ui=null,vi={},wi={},xi;function yi(a,b){var c={event:a};b&&(c.eventModel=C(b),b[H.nc]&&(c.eventCallback=b[H.nc]),b[H.tb]&&(c.eventTimeout=b[H.tb]));return c}
var zi=function(){ui=ui||!I.gtagRegistered;I.gtagRegistered=!0;return ui},Ai=function(a){if(void 0===wi[a.id]){var b;switch(a.prefix){case "UA":b=qf("gtagua",{trackingId:a.id});break;case "AW":b=qf("gtagaw",{conversionId:a});break;case "DC":b=qf("gtagfl",{targetId:a.id});break;case "GF":b=qf("gtaggf",{conversionId:a});break;case "HA":b=qf("gtagha",{conversionId:a});break;case "GP":b=qf("gtaggp",{conversionId:a.id});break;default:return}if(!xi){var c=Bb("v",{name:"send_to",dataLayerVersion:2});rb.push(c);
xi=["macro",rb.length-1]}var d={arg0:xi,arg1:a.id,ignore_case:!1};d[Ib.ra]="_lc";tb.push(d);var e={"if":[tb.length-1],add:[b]};e["if"]&&(e.add||e.block)&&sb.push(e);wi[a.id]=b}},Bi=function(a){Aa(vi,function(b,c){var d=q(c,a);0<=d&&c.splice(d,1)})},Ci=Ia(function(){}),Di=function(a){if(a.containerId!==Wc.s&&"G"!==a.prefix){var b;switch(a.prefix){case "UA":b=14;break;case "AW":b=15;break;case "DC":b=16;break;default:b=17}P("GTM",b)}};
var Ei={config:function(a){var b=a[2]||{};if(2>a.length||!g(a[1])||!Ra(b))return;var c=Tc(a[1]);if(!c)return;Bi(c.id);var d=c.id,e=b[H.nd]||"default";e=e.toString().split(",");for(var f=0;f<e.length;f++)vi[e[f]]=vi[e[f]]||[],vi[e[f]].push(d);delete b[H.nd];C(b);if(zi()){if(ti&&-1!==q(si,c.prefix)||-1!==q(ri,c.prefix)){"G"===c.prefix&&(b[H.qa]=!0);li(b,c.id);return}Ai(c);Di(c)}else Ci();Rd("gtag.targets."+c.id,void 0);Rd("gtag.targets."+c.id,C(b));var h={};h[H.na]=c.id;
return yi(H.D,h);},event:function(a){var b=a[1];if(g(b)&&!(3<a.length)){var c;if(2<a.length){if(!Ra(a[2])&&void 0!=a[2])return;c=a[2]}var d=yi(b,c);var e;var f=c&&c[H.na];void 0===f&&(f=Ld(H.na,2),void 0===f&&(f="default"));if(g(f)||va(f)){for(var h=f.toString().replace(/\s+/g,"").split(","),k=[],l=0;l<h.length;l++)0<=h[l].indexOf("-")?k.push(h[l]):k=k.concat(vi[h[l]]||[]);e=Vc(k)}else e=void 0;var m=e;if(!m)return;var n=zi();n||Ci();for(var r=
[],u=0;n&&u<m.length;u++){var p=m[u];Di(p);if(ti&&-1!==q(si,p.prefix)||-1!==q(ri,p.prefix)){var t=C(c);"G"===p.prefix&&(t[H.qa]=!0);ki(b,t,p.id)}else Ai(p);r.push(p.id)}C(c,{event:b});d.eventModel=d.eventModel||{};0<m.length?d.eventModel[H.na]=r.join():delete d.eventModel[H.na];return d}},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}},policy:function(){},set:function(a){var b;2==a.length&&Ra(a[1])?b=C(a[1]):3==a.length&&
g(a[1])&&(b={},Ra(a[2])||va(a[2])?b[a[1]]=C(a[2]):b[a[1]]=a[2]);if(b){if(zi()){var c=C(b);hi().push("set",[c])}C(b);b._clear=!0;return b}}},Fi={policy:!0};var Gi=function(a,b){var c=a.hide;if(c&&void 0!==c[b]&&c.end){c[b]=!1;var d=!0,e;for(e in c)if(c.hasOwnProperty(e)&&!0===c[e]){d=!1;break}d&&(c.end(),c.end=null)}},Ii=function(a){var b=Hi(),c=b&&b.hide;c&&c.end&&(c[a]=!0)};var Ji=!1,Ki=[];function Li(){if(!Ji){Ji=!0;for(var a=0;a<Ki.length;a++)G(Ki[a])}}var Mi=function(a){Ji?G(a):Ki.push(a)};var bj=function(a){if(aj(a))return a;this.h=a};bj.prototype.fg=function(){return this.h};var aj=function(a){return!a||"object"!==Pa(a)||Ra(a)?!1:"getUntrustedUpdateValue"in a};bj.prototype.getUntrustedUpdateValue=bj.prototype.fg;var cj=[],dj=!1,ej=function(a){return D["dataLayer"].push(a)},fj=function(a){var b=I["dataLayer"],c=b?b.subscribers:1,d=0;return function(){++d===c&&a()}};
function gj(a){var b=a._clear;Aa(a,function(f,h){"_clear"!==f&&(b&&Rd(f,void 0),Rd(f,h))});bd||(bd=a["gtm.start"]);var c=a.event;if(!c)return!1;var d=a["gtm.uniqueEventId"];d||(d=hd(),a["gtm.uniqueEventId"]=d,Rd("gtm.uniqueEventId",d));dd=c;var e=
hj(a);dd=null;switch(c){case "gtm.init":P("GTM",19),e&&P("GTM",20)}return e}function hj(a){var b=a.event,c=a["gtm.uniqueEventId"],d,e=I.zones;d=e?e.checkState(Wc.s,c):re;return d.active?pf(c,b,d.isWhitelisted,a.eventCallback,a.eventTimeout)?!0:!1:!1}
function ij(){for(var a=!1;!dj&&0<cj.length;){dj=!0;delete Id.eventModel;Kd();var b=cj.shift();if(null!=b){var c=aj(b);if(c){var d=b;b=aj(d)?d.getUntrustedUpdateValue():void 0;for(var e=["gtm.whitelist","gtm.blacklist","tagTypeBlacklist"],f=0;f<e.length;f++){var h=e[f],k=Ld(h,1);if(va(k)||Ra(k))k=C(k);Jd[h]=k}}try{if(ra(b))try{b.call(Md)}catch(v){}else if(va(b)){var l=b;if(g(l[0])){var m=
l[0].split("."),n=m.pop(),r=l.slice(1),u=Ld(m.join("."),2);if(void 0!==u&&null!==u)try{u[n].apply(u,r)}catch(v){}}}else{var p=b;if(p&&("[object Arguments]"==Object.prototype.toString.call(p)||Object.prototype.hasOwnProperty.call(p,"callee"))){a:{if(b.length&&g(b[0])){var t=Ei[b[0]];if(t&&(!c||!Fi[b[0]])){b=t(b);break a}}b=void 0}if(!b){dj=!1;continue}}a=gj(b)||a}}finally{c&&Kd(!0)}}dj=!1}
return!a}function jj(){var a=ij();try{Gi(D["dataLayer"],Wc.s)}catch(b){}return a}
var lj=function(){var a=ic("dataLayer",[]),b=ic("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};ze(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Mi(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});b.subscribers=(b.subscribers||0)+1;var c=a.push;a.push=function(){var d;if(0<I.SANDBOXED_JS_SEMAPHORE){d=[];for(var e=0;e<arguments.length;e++)d[e]=new bj(arguments[e])}else d=[].slice.call(arguments,0);var f=c.apply(a,d);cj.push.apply(cj,d);if(300<
this.length)for(P("GTM",4);300<this.length;)this.shift();var h="boolean"!==typeof f||f;return ij()&&h};cj.push.apply(cj,a.slice(0));kj()&&G(jj)},kj=function(){var a=!0;return a};var mj={};mj.ub=new String("undefined");
var nj=function(a){this.h=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===mj.ub?b:a[d]);return c.join("")}};nj.prototype.toString=function(){return this.h("undefined")};nj.prototype.valueOf=nj.prototype.toString;mj.lf=nj;mj.xc={};mj.Rf=function(a){return new nj(a)};var oj={};mj.Ug=function(a,b){var c=hd();oj[c]=[a,b];return c};mj.ce=function(a){var b=a?0:1;return function(c){var d=oj[c];if(d&&"function"===typeof d[b])d[b]();oj[c]=void 0}};mj.og=function(a){for(var b=!1,c=!1,d=2;d<a.length;d++)b=
b||8===a[d],c=c||16===a[d];return b&&c};mj.Kg=function(a){if(a===mj.ub)return a;var b=hd();mj.xc[b]=a;return'google_tag_manager["'+Wc.s+'"].macro('+b+")"};mj.zg=function(a,b,c){a instanceof mj.lf&&(a=a.h(mj.Ug(b,c)),b=qa);return{Jc:a,B:b}};var pj=function(a,b,c){function d(f,h){var k=f[h];return k}var e={event:b,"gtm.element":a,"gtm.elementClasses":d(a,"className"),"gtm.elementId":a["for"]||qc(a,"id")||"","gtm.elementTarget":a.formTarget||d(a,"target")||""};c&&(e["gtm.triggers"]=c.join(","));e["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||d(a,"href")||a.src||a.code||a.codebase||
"";return e},qj=function(a){I.hasOwnProperty("autoEventsSettings")||(I.autoEventsSettings={});var b=I.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},rj=function(a,b,c){qj(a)[b]=c},sj=function(a,b,c,d){var e=qj(a),f=Ha(e,b,d);e[b]=c(f)},tj=function(a,b,c){var d=qj(a);return Ha(d,b,c)};var uj=["input","select","textarea"],vj=["button","hidden","image","reset","submit"],wj=function(a){var b=a.tagName.toLowerCase();return!wa(uj,function(c){return c===b})||"input"===b&&wa(vj,function(c){return c===a.type.toLowerCase()})?!1:!0},xj=function(a){return a.form?a.form.tagName?a.form:E.getElementById(a.form):uc(a,["form"],100)},yj=function(a,b,c){if(!a.elements)return 0;for(var d=b.getAttribute(c),e=0,f=1;e<a.elements.length;e++){var h=a.elements[e];if(wj(h)){if(h.getAttribute(c)===d)return f;
f++}}return 0};var zj=!!D.MutationObserver,Aj=void 0,Bj=function(a){if(!Aj){var b=function(){var c=E.body;if(c)if(zj)(new MutationObserver(function(){for(var e=0;e<Aj.length;e++)G(Aj[e])})).observe(c,{childList:!0,subtree:!0});else{var d=!1;oc(c,"DOMNodeInserted",function(){d||(d=!0,G(function(){d=!1;for(var e=0;e<Aj.length;e++)G(Aj[e])}))})}};Aj=[];E.body?b():G(b)}Aj.push(a)};var Wj=D.clearTimeout,Xj=D.setTimeout,V=function(a,b,c){if(Vd()){b&&G(b)}else return kc(a,b,c)},Yj=function(){return D.location.href},Zj=function(a){return Ze($e(a),"fragment")},ak=function(a){return Ye($e(a))},W=function(a,b){return Ld(a,b||2)},bk=function(a,b,c){var d;b?(a.eventCallback=b,c&&(a.eventTimeout=c),d=ej(a)):d=ej(a);return d},ck=function(a,b){D[a]=b},X=function(a,b,c){b&&(void 0===D[a]||c&&!D[a])&&(D[a]=
b);return D[a]},dk=function(a,b,c){return Ff(a,b,void 0===c?!0:!!c)},ek=function(a,b){if(Vd()){b&&G(b)}else mc(a,b)},fk=function(a){return!!tj(a,"init",!1)},gk=function(a){rj(a,"init",!0)},hk=function(a,b){var c=(void 0===b?0:b)?"www.googletagmanager.com/gtag/js":$c;c+="?id="+encodeURIComponent(a)+"&l=dataLayer";V(R("https://","http://",c))},ik=function(a,b){var c=a[b];return c};
var jk=mj.zg;var Gk=new ya;function Hk(a,b){function c(h){var k=$e(h),l=Ze(k,"protocol"),m=Ze(k,"host",!0),n=Ze(k,"port"),r=Ze(k,"path").toLowerCase().replace(/\/$/,"");if(void 0===l||"http"==l&&"80"==n||"https"==l&&"443"==n)l="web",n="default";return[l,m,n,r]}for(var d=c(String(a)),e=c(String(b)),f=0;f<d.length;f++)if(d[f]!==e[f])return!1;return!0}
function Ik(a){return Jk(a)?1:0}
function Jk(a){var b=a.arg0,c=a.arg1;if(a.any_of&&va(c)){for(var d=0;d<c.length;d++)if(Ik({"function":a["function"],arg0:b,arg1:c[d]}))return!0;return!1}switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var e;a:{if(b){var f=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var h=0;h<f.length;h++)if(b[f[h]]){e=b[f[h]](c);break a}}catch(v){}}e=!1}return e;case "_ew":var k,l;k=String(b);l=String(c);var m=k.length-
l.length;return 0<=m&&k.indexOf(l,m)==m;case "_eq":return String(b)==String(c);case "_ge":return Number(b)>=Number(c);case "_gt":return Number(b)>Number(c);case "_lc":var n;n=String(b).split(",");return 0<=q(n,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":var r;var u=a.ignore_case?"i":void 0;try{var p=String(c)+u,t=Gk.get(p);t||(t=new RegExp(c,u),Gk.set(p,t));r=t.test(b)}catch(v){r=!1}return r;case "_sw":return 0==String(b).indexOf(String(c));case "_um":return Hk(b,
c)}return!1};var Kk=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var Lk={},Mk=encodeURI,Y=encodeURIComponent,Nk=nc;var Ok=function(a,b){if(!a)return!1;var c=Ze($e(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var Pk=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};Lk.pg=function(){var a=!1;return a};var am=function(){var a=D.gaGlobal=D.gaGlobal||{};a.hid=a.hid||xa();return a.hid};var lm=window,mm=document,nm=function(a){var b=lm._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===lm["ga-disable-"+a])return!0;try{var c=lm.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(f){}for(var d=Ff("AMP_TOKEN",mm.cookie,!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return mm.getElementById("__gaOptOutExtension")?!0:!1};var qm=function(a){Aa(a,function(c){"_"===c.charAt(0)&&delete a[c]});var b=a[H.ba]||{};Aa(b,function(c){"_"===c.charAt(0)&&delete b[c]})};var um=function(a,b,c){ki(b,c,a)},vm=function(a,b,c){ki(b,c,a,!0)},xm=function(a,b){};
function wm(a,b){}var Z={a:{}};



Z.a.gtagha=["google"],function(){var a=!1;a=!0;var b=function(c){var d=c.vtp_conversionId,e=dd,f=W("eventModel");if(a){ji(d.id,Gh);if(e===H.D){var h=W("gtag.targets."+d.id);li(h,d.id)}else ki(e,f,d.id);G(c.vtp_gtmOnSuccess)}else{var k=Df(Cf(xf(f),c.vtp_gtmOnSuccess),c.vtp_gtmOnFailure);k.getWithConfig=function(l){return Nd(l,d.containerId,d.id)};Gh(d.id,e,(new Date).getTime(),
k)}};Z.__gtagha=b;Z.__gtagha.b="gtagha";Z.__gtagha.g=!0;Z.__gtagha.priorityOverride=0;}();
Z.a.e=["google"],function(){(function(a){Z.__e=a;Z.__e.b="e";Z.__e.g=!0;Z.__e.priorityOverride=0})(function(a){return String(Td(a.vtp_gtmEventId,"event"))})}();

Z.a.v=["google"],function(){(function(a){Z.__v=a;Z.__v.b="v";Z.__v.g=!0;Z.__v.priorityOverride=0})(function(a){var b=a.vtp_name;if(!b||!b.replace)return!1;var c=W(b.replace(/\\\./g,"."),a.vtp_dataLayerVersion||1);return void 0!==c?c:a.vtp_defaultValue})}();







Z.a.gtagaw=["google"],function(){(function(a){Z.__gtagaw=a;Z.__gtagaw.b="gtagaw";Z.__gtagaw.g=!0;Z.__gtagaw.priorityOverride=0})(function(a){var b=a.vtp_conversionId,c=dd;ji(b.id,Wg);if(c===H.D){var d=W("gtag.targets."+b.id);li(d,b.id)}else{var e=W("eventModel");ki(c,e,b.id)}G(a.vtp_gtmOnSuccess)})}();

Z.a.get=["google"],function(){(function(a){Z.__get=a;Z.__get.b="get";Z.__get.g=!0;Z.__get.priorityOverride=0})(function(a){if(a.vtp_isAutoTag){var b=String(a.vtp_trackingId),c=dd||"",d={};if(c===H.D){var e=W("gtag.targets."+b);C(e,d);d[H.qa]=!0;li(d,b)}else{var f=W("eventModel");C(f,d);d[H.qa]=!0;ki(c,d,b)}}else{var h=a.vtp_settings;(a.vtp_deferrable?vm:um)(String(h.streamId),String(a.vtp_eventName),h.eventParameters||{})}a.vtp_gtmOnSuccess()})}();


Z.a.gtagfl=[],function(){function a(d){var e=/^DC-(\d+)(\/([\w-]+)\/([\w-]+)\+(\w+))?$/.exec(d);if(e)return{containerId:"DC-"+e[1],N:e[3]&&d}}var b=!1;b=!0;var c=function(d){var e=d.vtp_targetId,f=dd,h=W("eventModel");if(b){ji(e,wh);if(f===H.D){var k=W("gtag.targets."+e);li(k,e)}else ki(f,h,e);G(d.vtp_gtmOnSuccess)}else{var l=a(e);if(l){var m=Df(Cf(xf(h),d.vtp_gtmOnSuccess),
d.vtp_gtmOnFailure);m.getWithConfig=function(n){return Nd(n,l.containerId,l.N)};wh(e,f,(new Date).getTime(),m)}else G(d.vtp_gtmOnFailure)}};Z.__gtagfl=c;Z.__gtagfl.b="gtagfl";Z.__gtagfl.g=!0;Z.__gtagfl.priorityOverride=0;}();


Z.a.gtaggf=["google"],function(){(function(a){Z.__gtaggf=a;Z.__gtaggf.b="gtaggf";Z.__gtaggf.g=!0;Z.__gtaggf.priorityOverride=0})(function(a){var b=a.vtp_conversionId,c=dd,d=W("eventModel");ji(b.id,Bh);if(c===H.D){var e=W("gtag.targets."+b.id);li(e,b.id)}else ki(c,d,b.id);G(a.vtp_gtmOnSuccess)})}();




Z.a.gtagua=["google"],function(){var a=!1;a=!0;var b=function(c){var d=c.vtp_trackingId,e=dd,f=W("eventModel");if(a){ji(d,Xh);if(e===H.D){var h=W("gtag.targets."+d);li(h,d)}else ki(e,f,d);G(c.vtp_gtmOnSuccess)}else{var k=Df(Cf(xf(f),c.vtp_gtmOnSuccess),c.vtp_gtmOnFailure);k.getWithConfig=function(l){return Nd(l,d,void 0)};Xh(d,e,(new Date).getTime(),k)}};Z.__gtagua=
b;Z.__gtagua.b="gtagua";Z.__gtagua.g=!0;Z.__gtagua.priorityOverride=0;}();

var ym={};ym.macro=function(a){if(mj.xc.hasOwnProperty(a))return mj.xc[a]},ym.onHtmlSuccess=mj.ce(!0),ym.onHtmlFailure=mj.ce(!1);ym.dataLayer=Md;ym.callback=function(a){fd.hasOwnProperty(a)&&ra(fd[a])&&fd[a]();delete fd[a]};function zm(){I[Wc.s]=ym;Ja(gd,Z.a);zb=zb||mj;Ab=qe}
function Am(){sg.gtm_3pds=!0;I=D.google_tag_manager=D.google_tag_manager||{};if(I[Wc.s]){var a=I.zones;a&&a.unregisterChild(Wc.s)}else{for(var b=data.resource||{},c=b.macros||[],d=0;d<c.length;d++)rb.push(c[d]);for(var e=b.tags||[],f=0;f<e.length;f++)ub.push(e[f]);for(var h=b.predicates||[],k=0;k<
h.length;k++)tb.push(h[k]);for(var l=b.rules||[],m=0;m<l.length;m++){for(var n=l[m],r={},u=0;u<n.length;u++)r[n[u][0]]=Array.prototype.slice.call(n[u],1);sb.push(r)}xb=Z;yb=Ik;zm();lj();ue=!1;ve=0;if("interactive"==E.readyState&&!E.createEventObject||"complete"==E.readyState)xe();else{oc(E,"DOMContentLoaded",xe);oc(E,"readystatechange",xe);if(E.createEventObject&&E.documentElement.doScroll){var p=!0;try{p=!D.frameElement}catch(y){}p&&ye()}oc(D,"load",xe)}Ji=!1;"complete"===E.readyState?Li():oc(D,
"load",Li);a:{if(!Bd)break a;D.setInterval(Cd,864E5);}
cd=(new Date).getTime();
ym.bootstrap=cd;}}Am();

})()
