(function(h){var l=window.AmazonUIPageJS||window.P,n=l._namespace||l.attributeErrors,b=n?n("JQueryUI_Core_AUIBuild"):l;b.guardFatal?b.guardFatal(h)(b,window):b.execute(function(){h(b,window)})})(function(h,l,n){h.when("jQuery").register("jQueryUI-core",function(b){(function(a,b){function d(b,d){var e,f;e=b.nodeName.toLowerCase();if("area"===e){e=b.parentNode;f=e.name;if(!b.href||!f||"map"!==e.nodeName.toLowerCase())return!1;e=a("img[usemap=#"+f+"]")[0];return!!e&&c(e)}return(/input|select|textarea|button|object/.test(e)?
!b.disabled:"a"===e?b.href||d:d)&&c(b)}function c(b){return a.expr.filters.visible(b)&&!a(b).parents().addBack().filter(function(){return"hidden"===a.css(this,"visibility")}).length}var f=0,k=/^ui-id-\d+$/;a.ui=a.ui||{};a.extend(a.ui,{version:"1.10.3",keyCode:{BACKSPACE:8,COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,
TAB:9,UP:38}});a.fn.extend({focus:function(b){return function(c,d){return"number"===typeof c?this.each(function(){var b=this;setTimeout(function(){a(b).focus();d&&d.call(b)},c)}):b.apply(this,arguments)}}(a.fn.focus),scrollParent:function(){var b;b=a.ui.ie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(a.css(this,"position"))&&/(auto|scroll)/.test(a.css(this,"overflow")+a.css(this,"overflow-y")+
a.css(this,"overflow-x"))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(a.css(this,"overflow")+a.css(this,"overflow-y")+a.css(this,"overflow-x"))}).eq(0);return/fixed/.test(this.css("position"))||!b.length?a(document):b},zIndex:function(c){if(c!==b)return this.css("zIndex",c);if(this.length){c=a(this[0]);for(var d;c.length&&c[0]!==document;){d=c.css("position");if("absolute"===d||"relative"===d||"fixed"===d)if(d=parseInt(c.css("zIndex"),10),!isNaN(d)&&0!==d)return d;c=c.parent()}}return 0},
uniqueId:function(){return this.each(function(){this.id||(this.id="ui-id-"+ ++f)})},removeUniqueId:function(){return this.each(function(){k.test(this.id)&&a(this).removeAttr("id")})}});a.extend(a.expr[":"],{data:a.expr.createPseudo?a.expr.createPseudo(function(b){return function(c){return!!a.data(c,b)}}):function(b,c,d){return!!a.data(b,d[3])},focusable:function(b){return d(b,!isNaN(a.attr(b,"tabindex")))},tabbable:function(b){var c=a.attr(b,"tabindex"),e=isNaN(c);return(e||0<=c)&&d(b,!e)}});a("<a>").outerWidth(1).jquery||
a.each(["Width","Height"],function(c,d){function f(b,c,d,e){a.each(k,function(){c-=parseFloat(a.css(b,"padding"+this))||0;d&&(c-=parseFloat(a.css(b,"border"+this+"Width"))||0);e&&(c-=parseFloat(a.css(b,"margin"+this))||0)});return c}var k="Width"===d?["Left","Right"]:["Top","Bottom"],h=d.toLowerCase(),l={innerWidth:a.fn.innerWidth,innerHeight:a.fn.innerHeight,outerWidth:a.fn.outerWidth,outerHeight:a.fn.outerHeight};a.fn["inner"+d]=function(c){return c===b?l["inner"+d].call(this):this.each(function(){a(this).css(h,
f(this,c)+"px")})};a.fn["outer"+d]=function(b,c){return"number"!==typeof b?l["outer"+d].call(this,b):this.each(function(){a(this).css(h,f(this,b,!0,c)+"px")})}});a.fn.addBack||(a.fn.addBack=function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))});a("<a>").data("a-b","a").removeData("a-b").data("a-b")&&(a.fn.removeData=function(b){return function(c){return arguments.length?b.call(this,a.camelCase(c)):b.call(this)}}(a.fn.removeData));a.ui.ie=!!/msie [\w.]+/.exec(navigator.userAgent.toLowerCase());
a.support.selectstart="onselectstart"in document.createElement("div");a.fn.extend({disableSelection:function(){return this.bind((a.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});a.extend(a.ui,{plugin:{add:function(b,c,d){var e;b=a.ui[b].prototype;for(e in d)b.plugins[e]=b.plugins[e]||[],b.plugins[e].push([c,d[e]])},call:function(a,b,c){var d=a.plugins[b];if(d&&a.element[0].parentNode&&
11!==a.element[0].parentNode.nodeType)for(b=0;b<d.length;b++)a.options[d[b][0]]&&d[b][1].apply(a.element,c)}},hasScroll:function(b,c){if("hidden"===a(b).css("overflow"))return!1;var d=c&&"left"===c?"scrollLeft":"scrollTop",e=!1;if(0<b[d])return!0;b[d]=1;e=0<b[d];b[d]=0;return e}})})(b);return b})});
/* ******** */
(function(h){var l=window.AmazonUIPageJS||window.P,n=l._namespace||l.attributeErrors,b=n?n("JQueryUI_Position_AUIBuild"):l;b.guardFatal?b.guardFatal(h)(b,window):b.execute(function(){h(b,window)})})(function(h,l,n){h.when("jQuery").register("jQueryUI-position",function(b){(function(a,b){function d(a,b,c){return[parseFloat(a[0])*(u.test(a[0])?b/100:1),parseFloat(a[1])*(u.test(a[1])?c/100:1)]}function c(b){var c=b[0];return 9===c.nodeType?{width:b.width(),height:b.height(),offset:{top:0,left:0}}:a.isWindow(c)?
{width:b.width(),height:b.height(),offset:{top:b.scrollTop(),left:b.scrollLeft()}}:c.preventDefault?{width:0,height:0,offset:{top:c.pageY,left:c.pageX}}:{width:b.outerWidth(),height:b.outerHeight(),offset:b.offset()}}a.ui=a.ui||{};var f,h=Math.max,m=Math.abs,g=Math.round,r=/left|center|right/,n=/top|center|bottom/,D=/[\+\-]\d+(\.[\d]+)?%?/,q=/^\w+/,u=/%$/,w=a.fn.position;a.position={scrollbarWidth:function(){if(f!==b)return f;var c,d,g=a("<div style='display:block;width:50px;height:50px;overflow:hidden;'><div style='height:100px;width:auto;'></div></div>");
d=g.children()[0];a("body").append(g);c=d.offsetWidth;g.css("overflow","scroll");d=d.offsetWidth;c===d&&(d=g[0].clientWidth);g.remove();return f=c-d},getScrollInfo:function(b){var c=b.isWindow?"":b.element.css("overflow-x"),d=b.isWindow?"":b.element.css("overflow-y"),c="scroll"===c||"auto"===c&&b.width<b.element[0].scrollWidth;return{width:"scroll"===d||"auto"===d&&b.height<b.element[0].scrollHeight?a.position.scrollbarWidth():0,height:c?a.position.scrollbarWidth():0}},getWithinInfo:function(b){b=
a(b||l);var c=a.isWindow(b[0]);return{element:b,isWindow:c,offset:b.offset()||{left:0,top:0},scrollLeft:b.scrollLeft(),scrollTop:b.scrollTop(),width:c?b.width():b.outerWidth(),height:c?b.height():b.outerHeight()}}};a.fn.position=function(b){if(!b||!b.of)return w.apply(this,arguments);b=a.extend({},b);var e,f,l,u,v,A,H=a(b.of),z=a.position.getWithinInfo(b.within),F=a.position.getScrollInfo(z),G=(b.collision||"flip").split(" "),J={};A=c(H);H[0].preventDefault&&(b.at="left top");f=A.width;l=A.height;
u=A.offset;v=a.extend({},u);a.each(["my","at"],function(){var a=(b[this]||"").split(" "),c,d;1===a.length&&(a=r.test(a[0])?a.concat(["center"]):n.test(a[0])?["center"].concat(a):["center","center"]);a[0]=r.test(a[0])?a[0]:"center";a[1]=n.test(a[1])?a[1]:"center";c=D.exec(a[0]);d=D.exec(a[1]);J[this]=[c?c[0]:0,d?d[0]:0];b[this]=[q.exec(a[0])[0],q.exec(a[1])[0]]});1===G.length&&(G[1]=G[0]);"right"===b.at[0]?v.left+=f:"center"===b.at[0]&&(v.left+=f/2);"bottom"===b.at[1]?v.top+=l:"center"===b.at[1]&&
(v.top+=l/2);e=d(J.at,f,l);v.left+=e[0];v.top+=e[1];return this.each(function(){var c,r,n=a(this),q=n.outerWidth(),A=n.outerHeight(),C=parseInt(a.css(this,"marginLeft"),10)||0,w=parseInt(a.css(this,"marginTop"),10)||0,D=q+C+(parseInt(a.css(this,"marginRight"),10)||0)+F.width,K=A+w+(parseInt(a.css(this,"marginBottom"),10)||0)+F.height,E=a.extend({},v),I=d(J.my,n.outerWidth(),n.outerHeight());"right"===b.my[0]?E.left-=q:"center"===b.my[0]&&(E.left-=q/2);"bottom"===b.my[1]?E.top-=A:"center"===b.my[1]&&
(E.top-=A/2);E.left+=I[0];E.top+=I[1];a.support.offsetFractions||(E.left=g(E.left),E.top=g(E.top));c={marginLeft:C,marginTop:w};a.each(["left","top"],function(d,g){if(a.ui.position[G[d]])a.ui.position[G[d]][g](E,{targetWidth:f,targetHeight:l,elemWidth:q,elemHeight:A,collisionPosition:c,collisionWidth:D,collisionHeight:K,offset:[e[0]+I[0],e[1]+I[1]],my:b.my,at:b.at,within:z,elem:n})});b.using&&(r=function(a){var c=u.left-E.left,d=c+f-q,e=u.top-E.top,g=e+l-A,r={target:{element:H,left:u.left,top:u.top,
width:f,height:l},element:{element:n,left:E.left,top:E.top,width:q,height:A},horizontal:0>d?"left":0<c?"right":"center",vertical:0>g?"top":0<e?"bottom":"middle"};f<q&&m(c+d)<f&&(r.horizontal="center");l<A&&m(e+g)<l&&(r.vertical="middle");h(m(c),m(d))>h(m(e),m(g))?r.important="horizontal":r.important="vertical";b.using.call(this,a,r)});n.offset(a.extend(E,{using:r}))})};a.ui.position={fit:{left:function(a,b){var c=b.within,d=c.isWindow?c.scrollLeft:c.offset.left,e=c.width,g=a.left-b.collisionPosition.marginLeft,
c=d-g,f=g+b.collisionWidth-e-d;b.collisionWidth>e?0<c&&0>=f?(d=a.left+c+b.collisionWidth-e-d,a.left+=c-d):a.left=0<f&&0>=c?d:c>f?d+e-b.collisionWidth:d:a.left=0<c?a.left+c:0<f?a.left-f:h(a.left-g,a.left)},top:function(a,b){var c=b.within,d=c.isWindow?c.scrollTop:c.offset.top,e=b.within.height,g=a.top-b.collisionPosition.marginTop,c=d-g,f=g+b.collisionHeight-e-d;b.collisionHeight>e?0<c&&0>=f?(d=a.top+c+b.collisionHeight-e-d,a.top+=c-d):a.top=0<f&&0>=c?d:c>f?d+e-b.collisionHeight:d:a.top=0<c?a.top+
c:0<f?a.top-f:h(a.top-g,a.top)}},flip:{left:function(a,b){var c=b.within,d=c.offset.left+c.scrollLeft,e=c.width,g=c.isWindow?c.scrollLeft:c.offset.left,f=a.left-b.collisionPosition.marginLeft,c=f-g,h=f+b.collisionWidth-e-g,f="left"===b.my[0]?-b.elemWidth:"right"===b.my[0]?b.elemWidth:0,k="left"===b.at[0]?b.targetWidth:"right"===b.at[0]?-b.targetWidth:0,l=-2*b.offset[0];if(0>c){if(d=a.left+f+k+l+b.collisionWidth-e-d,0>d||d<m(c))a.left+=f+k+l}else 0<h&&(d=a.left-b.collisionPosition.marginLeft+f+k+l-
g,0<d||m(d)<h)&&(a.left+=f+k+l)},top:function(a,b){var c=b.within,d=c.offset.top+c.scrollTop,e=c.height,g=c.isWindow?c.scrollTop:c.offset.top,f=a.top-b.collisionPosition.marginTop,c=f-g,h=f+b.collisionHeight-e-g,f="top"===b.my[1]?-b.elemHeight:"bottom"===b.my[1]?b.elemHeight:0,k="top"===b.at[1]?b.targetHeight:"bottom"===b.at[1]?-b.targetHeight:0,l=-2*b.offset[1];0>c?(d=a.top+f+k+l+b.collisionHeight-e-d,a.top+f+k+l>c&&(0>d||d<m(c))&&(a.top+=f+k+l)):0<h&&(d=a.top-b.collisionPosition.marginTop+f+k+l-
g,a.top+f+k+l>h&&(0<d||m(d)<h)&&(a.top+=f+k+l))}},flipfit:{left:function(){a.ui.position.flip.left.apply(this,arguments);a.ui.position.fit.left.apply(this,arguments)},top:function(){a.ui.position.flip.top.apply(this,arguments);a.ui.position.fit.top.apply(this,arguments)}}};(function(){var b,c,d,e,g=document.getElementsByTagName("body")[0];d=document.createElement("div");b=document.createElement(g?"div":"body");c={visibility:"hidden",width:0,height:0,border:0,margin:0,background:"none"};g&&a.extend(c,
{position:"absolute",left:"-1000px",top:"-1000px"});for(e in c)b.style[e]=c[e];b.appendChild(d);c=g||document.documentElement;c.insertBefore(b,c.firstChild);d.style.cssText="position: absolute; left: 10.7432222px;";d=a(d).offset().left;a.support.offsetFractions=10<d&&11>d;b.innerHTML="";c.removeChild(b)})()})(b);return b})});
/* ******** */
(function(h){var l=window.AmazonUIPageJS||window.P,n=l._namespace||l.attributeErrors,b=n?n("JQueryUI_Widget_AUIBuild"):l;b.guardFatal?b.guardFatal(h)(b,window):b.execute(function(){h(b,window)})})(function(h,l,n){h.when("jQuery").register("jQueryUI-widget",function(b){(function(a,b){var d=0,c=Array.prototype.slice,f=a.cleanData;a.cleanData=function(b){for(var c=0,d;null!=(d=b[c]);c++)try{a(d).triggerHandler("remove")}catch(e){}f(b)};a.widget=function(b,c,d){var e,f,h,l,n={},w=b.split(".")[0];b=b.split(".")[1];
e=w+"-"+b;d||(d=c,c=a.Widget);a.expr[":"][e.toLowerCase()]=function(b){return!!a.data(b,e)};a[w]=a[w]||{};f=a[w][b];h=a[w][b]=function(a,b){if(!this._createWidget)return new h(a,b);arguments.length&&this._createWidget(a,b)};a.extend(h,f,{version:d.version,_proto:a.extend({},d),_childConstructors:[]});l=new c;l.options=a.widget.extend({},l.options);a.each(d,function(b,d){a.isFunction(d)?n[b]=function(){var a=function(){return c.prototype[b].apply(this,arguments)},e=function(a){return c.prototype[b].apply(this,
a)};return function(){var b=this._super,c=this._superApply,g;this._super=a;this._superApply=e;g=d.apply(this,arguments);this._super=b;this._superApply=c;return g}}():n[b]=d});h.prototype=a.widget.extend(l,{widgetEventPrefix:f?l.widgetEventPrefix:b},n,{constructor:h,namespace:w,widgetName:b,widgetFullName:e});f?(a.each(f._childConstructors,function(b,c){var d=c.prototype;a.widget(d.namespace+"."+d.widgetName,h,c._proto)}),delete f._childConstructors):c._childConstructors.push(h);a.widget.bridge(b,
h)};a.widget.extend=function(d){for(var f=c.call(arguments,1),g=0,h=f.length,l,n;g<h;g++)for(l in f[g])n=f[g][l],f[g].hasOwnProperty(l)&&n!==b&&(a.isPlainObject(n)?d[l]=a.isPlainObject(d[l])?a.widget.extend({},d[l],n):a.widget.extend({},n):d[l]=n);return d};a.widget.bridge=function(d,f){var g=f.prototype.widgetFullName||d;a.fn[d]=function(h){var l="string"===typeof h,n=c.call(arguments,1),q=this;h=!l&&n.length?a.widget.extend.apply(null,[h].concat(n)):h;l?this.each(function(){var c,f=a.data(this,
g);if(!f)return a.error("cannot call methods on "+d+" prior to initialization; attempted to call method '"+h+"'");if(!a.isFunction(f[h])||"_"===h.charAt(0))return a.error("no such method '"+h+"' for "+d+" widget instance");c=f[h].apply(f,n);if(c!==f&&c!==b)return q=c&&c.jquery?q.pushStack(c.get()):c,!1}):this.each(function(){var b=a.data(this,g);b?b.option(h||{})._init():a.data(this,g,new f(h,this))});return q}};a.Widget=function(){};a.Widget._childConstructors=[];a.Widget.prototype={widgetName:"widget",
widgetEventPrefix:"",defaultElement:"<div>",options:{disabled:!1,create:null},_createWidget:function(b,c){c=a(c||this.defaultElement||this)[0];this.element=a(c);this.uuid=d++;this.eventNamespace="."+this.widgetName+this.uuid;this.options=a.widget.extend({},this.options,this._getCreateOptions(),b);this.bindings=a();this.hoverable=a();this.focusable=a();c!==this&&(a.data(c,this.widgetFullName,this),this._on(!0,this.element,{remove:function(a){a.target===c&&this.destroy()}}),this.document=a(c.style?
c.ownerDocument:c.document||c),this.window=a(this.document[0].defaultView||this.document[0].parentWindow));this._create();this._trigger("create",null,this._getCreateEventData());this._init()},_getCreateOptions:a.noop,_getCreateEventData:a.noop,_create:a.noop,_init:a.noop,destroy:function(){this._destroy();this.element.unbind(this.eventNamespace).removeData(this.widgetName).removeData(this.widgetFullName).removeData(a.camelCase(this.widgetFullName));this.widget().unbind(this.eventNamespace).removeAttr("aria-disabled").removeClass(this.widgetFullName+
"-disabled ui-state-disabled");this.bindings.unbind(this.eventNamespace);this.hoverable.removeClass("ui-state-hover");this.focusable.removeClass("ui-state-focus")},_destroy:a.noop,widget:function(){return this.element},option:function(c,d){var g=c,f,h,l;if(0===arguments.length)return a.widget.extend({},this.options);if("string"===typeof c)if(g={},f=c.split("."),c=f.shift(),f.length){h=g[c]=a.widget.extend({},this.options[c]);for(l=0;l<f.length-1;l++)h[f[l]]=h[f[l]]||{},h=h[f[l]];c=f.pop();if(d===
b)return h[c]===b?null:h[c];h[c]=d}else{if(d===b)return this.options[c]===b?null:this.options[c];g[c]=d}this._setOptions(g);return this},_setOptions:function(a){for(var b in a)this._setOption(b,a[b]);return this},_setOption:function(a,b){this.options[a]=b;"disabled"===a&&(this.widget().toggleClass(this.widgetFullName+"-disabled ui-state-disabled",!!b).attr("aria-disabled",b),this.hoverable.removeClass("ui-state-hover"),this.focusable.removeClass("ui-state-focus"));return this},enable:function(){return this._setOption("disabled",
!1)},disable:function(){return this._setOption("disabled",!0)},_on:function(b,c,d){var e,f=this;"boolean"!==typeof b&&(d=c,c=b,b=!1);d?(c=e=a(c),this.bindings=this.bindings.add(c)):(d=c,c=this.element,e=this.widget());a.each(d,function(d,g){function h(){if(b||!0!==f.options.disabled&&!a(this).hasClass("ui-state-disabled"))return("string"===typeof g?f[g]:g).apply(f,arguments)}"string"!==typeof g&&(h.guid=g.guid=g.guid||h.guid||a.guid++);var l=d.match(/^(\w+)\s*(.*)$/),n=l[1]+f.eventNamespace;(l=l[2])?
e.delegate(l,n,h):c.bind(n,h)})},_off:function(a,b){b=(b||"").split(" ").join(this.eventNamespace+" ")+this.eventNamespace;a.unbind(b).undelegate(b)},_delay:function(a,b){var c=this;return setTimeout(function(){return("string"===typeof a?c[a]:a).apply(c,arguments)},b||0)},_hoverable:function(b){this.hoverable=this.hoverable.add(b);this._on(b,{mouseenter:function(b){a(b.currentTarget).addClass("ui-state-hover")},mouseleave:function(b){a(b.currentTarget).removeClass("ui-state-hover")}})},_focusable:function(b){this.focusable=
this.focusable.add(b);this._on(b,{focusin:function(b){a(b.currentTarget).addClass("ui-state-focus")},focusout:function(b){a(b.currentTarget).removeClass("ui-state-focus")}})},_trigger:function(b,c,d){var e,f=this.options[b];d=d||{};c=a.Event(c);c.type=(b===this.widgetEventPrefix?b:this.widgetEventPrefix+b).toLowerCase();c.target=this.element[0];if(b=c.originalEvent)for(e in b)e in c||(c[e]=b[e]);this.element.trigger(c,d);return!(a.isFunction(f)&&!1===f.apply(this.element[0],[c].concat(d))||c.isDefaultPrevented())}};
a.each({show:"fadeIn",hide:"fadeOut"},function(b,c){a.Widget.prototype["_"+b]=function(d,e,f){"string"===typeof e&&(e={effect:e});var h,l=e?!0===e||"number"===typeof e?c:e.effect||c:b;e=e||{};"number"===typeof e&&(e={duration:e});h=!a.isEmptyObject(e);e.complete=f;e.delay&&d.delay(e.delay);if(h&&a.effects&&a.effects.effect[l])d[b](e);else if(l!==b&&d[l])d[l](e.duration,e.easing,f);else d.queue(function(c){a(this)[b]();f&&f.call(d[0]);c()})}})})(b);return b})});
/* ******** */
(function(h){var l=window.AmazonUIPageJS||window.P,n=l._namespace||l.attributeErrors,b=n?n("JQueryUI_Menu_AUIBuild"):l;b.guardFatal?b.guardFatal(h)(b,window):b.execute(function(){h(b,window)})})(function(h,l,n){h.when("jQueryUI-core","jQueryUI-position","jQueryUI-widget").register("jQueryUI-menu",function(b){(function(a,b){a.widget("ui.menu",{version:"1.10.3",defaultElement:"<ul>",delay:300,options:{icons:{submenu:"ui-icon-carat-1-e"},menus:"ul",position:{my:"left top",at:"right top"},role:"menu",
blur:null,focus:null,select:null},_create:function(){this.activeMenu=this.element;this.mouseHandled=!1;this.element.uniqueId().addClass("ui-menu ui-widget ui-widget-content ui-corner-all").toggleClass("ui-menu-icons",!!this.element.find(".ui-icon").length).attr({role:this.options.role,tabIndex:0}).bind("click"+this.eventNamespace,a.proxy(function(a){this.options.disabled&&a.preventDefault()},this));this.options.disabled&&this.element.addClass("ui-state-disabled").attr("aria-disabled","true");this._on({"mousedown .ui-menu-item > a":function(a){a.preventDefault()},
"click .ui-state-disabled > a":function(a){a.preventDefault()},"click .ui-menu-item:has(a)":function(b){var c=a(b.target).closest(".ui-menu-item");!this.mouseHandled&&c.not(".ui-state-disabled").length&&(this.mouseHandled=!0,this.select(b),c.has(".ui-menu").length?this.expand(b):this.element.is(":focus")||(this.element.trigger("focus",[!0]),this.active&&1===this.active.parents(".ui-menu").length&&clearTimeout(this.timer)))},"mouseenter .ui-menu-item":function(b){var c=a(b.currentTarget);c.siblings().children(".ui-state-active").removeClass("ui-state-active");
this.focus(b,c)},mouseleave:"collapseAll","mouseleave .ui-menu":"collapseAll",focus:function(a,b){var e=this.active||this.element.children(".ui-menu-item").eq(0);b||this.focus(a,e)},blur:function(b){this._delay(function(){a.contains(this.element[0],this.document[0].activeElement)||this.collapseAll(b)})},keydown:"_keydown"});this.refresh();this._on(this.document,{click:function(b){a(b.target).closest(".ui-menu").length||this.collapseAll(b);this.mouseHandled=!1}})},_destroy:function(){this.element.removeAttr("aria-activedescendant").find(".ui-menu").addBack().removeClass("ui-menu ui-widget ui-widget-content ui-corner-all ui-menu-icons").removeAttr("role").removeAttr("tabIndex").removeAttr("aria-labelledby").removeAttr("aria-expanded").removeAttr("aria-hidden").removeAttr("aria-disabled").removeUniqueId().show();
this.element.find(".ui-menu-item").removeClass("ui-menu-item").removeAttr("role").removeAttr("aria-disabled").children("a").removeUniqueId().removeClass("ui-corner-all ui-state-hover").removeAttr("tabIndex").removeAttr("role").removeAttr("aria-haspopup").children().each(function(){var b=a(this);b.data("ui-menu-submenu-carat")&&b.remove()});this.element.find(".ui-menu-divider").removeClass("ui-menu-divider ui-widget-content")},_keydown:function(b){function c(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,
"\\$&")}var e,k,h,g,l=!0;switch(b.keyCode){case a.ui.keyCode.PAGE_UP:this.previousPage(b);break;case a.ui.keyCode.PAGE_DOWN:this.nextPage(b);break;case a.ui.keyCode.HOME:this._move("first","first",b);break;case a.ui.keyCode.END:this._move("last","last",b);break;case a.ui.keyCode.UP:this.previous(b);break;case a.ui.keyCode.DOWN:this.next(b);break;case a.ui.keyCode.LEFT:this.collapse(b);break;case a.ui.keyCode.RIGHT:this.active&&!this.active.is(".ui-state-disabled")&&this.expand(b);break;case a.ui.keyCode.ENTER:case a.ui.keyCode.SPACE:this._activate(b);
break;case a.ui.keyCode.ESCAPE:this.collapse(b);break;default:l=!1,e=this.previousFilter||"",k=String.fromCharCode(b.keyCode),h=!1,clearTimeout(this.filterTimer),k===e?h=!0:k=e+k,g=new RegExp("^"+c(k),"i"),e=this.activeMenu.children(".ui-menu-item").filter(function(){return g.test(a(this).children("a").text())}),e=h&&-1!==e.index(this.active.next())?this.active.nextAll(".ui-menu-item"):e,e.length||(k=String.fromCharCode(b.keyCode),g=new RegExp("^"+c(k),"i"),e=this.activeMenu.children(".ui-menu-item").filter(function(){return g.test(a(this).children("a").text())})),
e.length?(this.focus(b,e),1<e.length?(this.previousFilter=k,this.filterTimer=this._delay(function(){delete this.previousFilter},1E3)):delete this.previousFilter):delete this.previousFilter}l&&b.preventDefault()},_activate:function(a){this.active.is(".ui-state-disabled")||(this.active.children("a[aria-haspopup='true']").length?this.expand(a):this.select(a))},refresh:function(){var b,c=this.options.icons.submenu;b=this.element.find(this.options.menus);b.filter(":not(.ui-menu)").addClass("ui-menu ui-widget ui-widget-content ui-corner-all").hide().attr({role:this.options.role,
"aria-hidden":"true","aria-expanded":"false"}).each(function(){var b=a(this),d=b.prev("a"),e=a("<span>").addClass("ui-menu-icon ui-icon "+c).data("ui-menu-submenu-carat",!0);d.attr("aria-haspopup","true").prepend(e);b.attr("aria-labelledby",d.attr("id"))});b=b.add(this.element);b.children(":not(.ui-menu-item):has(a)").addClass("ui-menu-item").attr("role","presentation").children("a").uniqueId().addClass("ui-corner-all").attr({tabIndex:-1,role:this._itemRole()});b.children(":not(.ui-menu-item)").each(function(){var b=
a(this);/[^\-\u2014\u2013\s]/.test(b.text())||b.addClass("ui-widget-content ui-menu-divider")});b.children(".ui-state-disabled").attr("aria-disabled","true");this.active&&!a.contains(this.element[0],this.active[0])&&this.blur()},_itemRole:function(){return{menu:"menuitem",listbox:"option"}[this.options.role]},_setOption:function(a,b){"icons"===a&&this.element.find(".ui-menu-icon").removeClass(this.options.icons.submenu).addClass(b.submenu);this._super(a,b)},focus:function(a,b){var e;this.blur(a,a&&
"focus"===a.type);this._scrollIntoView(b);this.active=b.first();e=this.active.children("a").addClass("ui-state-focus");this.options.role&&this.element.attr("aria-activedescendant",e.attr("id"));this.active.parent().closest(".ui-menu-item").children("a:first").addClass("ui-state-active");a&&"keydown"===a.type?this._close():this.timer=this._delay(function(){this._close()},this.delay);e=b.children(".ui-menu");e.length&&/^mouse/.test(a.type)&&this._startOpening(e);this.activeMenu=b.parent();this._trigger("focus",
a,{item:b})},_scrollIntoView:function(b){var c,e,h;this._hasScroll()&&(c=parseFloat(a.css(this.activeMenu[0],"borderTopWidth"))||0,e=parseFloat(a.css(this.activeMenu[0],"paddingTop"))||0,c=b.offset().top-this.activeMenu.offset().top-c-e,e=this.activeMenu.scrollTop(),h=this.activeMenu.height(),b=b.height(),0>c?this.activeMenu.scrollTop(e+c):c+b>h&&this.activeMenu.scrollTop(e+c-h+b))},blur:function(a,b){b||clearTimeout(this.timer);this.active&&(this.active.children("a").removeClass("ui-state-focus"),
this.active=null,this._trigger("blur",a,{item:this.active}))},_startOpening:function(a){clearTimeout(this.timer);"true"===a.attr("aria-hidden")&&(this.timer=this._delay(function(){this._close();this._open(a)},this.delay))},_open:function(b){var c=a.extend({of:this.active},this.options.position);clearTimeout(this.timer);this.element.find(".ui-menu").not(b.parents(".ui-menu")).hide().attr("aria-hidden","true");b.show().removeAttr("aria-hidden").attr("aria-expanded","true").position(c)},collapseAll:function(b,
c){clearTimeout(this.timer);this.timer=this._delay(function(){var e=c?this.element:a(b&&b.target).closest(this.element.find(".ui-menu"));e.length||(e=this.element);this._close(e);this.blur(b);this.activeMenu=e},this.delay)},_close:function(a){a||(a=this.active?this.active.parent():this.element);a.find(".ui-menu").hide().attr("aria-hidden","true").attr("aria-expanded","false").end().find("a.ui-state-active").removeClass("ui-state-active")},collapse:function(a){var b=this.active&&this.active.parent().closest(".ui-menu-item",
this.element);b&&b.length&&(this._close(),this.focus(a,b))},expand:function(a){var b=this.active&&this.active.children(".ui-menu ").children(".ui-menu-item").first();b&&b.length&&(this._open(b.parent()),this._delay(function(){this.focus(a,b)}))},next:function(a){this._move("next","first",a)},previous:function(a){this._move("prev","last",a)},isFirstItem:function(){return this.active&&!this.active.prevAll(".ui-menu-item").length},isLastItem:function(){return this.active&&!this.active.nextAll(".ui-menu-item").length},
_move:function(a,b,e){var h;this.active&&(h="first"===a||"last"===a?this.active["first"===a?"prevAll":"nextAll"](".ui-menu-item").eq(-1):this.active[a+"All"](".ui-menu-item").eq(0));h&&h.length&&this.active||(h=this.activeMenu.children(".ui-menu-item")[b]());this.focus(e,h)},nextPage:function(b){var c,e,h;this.active?this.isLastItem()||(this._hasScroll()?(e=this.active.offset().top,h=this.element.height(),this.active.nextAll(".ui-menu-item").each(function(){c=a(this);return 0>c.offset().top-e-h}),
this.focus(b,c)):this.focus(b,this.activeMenu.children(".ui-menu-item")[this.active?"last":"first"]())):this.next(b)},previousPage:function(b){var c,e,h;this.active?this.isFirstItem()||(this._hasScroll()?(e=this.active.offset().top,h=this.element.height(),this.active.prevAll(".ui-menu-item").each(function(){c=a(this);return 0<c.offset().top-e+h}),this.focus(b,c)):this.focus(b,this.activeMenu.children(".ui-menu-item").first())):this.next(b)},_hasScroll:function(){return this.element.outerHeight()<
this.element.prop("scrollHeight")},select:function(b){this.active=this.active||a(b.target).closest(".ui-menu-item");var c={item:this.active};this.active.has(".ui-menu").length||this.collapseAll(b,!0);this._trigger("select",b,c)}})})(b)})});
/* ******** */
(function(h){var l=window.AmazonUIPageJS||window.P,n=l._namespace||l.attributeErrors,b=n?n("JQueryUI_Autocomplete_AUIBuild"):l;b.guardFatal?b.guardFatal(h)(b,window):b.execute(function(){h(b,window)})})(function(h,l,n){h.when("jQueryUI-core","jQueryUI-position","jQueryUI-widget","jQueryUI-menu").register("jQueryUI-autocomplete",function(b){(function(a,b){var d=0;a.widget("ui.autocomplete",{version:"1.10.3",defaultElement:"<input>",options:{appendTo:null,autoFocus:!1,delay:300,minLength:1,position:{my:"left top",
at:"left bottom",collision:"none"},source:null,change:null,close:null,focus:null,open:null,response:null,search:null,select:null},pending:0,_create:function(){var b,d,e,h=this.element[0].nodeName.toLowerCase(),g="textarea"===h,h="input"===h;this.isMultiLine=g?!0:h?!1:this.element.prop("isContentEditable");this.valueMethod=this.element[g||h?"val":"text"];this.isNewMenu=!0;this.element.addClass("ui-autocomplete-input").attr("autocomplete","off");this._on(this.element,{keydown:function(g){if(this.element.prop("readOnly"))d=
e=b=!0;else{d=e=b=!1;var h=a.ui.keyCode;switch(g.keyCode){case h.PAGE_UP:b=!0;this._move("previousPage",g);break;case h.PAGE_DOWN:b=!0;this._move("nextPage",g);break;case h.UP:b=!0;this._keyEvent("previous",g);break;case h.DOWN:b=!0;this._keyEvent("next",g);break;case h.ENTER:case h.NUMPAD_ENTER:this.menu.active&&(b=!0,g.preventDefault(),this.menu.select(g));break;case h.TAB:this.menu.active&&this.menu.select(g);break;case h.ESCAPE:this.menu.element.is(":visible")&&(this._value(this.term),this.close(g),
g.preventDefault());break;default:d=!0,this._searchTimeout(g)}}},keypress:function(e){if(b)b=!1,this.isMultiLine&&!this.menu.element.is(":visible")||e.preventDefault();else if(!d){var g=a.ui.keyCode;switch(e.keyCode){case g.PAGE_UP:this._move("previousPage",e);break;case g.PAGE_DOWN:this._move("nextPage",e);break;case g.UP:this._keyEvent("previous",e);break;case g.DOWN:this._keyEvent("next",e)}}},input:function(a){e?(e=!1,a.preventDefault()):this._searchTimeout(a)},focus:function(){this.selectedItem=
null;this.previous=this._value()},blur:function(a){this.cancelBlur?delete this.cancelBlur:(clearTimeout(this.searching),this.close(a),this._change(a))}});this._initSource();this.menu=a("<ul>").addClass("ui-autocomplete ui-front").appendTo(this._appendTo()).menu({role:null}).hide().data("ui-menu");this._on(this.menu.element,{mousedown:function(b){b.preventDefault();this.cancelBlur=!0;this._delay(function(){delete this.cancelBlur});var c=this.menu.element[0];a(b.target).closest(".ui-menu-item").length||
this._delay(function(){var b=this;this.document.one("mousedown",function(d){d.target===b.element[0]||d.target===c||a.contains(c,d.target)||b.close()})})},menufocus:function(b,c){if(this.isNewMenu&&(this.isNewMenu=!1,b.originalEvent&&/^mouse/.test(b.originalEvent.type))){this.menu.blur();this.document.one("mousemove",function(){a(b.target).trigger(b.originalEvent)});return}var d=c.item.data("ui-autocomplete-item");!1!==this._trigger("focus",b,{item:d})?b.originalEvent&&/^key/.test(b.originalEvent.type)&&
this._value(d.value):this.liveRegion.text(d.value)},menuselect:function(a,b){var c=b.item.data("ui-autocomplete-item"),d=this.previous;this.element[0]!==this.document[0].activeElement&&(this.element.focus(),this.previous=d,this._delay(function(){this.previous=d;this.selectedItem=c}));!1!==this._trigger("select",a,{item:c})&&this._value(c.value);this.term=this._value();this.close(a);this.selectedItem=c}});this.liveRegion=a("<span>",{role:"status","aria-live":"polite"}).addClass("ui-helper-hidden-accessible").insertBefore(this.element);
this._on(this.window,{beforeunload:function(){this.element.removeAttr("autocomplete")}})},_destroy:function(){clearTimeout(this.searching);this.element.removeClass("ui-autocomplete-input").removeAttr("autocomplete");this.menu.element.remove();this.liveRegion.remove()},_setOption:function(a,b){this._super(a,b);"source"===a&&this._initSource();"appendTo"===a&&this.menu.element.appendTo(this._appendTo());"disabled"===a&&b&&this.xhr&&this.xhr.abort()},_appendTo:function(){var b=this.options.appendTo;
b&&(b=b.jquery||b.nodeType?a(b):this.document.find(b).eq(0));b||(b=this.element.closest(".ui-front"));b.length||(b=this.document[0].body);return b},_initSource:function(){var b,d,e=this;a.isArray(this.options.source)?(b=this.options.source,this.source=function(d,e){e(a.ui.autocomplete.filter(b,d.term))}):"string"===typeof this.options.source?(d=this.options.source,this.source=function(b,c){e.xhr&&e.xhr.abort();e.xhr=a.ajax({url:d,data:b,dataType:"json",success:function(a){c(a)},error:function(){c([])}})}):
this.source=this.options.source},_searchTimeout:function(a){clearTimeout(this.searching);this.searching=this._delay(function(){this.term!==this._value()&&(this.selectedItem=null,this.search(null,a))},this.options.delay)},search:function(a,b){a=null!=a?a:this._value();this.term=this._value();if(a.length<this.options.minLength)return this.close(b);if(!1!==this._trigger("search",b))return this._search(a)},_search:function(a){this.pending++;this.element.addClass("ui-autocomplete-loading");this.cancelSearch=
!1;this.source({term:a},this._response())},_response:function(){var a=this,b=++d;return function(e){b===d&&a.__response(e);a.pending--;a.pending||a.element.removeClass("ui-autocomplete-loading")}},__response:function(a){a&&(a=this._normalize(a));this._trigger("response",null,{content:a});!this.options.disabled&&a&&a.length&&!this.cancelSearch?(this._suggest(a),this._trigger("open")):this._close()},close:function(a){this.cancelSearch=!0;this._close(a)},_close:function(a){this.menu.element.is(":visible")&&
(this.menu.element.hide(),this.menu.blur(),this.isNewMenu=!0,this._trigger("close",a))},_change:function(a){this.previous!==this._value()&&this._trigger("change",a,{item:this.selectedItem})},_normalize:function(b){return b.length&&b[0].label&&b[0].value?b:a.map(b,function(b){return"string"===typeof b?{label:b,value:b}:a.extend({label:b.label||b.value,value:b.value||b.label},b)})},_suggest:function(b){var d=this.menu.element.empty();this._renderMenu(d,b);this.isNewMenu=!0;this.menu.refresh();d.show();
this._resizeMenu();d.position(a.extend({of:this.element},this.options.position));this.options.autoFocus&&this.menu.next()},_resizeMenu:function(){var a=this.menu.element;a.outerWidth(Math.max(a.width("").outerWidth()+1,this.element.outerWidth()))},_renderMenu:function(b,d){var e=this;a.each(d,function(a,d){e._renderItemData(b,d)})},_renderItemData:function(a,b){return this._renderItem(a,b).data("ui-autocomplete-item",b)},_renderItem:function(b,d){return a("<li>").append(a("<a>").text(d.label)).appendTo(b)},
_move:function(a,b){if(this.menu.element.is(":visible"))if(this.menu.isFirstItem()&&/^previous/.test(a)||this.menu.isLastItem()&&/^next/.test(a))this._value(this.term),this.menu.blur();else this.menu[a](b);else this.search(null,b)},widget:function(){return this.menu.element},_value:function(){return this.valueMethod.apply(this.element,arguments)},_keyEvent:function(a,b){if(!this.isMultiLine||this.menu.element.is(":visible"))this._move(a,b),b.preventDefault()}});a.extend(a.ui.autocomplete,{escapeRegex:function(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,
"\\$&")},filter:function(b,d){var e=new RegExp(a.ui.autocomplete.escapeRegex(d),"i");return a.grep(b,function(a){return e.test(a.label||a.value||a)})}});a.widget("ui.autocomplete",a.ui.autocomplete,{options:{messages:{noResults:"No search results.",results:function(a){return a+(1<a?" results are":" result is")+" available, use up and down arrow keys to navigate."}}},__response:function(a){var b;this._superApply(arguments);this.options.disabled||this.cancelSearch||(b=a&&a.length?this.options.messages.results(a.length):
this.options.messages.noResults,this.liveRegion.text(b))}})})(b)})});
/* ******** */
(function(h){var l=window.AmazonUIPageJS||window.P,n=l._namespace||l.attributeErrors,b=n?n("JQuery_Cookie_AUIBuild"):l;b.guardFatal?b.guardFatal(h)(b,window):b.execute(function(){h(b,window)})})(function(h,l,n){h.when("jQuery").register("jQuery-Cookie",function(b){(function(a){"function"===typeof define&&define.amd?define(["jquery"],a):a(b)})(function(a){function b(a){return f.raw?a:decodeURIComponent(a.replace(c," "))}function d(a){0===a.indexOf('"')&&(a=a.slice(1,-1).replace(/\\"/g,'"').replace(/\\\\/g,
"\\"));a=b(a);try{return f.json?JSON.parse(a):a}catch(c){}}var c=/\+/g,f=a.cookie=function(c,h,g){if(h!==n){g=a.extend({},f.defaults,g);if("number"===typeof g.expires){var l=g.expires,C=g.expires=new Date;C.setDate(C.getDate()+l)}h=f.json?JSON.stringify(h):String(h);return document.cookie=[f.raw?c:encodeURIComponent(c),"=",f.raw?h:encodeURIComponent(h),g.expires?"; expires="+g.expires.toUTCString():"",g.path?"; path="+g.path:"",g.domain?"; domain="+g.domain:"",g.secure?"; secure":""].join("")}h=document.cookie.split("; ");
g=c?n:{};l=0;for(C=h.length;l<C;l++){var D=h[l].split("="),q=b(D.shift()),D=D.join("=");if(c&&c===q){g=d(D);break}c||(g[q]=d(D))}return g};f.defaults={};a.removeCookie=function(b,c){return a.cookie(b)!==n?(a.cookie(b,"",a.extend({},c,{expires:-1})),!0):!1}})})});
/* ******** */
(function(h){var l=window.AmazonUIPageJS||window.P,n=l._namespace||l.attributeErrors,b=n?n("AuthenticationPortalAssets"):l;b.guardFatal?b.guardFatal(h)(b,window):b.execute(function(){h(b,window)})})(function(h,l,n){h.when("A","cvf","ready").register("auth-account-switcher",function(b,a){function e(a){return n}function d(a){l.location=c(l.location);return n}function c(a){var c=a.search;return c?c.match(k)?a.href.replace(k,"$1ACCOUNT_SWITCH_FAILED"):a.href+"&errorCodes=ACCOUNT_SWITCH_FAILED":a.href+
"?errorCodes=ACCOUNT_SWITCH_FAILED"}var f=b.$,k=/(errorCodes=)[\w\d]+/g;f("#ap-account-switcher-container").length&&"undefined"!==typeof f("#ap-account-switcher-container").attr("data-token")&&(f={target:f("#ap-account-switcher-container"),requestToken:f("#ap-account-switcher-container").attr("data-token"),requestArbToken:f("#ap-account-switcher-container").attr("data-arbToken"),onSuccess:e,onError:d,autoStart:!1,widgetMetricsScope:"CvfAccountSwitcherClientSideMetrics"},a.create(f).start());return{getUrlWithSwitchErrorCodeAdded:c}});
h.when("A","ready").register("auth-login-autofill",function(b){function a(a){var d=a.data("claim");a.val()!==d&&a.val(d)}function e(a,b){var e=d(a);e.change(function(){b(d(this))});b(e)}var d=b.$;e("#ap-credential-autofill-hint",a);return{monitorForChanges:e,restoreClaimValue:a}});h.register("AmazonHelpPopup",function(){return function(b,a,e){l.open(b,a,e).focus();return!1}});h.when("A","ready").execute(function(b){b.$(".auth-autofocus").first().focus()});
h.when("A","ready").execute(function(b){function a(){location.href=d.returnToAddress}function e(){clearTimeout(c);c=setTimeout(a,f)}var d=b.state("timeout-parameters");if(d){var c=0,f=d.timeoutValue;document.onmousemove=e;document.onkeypress=e;document.ontouchstart=e;document.ontouchmove=e;document.ontouchend=e;e()}});h.when("A","auth-captcha-cf").register("auth-image-captcha",function(b){function a(a){a&&a.captchaImageUrl&&c.test(a.captchaImageUrl)?(d("#auth-captcha-image").attr("src",
a.captchaImageUrl),d("input[type='hidden'][name='ces']").val(a.cesString)):(h.log("Failed to load new CAPTCHA due to invalid response from server","FATAL","auth-captcha"),l.location.reload(!0))}function e(){d("#auth-captcha-refresh-link").hide();d("#auth-captcha-noop-link").show();d("#auth-captcha-image").hide();d("#auth-captcha-image-container").addClass("a-lazy-loaded");var a=d("#auth-captcha-image").attr("data-refresh-url");a||h.log("Attempting to instantiate Captcha without a valid refresh url.",
"FATAL","auth-captcha");b.ajax(a,f)}var d=b.$,c=/^(http|https):\/\//,f={cache:!1,timeout:1E3,error:function(){h.log("Failed to refresh CAPTCHA due to error response from server","FATAL","auth-captcha");l.location.reload(!0)},success:a};d("#auth-captcha-image").load(function(){d("#auth-captcha-noop-link").hide();d("#auth-captcha-refresh-link").show();d("#auth-captcha-image-container").removeClass("a-lazy-loaded");d("#auth-captcha-image").fadeIn()});d(document).delegate("#auth-captcha-refresh-link",
"click",function(a){a.preventDefault();e();d("#auth-captcha-guess").focus()});return{handleSuccess:a,refresh:e}});h.when("A","auth-image-captcha","ready").register("auth-audio-captcha-handler",function(b,a){function e(a){a&&a.captchaImageUrl&&w.test(a.captchaImageUrl)?(k.val(a.cesString),C.attr("src",a.captchaImageUrl),f.load()):(h.log("Failed to load new CAPTCHA due to invalid response from server","FATAL","auth-audio-captcha-handler"),l.location.reload(!0))}function d(){b.ajax(C.attr("data-refresh-url"),
A);x.focus()}var c=b.$,f=c("#audio-captcha")[0],k=c("input[type='hidden'][name='ces']"),m=c("#audio-captcha-section"),g=c("#auth-captcha-guess"),r=c("#image-captcha-section"),C=c("#mp3-file"),D=c("#auth-switch-captcha-to-audio-container"),q=c("#use_audio_captcha"),u=c("#use_image_captcha");c("#auth-error-message-box");var w=/^(http|https):\/\//,p=c(".a-mobile").length,x=c("#audio-captcha-play-pause-button"),y=c("#audio-captcha-options"),t=c("#image-captcha-options"),B=c("#image-captcha-placeholder"),
v=c("#audio-captcha-placeholder"),A={cache:!1,timeout:1E3,error:function(){h.log("Failed to refresh CAPTCHA due to error response from server","FATAL","auth-audio-captcha-handler");l.location.reload(!0)},success:e};b.capabilities.audio&&D.show();return{switchCaptchaToAudio:function(){r.hide();u.val("false");m.show();q.val("true");g.val("");d();p&&(t.hide(),y.show(),g.attr("placeholder",v.val()))},switchCaptchaToImage:function(){m.hide();q.val("false");r.show();u.val("true");g.val("");f.pause();a.refresh();
g.focus();p&&(t.show(),y.hide(),g.attr("placeholder",B.val()))},audioRefresh:d,audioPlayButton:function(){f.paused?(g.focus(),f.play()):f.pause()},handleSuccess:e}});h.when("A","auth-audio-captcha-handler","ready").register("auth-audio-captcha",function(b,a){var e=b.$;e("#auth-switch-captcha-to-audio").click(function(d){d.preventDefault();a.switchCaptchaToAudio()});e("#auth-switch-captcha-to-image").click(function(d){d.preventDefault();a.switchCaptchaToImage()});e("#auth-refresh-audio").click(function(d){d.preventDefault();
a.audioRefresh()});e("#audio-captcha-play-pause-button").click(function(d){d.preventDefault();a.audioPlayButton()});return{handleSuccess:a.handleSuccess}});h.when("A").register("auth-cookie",function(b){function a(a,d,e){if(a){var m="";b.isFiniteNumber(e)&&(0>e?m="; expires=Thu, 01 Jan 1970 00:00:00 GMT":(m=new Date,m.setDate(m.getDate()+e),m="; expires="+m.toGMTString()));document.cookie=a+"="+l.encodeURIComponent(d)+m;return!0}return!1}function e(a){if(0<document.cookie.length&&a){var d=
document.cookie.indexOf(a+"=");if(-1<d)return d=d+a.length+1,a=document.cookie.indexOf(";",d),-1===a&&(a=document.cookie.length),l.decodeURIComponent(document.cookie.substring(d,a))}return""}function d(c){a(c,"",-1)}return{setCookie:a,getCookieValue:e,deleteCookie:d,checkCookieEnabled:function(c){a("amznTest","1");var b=e("amznTest");b?d("amznTest"):c&&(c=document.getElementById(c))&&(c.style.display="block");return!!b}}});h.when("A","ready").register("auth-pv-resend-utility",function(b){return{successHandler:function(a,
b){a.show();b.show()},errorHandler:function(a,b,d,c,f){403===a.http.status?l.location=b.sessionTimeoutUrl:(0<=(a.http.response||"").search("Throttled")?d.show():c.show(),f.show())},hideMessageBox:function(a,b,d,c,f){a.hide();b.hide();d.hide();c.hide();f.hide()}}});h.when("A","auth-pv-resend-utility","ready").register("auth-pv-resend",function(b,a){var e=b.state("auth-pv-page-state");if(e){var d=b.$,c=d("#auth-pv-client-side-success-box"),f=d(".auth-pv-client-side-success-messages li"),k=d("#auth-pv-client-side-error-box"),
m=d(".auth-pv-client-side-error-messages li"),g=d(".auth-server-side-message-box"),r=d("#auth-resend-code-succeeded"),h=d("#auth-there-was-an-error-throttled"),l=d("#auth-there-was-an-error"),q=function(){a.successHandler(r,c)},u=function(c){a.errorHandler(c,e,h,l,k)};d("#auth-resend-code-link").click(function(d){a.hideMessageBox(c,f,k,m,g);b.ajax(e.resendUrl,{method:"post",success:q,error:u})});return{successHandler:q,errorHandler:u}}});h.when("A").register("auto-verification-timeout",function(b){var a=
b.$,e=a("#auth-auto-verification-failed");e.length&&b.delay(function(){e[0].click()},3E4)});h.when("A","AmazonHelpPopup","ready").execute(function(b,a){b.$("#auth-amazon-help-link").click(function(){return a(this.href,"AmazonHelp","width=700,height=800,resizable=1,scrollbars=1,toolbar=1,status=1")})});h.when("A").execute(function(b){b.declarative("auth-popup","click",function(a){var b=a.data;a=a.$target.closest("a")[0];(b=l.open(a.href,a.target,b.windowOptions))&&b.focus()})});h.when("auth-cookie",
"ready").execute(function(b){b.checkCookieEnabled("auth-cookie-warning-message")});h.when("A","ready").register("AuthToolkit",function(b){function a(a){"undefined"!==typeof c(a)&&c(a).hasClass("a-button-disabled")&&(c(a).removeClass("a-button-disabled"),d(a).attr("disabled",!1))}function e(f,k){var m=d(f),g=m.data("remaining"),r=m.data("unit");0===g?(a(f),c(f).find(".a-button-text").text(k),b.trigger("AuthToolkit.countDownEnd",f)):0<g&&(m.data("remaining",g-1),c(f).find(".a-button-text").text(r.replace(/%d/,
g)),b.delay(function(){e(f,k)},1E3))}function d(a){var d=c(a).find("button");return 0<d.length?d:c(a).find("input")}var c=b.$;return{disableButton:function(a){"undefined"===typeof c(a)||c(a).hasClass("a-button-disabled")||(c(a).addClass("a-button-disabled"),d(a).attr("disabled","disabled"))},enableButton:a,countingDown:function(a){if("undefined"!==typeof c(a)){var b=c(a).find(".a-button-text").text();0<=d(a).data("remaining")&&e(a,b)}}}});h.when("A","ready").execute(function(b){var a=
b.$("#auth-external-javascript").data("external-javascripts");a&&a.length&&b.each(a,function(a){h.load.js(a,function(a){a.target.setAttribute("crossorigin","anonymous")})})});h.when("A","a-modal","auth-validate-form-handler","ready").register("auth-phone-verification-modal",function(b,a,e){function d(){var a=m.val();l.text(a);var c=k.find("option:selected"),a=c.data("calling-code"),c=c.data("country-code");r.text(a);h.text(c)}var c=b.$,f=b.state("auth-phone-verification-modal");if(f){var k=
c("#auth-country-picker"),m=c("#ap_phone_number"),g=c("#"+f.formIdToBindTo),r=c("#auth-verify-mobile-calling-code"),h=c("#auth-verify-mobile-country-code"),l=c("#auth-verify-mobile-national-number");b.on("a:popover:beforeShow:verifyContinueModal",d);c(".auth-requires-verify-modal").click(function(d){d.preventDefault();e.validate(g)&&(d=c("#auth-verify-modal-action"),(d=a.get(d))&&m.is(":enabled")?d.show():g.submit())});b.declarative("auth-verify-modal-complete","click",function(){g.submit()});return{updateVerificationModalContents:d}}});
h.when("A").register("auth-phone-verification-spinner",function(b){b=b.$;var a=b("#auth-contact-verification-spinner-hidden-code-form-wrapper #auth-pv-form");0<a.length&&(l.submitVerificationCode=function(b){a.find("#auth-pv-enter-code").val(b);a.find("#auth-verify-button").click()})});h.when("A","auth-validate-form-common","a-form-controls-api","client-side-counters-util","page-util","ready").register("auth-moa",function(b,a,e,d,c){var f=b.$,k=f("#ap_phone_number"),m=f("#ap_email");
f("#ap_use_mobile, #ap_use_email").click(function(a){f(".ap_email_fields,.ap_mobile_number_fields").toggle();f("#auth-country-picker, #ap_email, #ap_phone_number").prop("disabled",function(a,c){return!c});f("#auth-country-picker-container").toggleClass("a-button-disabled");c.isMobile()?f("#ap_email, #ap_phone_number").parent(".a-input-text-wrapper").toggleClass("a-form-disabled"):f("#ap_email, #ap_phone_number").toggleClass("a-form-disabled");return!1});f("#ap_use_email").click(function(){a.isNonBlankField(k)&&
a.isValidEmailField(k)&&(m.val(k.val()).keyup(),d.incrementCounter("PersistEmailFromPhoneToEmail"+c.determineDeviceType()))});f("#ap_use_mobile").click(function(){a.isNonBlankField(m)&&a.isValidPhoneNumberField(m)&&(k.val(m.val()).keyup(),d.incrementCounter("PersistPhoneFromEmailToPhone"+c.determineDeviceType()))})});h.when("A","page-util","ready").register("auth-validate-form-common",function(b,a){function e(a){return g.test(a.trim())}function d(a){return!r.test(a.trim())}function c(a){return a.data("validation-id")||
a.parent().data("validation-id")||a[0].name}function f(a){var c=a.closest(".a-input-text-wrapper");0<c.length?c.addClass("a-form-error"):a.addClass("a-form-error")}function k(a){var c=a.closest(".a-input-text-wrapper");0<c.length?c.removeClass("a-form-error"):a.removeClass("a-form-error")}var m=b.$,g=/^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,r=/^ *\+|^ *＋|[a-zA-ZＡ-Ｚａ-ｚ]|@/,h=/[a-zA-Z]/,l={"auth-required-field":"-missing-alert","auth-require-email-validaton":"-invalid-email-alert",
"auth-require-phone-validation":"-invalid-phone-alert","auth-require-claim-validation":"-invalid-claim-alert","auth-require-password-validation":"-invalid-password-alert","auth-require-fields-match":"-mismatch-alert"};return{isMatchingFields:function(a){var c=a.eq(0);a=a.eq(1);c=c.val().trim();a=a.val().trim();return c===a},isValidEmailField:function(a){a=a.val();return e(a)},isValidPhoneNumberField:function(a){a=a.val();return d(a)},isValidClaimField:function(a){a=a.val();return e(a)||!h.test(a.trim())},
isValidEmail:e,isValidPhoneWithCountryCodeSelector:d,isValidPasswordField:function(a){return 6<=a.val().length},isNonEmptyField:function(a){return!!a.val()},isNonBlankField:function(a){return!!a.val().trim()},displayErrorMessage:function(a,d){var b=c(a),b=m("#auth-"+b+d);f(a);b.show()},hideErrorMessage:function(a,d){var b=c(a),b=m("#auth-"+b+d);k(a);b.hide()},isErrorVisible:function(a,d){var b=c(a);return m("#auth-"+b+l[d]).is(":visible")},getValidationId:c,addErrorClass:f,removeErrorClass:k,determineDeviceType:function(){return a.isMobile()?
"OnMobile":"OnDesktop"},getErrorAlertExtension:function(a){return l[a]},getSelectorForInputsOfErrorTypeClass:function(a){if(a)return a+=":visible","input:enabled."+a+", ."+a+" input:enabled"}}});h.when("A","auth-validate-form-common","client-side-counters-util","page-util","ready").register("auth-validate-form-handler",function(b,a,e,d){function c(c,b,g,k){var f=a.getValidationId(b);f&&(t||(t={}),t[f]||(t[f]=[]),t[f].push({$field:b,type:g,extension:k}),k&&e.incrementCounter(d.getFormName(c)+
d.toCamelCase(f+k)+a.determineDeviceType()))}function f(d){d.find(".auth-require-fields-match-group").each(function(){var b=p(this).find(a.getSelectorForInputsOfErrorTypeClass("auth-require-fields-match"));1<b.length&&l(b.eq(0))&&l(b.eq(1))&&!a.isMatchingFields(b)&&(c(d,b.eq(0),"Check Mismatch","-mismatch-alert"),c(d,b.eq(1),"Check Mismatch"))})}function k(d){d.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-email-validaton")).each(function(){var b=p(this);a.isNonBlankField(b)&&!a.isValidEmailField(b)&&
c(d,b,"Invalid Email","-invalid-email-alert")})}function m(d){d.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-claim-validation")).each(function(){var b=p(this);a.isNonBlankField(b)&&!a.isValidClaimField(b)&&c(d,b,"Invalid Claim","-invalid-claim-alert")})}function g(d){d.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-phone-validation")).each(function(){var b=p(this);a.isNonBlankField(b)&&!a.isValidPhoneNumberField(b)&&c(d,b,"Invalid Phone","-invalid-phone-alert")})}function r(d){d.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-password-validation")).each(function(){var b=
p(this);a.isNonEmptyField(b)&&!a.isValidPasswordField(b)&&c(d,b,"Invalid Password","-invalid-password-alert")})}function h(d){d.find(a.getSelectorForInputsOfErrorTypeClass("auth-required-field")).each(function(){var a=p(this),b=this.name;l(a)||x.test(b)&&t&&t[b.split("Check")[0]]||c(d,a,"Missing Required","-missing-alert")})}function l(c){return"password"===c.attr("type")?a.isNonEmptyField(c):a.isNonBlankField(c)}function q(c){var d=p("#auth-alert-window");c.find(".a-form-error").removeClass("a-form-error");
p(".auth-error-messages li, .auth-inlined-error-message, .auth-inlined-information-message, .auth-server-side-message-box").hide();t?(b.each(t,function(c,d){b.each(c,function(c){var b=c.extension;a.addErrorClass(c.$field);b&&(c="#auth-"+d+b,b=p(c+y),b.length?b.show():p(c).show())})}),p("#message-box-slot").hide(),d.show(),c.find(".a-form-error").first().focus()):d.hide()}function u(a){return"string"!==typeof a||0===a.length?"":Array.prototype.map.call(a,function(a){var c=a.charCodeAt(0);return 65280<=
c&&65519>=c?String.fromCharCode(c-65248):12288===c?String.fromCharCode(32):a}).join("")}function w(a){a.find("input[name=email], input[name=customerName], input[name=customerNamePronunciation], input[name=emailLogin], input[name=guess]").each(function(){if(""!==p(this).val()){var a=u(p(this).val());p(this).val()!==a&&(p(this).val(a),e.incrementCounter(e.getCounterNameWithDeviceAndPageType("SingleClaimFieldFullWidthRemoval")))}})}var p=b.$,x=/Check$/g,y="",t;return{validate:function(c){c=c&&c.jquery?
c:p(c);if(c.length&&c.is("form")){y=c.hasClass("ap_ango_phone")?"-ango-phone":c.hasClass("ap_ango_email")?"-ango-email":"";w(c);h(c);m(c);k(c);g(c);r(c);f(c);t&&e.incrementCounter(d.getFormName(c)+"PreventedServerRoundTrips"+a.determineDeviceType());q(c);var b=!t;c.data("auth-validation-errors",t);t=void 0;return b}},getErrors:function(a){return(a.jquery?a:p(a)).data("auth-validation-errors")}}});h.when("A","auth-validate-form-handler","ready").register("auth-validate-form-moa",function(b,
a){var e=b.$;e(document.body).delegate(".auth-validate-form-moa","submit",function(d){a.validate(this)||d.preventDefault()})});h.when("A","auth-validate-form-handler","auth-validate-form-common","client-side-counters-util","page-util","ready").register("auth-validate-form",function(b,a,e,d,c){b=b.$;b(document.body).delegate(".auth-validate-form","submit",function(b){d.incrementCounter(c.getFormName(this)+"Submit"+e.determineDeviceType());a.validate(this)||b.preventDefault()})});h.when("A",
"auth-validate-form-common","ready").register("auth-validate-form-real-time",function(b,a){function e(c,d,b){a.isErrorVisible(c,d)&&b(c)&&a.hideErrorMessage(c,a.getErrorAlertExtension(d))}function d(c,d){if(c.hasClass("auth-require-fields-match")){var b=c.closest(".auth-require-fields-match-group");if(b!==f&&(b=b.find(a.getSelectorForInputsOfErrorTypeClass("auth-require-fields-match")),2===b.length)){var e=b.eq(0),h=b.eq(1);a.isErrorVisible(e,"auth-require-fields-match")&&d(b)&&(a.hideErrorMessage(e,
a.getErrorAlertExtension("auth-require-fields-match")),a.removeErrorClass(h))}}}var c=b.$,f;c(".auth-real-time-validation input").bind("keyup.clearValidationErrors",function(){var b=c(this);e(b,"auth-required-field",a.isNonEmptyField);e(b,"auth-require-email-validaton",a.isValidEmailField);e(b,"auth-require-phone-validation",a.isValidPhoneNumberField);e(b,"auth-require-claim-validation",a.isValidClaimField);e(b,"auth-require-password-validation",a.isValidPasswordField);d(b,a.isMatchingFields)});return{clearErrorMessageOnMatchingInputs:d}});
h.when("A","AuthToolkit","ready").register("auth-3p-phone-verification",function(b,a){function e(){l.NativeUI&&"function"===typeof l.NativeUI.applyFullFlash&&l.setTimeout(function(){l.NativeUI.applyFullFlash()},900)}var d=b.$,c=d("#auth-pv-enter-code");a.countingDown("#ap-3p-get-pin-code-button");b.on("AuthToolkit.countDownEnd",function(a){"#ap-3p-get-pin-code-button"===a&&(d("#auth-phone-number").removeClass("a-form-disabled"),d("#auth-phone-number-wrapper").removeClass("a-form-disabled"),
d("#auth-phone-number").attr("disabled",!1))});b.on("a:dropdown:auth-country-picker:select",e);c.bind("change paste keyup",function(){0<d(this).val().length?a.enableButton("#ap-3p-pv-create-account"):a.disableButton("#ap-3p-pv-create-account")});d("#auth-verify-button").click(function(){var a=d("#auth-3p-pv-form");a.find("#insisted").val("false");a.find("#getPinCodeAction").val("true");a.submit()});d("#ap-3p-insist-verify-link").click(function(){var a=d("#auth-3p-pv-form");a.find("#auth-country-picker").val(d("#ap-3p-insist-verify-link").attr("countrycode"));
a.find("#auth-phone-number").val(d("#ap-3p-insist-verify-link").attr("phonenumber"));a.find("#insisted").val("true");a.submit()});return{callApplyFullFlash:e}});h.when("A","a-modal","ready").register("ap-3p-pv-modal",function(b,a){var e=b.$,d=b.state("ap-3p-pv-modal");if(d){var c=d.thirdPartyPhoneConflict;if(c&&"None"!==c.toString()){var f=e("#"+d.formIdToBindTo),e=e("#ap-3p-pv-modal-action");(e=a.get(e))&&c&&"None"!==c.toString()&&e.show();b.declarative("ap-3p-pv-modal-complete","click",function(){c&&
"WeChat"===c.toString()&&(f.find("#insisted").val("true"),f.submit())})}}});h.when("A","a-modal","ready").register("ap-3p-account-connected-modal",function(b,a){var e=b.$,d=b.state("ap-3p-account-connected-modal");d&&d.thirdPartyAccountStatus&&"rejectWithLoginIdIfConnected"===d.thirdPartyAccountStatus&&(e=e("#ap-3p-account-connected-modal-action"),(e=a.get(e))&&e.show())});h.when("A").execute(function(b){function a(a){var c=b.state("moa_registration_v2_info");c&&c.enabled&&
b.get("/ap/nocontent/ref="+a+"_"+c.device,{})}var e=b.$;e("#ap_use_email").click(function(){a("ap_mmoar_usee")});e("#ap_use_mobile").click(function(){a("ap_mmoar_usem")});e("#auth-country-picker-container").click(function(){a("ap_mmoar_ccp")});e("#continue").click(function(){a("ap_mmoar_cont")});b.on("a:popover:show:verifyContinueModal",function(){a("ap_mmoar_vm_o")});b.on("a:popover:hide:verifyContinueModal",function(){a("ap_mmoar_vm_c")});e("#auth-verification-ok-announce").click(function(){a("ap_mmoar_vm_ok")});
e("#auth-already-have-account").click(function(){a("ap_mmoar_signin")});e("#auth-verify-button").click(function(){a("ap_mmoar_pv_verify")});e("#auth-resend-code-link").click(function(){a("ap_mmoar_pv_resend")})});h.when("A","jQuery","ready").register("wechat-wxlogin-js",function(b,a){if(0<a("#auth-wechat-login-container").length){var e=a("#auth-wechat-login-container").data("wechatUrl");h.load.js(e)}});h.when("A","jQuery","client-side-counters-util","wechat-login-button-counter","wechat-wxlogin-js",
"ready").register("wechat-qrcode-module",function(b,a,e,d){if(0<a("#auth-wechat-login-container").length){var c=function(){var c=a("div#auth-interactive-dialog-content"),d=a("div#auth-wechat-qrcode-loading-container").clone();d.removeClass("hidden");d.appendTo(c);a("div#auth-interactive-dialog").css("display","table");var b=a("#auth-wechat-login-container"),c=b.data("appid"),d=b.data("scope"),e=b.data("redirectUrl"),f=b.data("state"),b=b.data("style");new l.WxLogin({id:"auth-wechat-qrcode-container",
appid:c,scope:d,redirect_uri:e,state:f,style:b})},f=function(){var c=a("div#auth-interactive-dialog-content");a("div#auth-interactive-dialog").css("display","none");c.empty()};a("div#auth-interactive-dialog-content").click(function(a){a.stopImmediatePropagation()});a("#auth-wechat-login-container").click(function(){e.incrementCounter(d.weChatButtonClickEventCounterName);c()});a("div#auth-interactive-dialog-container").click(function(){f()});return{showWeChatQRCode:c,hideWeChatQRCode:f}}});h.when("A",
"client-side-counters-util","counters-name","ready").register("wechat-login-button-counter",function(b,a,e){var d=e.getCommonCounterNamePrefix()+":WeChat";e=b.$("#auth-wechat-login-container-noninteractive");0<e.length&&e.click(function(){a.incrementCounter(d)});b=b.$("a#signInSubmit.wechat_button");0<b.length&&b.click(function(){a.incrementCounter(d)});return{weChatButtonClickEventCounterName:d}});h.when("A").register("wechat",function(b){function a(a,c){return e.ajax({url:"https://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js",
dataType:"script",success:a,error:c,cache:!0})}var e=b.$,d=!1,c=null;return{WxLogin:function(b,k){k&&e.isFunction(k)||(k=function(){});d?k(new c(b)):a(function(){d=!0;c=l.WxLogin;k(new c(b));e("#identity-provider-pagelet-wechat-gray-block").fadeOut()},function(){k()})}}});h.when("A","wechat","ready").execute(function(b,a){var e=b.$,e=e("#auth-identity-provider-wechat-qrcode-container");0!==e.length&&(a.WxLogin({id:"auth-identity-provider-wechat-qrcode-container",appid:e.data("appid"),scope:e.data("scope"),
redirect_uri:e.data("redirect-uri"),state:e.data("state"),style:e.data("style")}),setTimeout(function(){l.location.reload()},9E5))});h.when("A","auth-form-field-utils","cvf","client-side-counters-util","ready").register("auth-contact-verification-handler",function(b,a,e,d){function c(c){var g=this;c=c||{};this.postVerificationSuccessCallback=c.postVerificationSuccessCallback||k.noop;this.$verificationForm=k("form.auth-contact-verification-form");this.$contactVerificationWidgetTarget=
k(".auth-contact-verification-widget-target").first();this.$claimToken=this.$verificationForm.find('input[type="hidden"].auth-contact-verification-claim-token');this.$verifyContactButton=this.$verificationForm.find(".auth-contact-verification-button");this.contactVerificationEndpoint=this.$verificationForm.attr("action");this.postVerificationFormAction=this.$verificationForm.data("post-verification-action");this.$verificationTarget=this.$verificationForm.find(".auth-contact-verification-target");
this.$spinnerTarget=this.$verificationForm.find(".auth-contact-verification-spinner");this.$successMessage=this.$verificationForm.find(".auth-contact-verification-success-message");this.preVerify="preVerify";this.pendingVerify="pendingVerify";this.verifyState=g.preVerify;this.formSubmitEvent="submit.contactVerification";this.$reverifyOnChangeTarget=k(".auth-require-reverify-on-change, .auth-require-reverify-on-change :input");this.verificationFlowCompleteTime=this.verifyRequestCompleteTime=this.verificationFlowStartTime=
0;this.disableTargetLabelCssClass="a-color-tertiary";this.errorCodes="&errorCodes=";this.internalError="INTERNAL_ERROR";this.ajax=function(a,c){b.ajax(a,c)};this.startContactVerification=function(){g.verificationFlowStartTime=(new Date).getTime();g.ajax(g.contactVerificationEndpoint,{method:"post",cache:!1,params:f(g.$verificationForm),error:g.startContactVerificationError,success:g.initializeComposableVerificationWidget})};this.startContactVerificationError=function(a,c,b){h.log("Error contacting contact verification endpoint: "+
b+". Customers will not be able to verify their contact information.","INFO");d.incrementCounter("contactVerificationAjaxFailureContactVerificationInit");l.location.href=l.location.href+g.errorCodes+g.internalError};this.cvfWidgetFactory=e;this.initializeComposableVerificationWidget=function(a){a=a||{};a.location?l.location.href=a.location:(a=a.requestToken||"",g.verifyRequestCompleteTime=(new Date).getTime(),a={target:g.$contactVerificationWidgetTarget,requestToken:a,onSuccess:g.completeContactVerification,
onError:g.widgetInitializationError,autoStart:!1},g.$spinnerTarget&&(a.spinnerTarget=g.$spinnerTarget),g.cvfWidgetFactory.create(a).start())};this.widgetInitializationError=function(a,c,b){h.log("Error initializing verification widget: "+b+". Customers will not be able to verify their contact information.","INFO");d.incrementCounter("contactVerificationAjaxFailureWidgetInit");l.location.href=l.location.href+g.errorCodes+g.internalError};this.setClaimToken=function(a){g.$claimToken.val(a)};this.completeContactVerification=
function(c,b){g.verificationFlowCompleteTime=(new Date).getTime();b?(g.setClaimToken(c),g.setPostVerificationAction(),g.$successMessage.show(),g.$verificationForm.unbind(g.formSubmitEvent),g.$verificationTarget.each(function(){a.enableInput(k(this));var c=k("label[for='"+k(this).attr("id")+"']");c.length&&c.removeClass(g.disableTargetLabelCssClass)}),d.insertCounter("contactVerificationCompleteVerificationFlowCompleteTime",g.verificationFlowCompleteTime-g.verificationFlowStartTime),d.insertCounter("contactVerificationVerifyRequestCompleteTime",
g.verifyRequestCompleteTime-g.verificationFlowStartTime),k.isFunction(g.postVerificationSuccessCallback)&&g.postVerificationSuccessCallback()):l.location.href=l.location.href+g.errorCodes+g.internalError};this.setPostVerificationAction=function(){g.$verificationForm.prop("action",g.postVerificationFormAction)};this.verificationRequestHandler=function(a){a.preventDefault();g.$spinnerTarget&&g.$spinnerTarget.show();g.verifyState=g.pendingVerify;g.$verifyContactButton.hide();g.startContactVerification()};
this.bindVerificationFormEvent=function(){g.$verificationForm.bind(g.formSubmitEvent,g.verificationRequestHandler)};g.bindVerificationFormEvent();this.unbindVerificationFormEvent=function(){g.$verificationForm.unbind(g.formSubmitEvent)};this.safeBind=function(){g.unbindVerificationFormEvent();g.bindVerificationFormEvent()};this.resetContactVerificationOnRequestInfoChange=function(){g.$reverifyOnChangeTarget.bind("keyup",function(a){a.preventDefault();a=13===a.keyCode;g.verifyState===g.preVerify||
a||(b.trigger("cvf:claim:changed"),g.verifyState=g.preVerify,g.reVerifyEmail());g.$claimToken.val()&&g.safeBind()})};g.resetContactVerificationOnRequestInfoChange();this.reVerifyEmail=function(){g.$contactVerificationWidgetTarget.empty();g.$verifyContactButton.show();g.$successMessage.hide();g.disableVerificationTarget();g.$verificationForm.prop("action",g.contactVerificationEndpoint)};this.disableVerificationTarget=function(){g.$verificationTarget.each(function(){a.disableInput(k(this));var c=k("label[for='"+
k(this).attr("id")+"']");c.length&&c.addClass(g.disableTargetLabelCssClass)})}}function f(c){c=c.find("input.auth-contact-verification-request-info, input[type=hidden]");return a.inputsToJson(c)}var k=b.$;return{create:function(a){d.incrementCounter("contactVerificationCVFCreate");return new c(a)},ContactVerificationHandler:c}});h.when("auth-contact-verification-handler","ready").register("auth-contact-verification-autostart",function(b){return b.create()});h.when("A").register("auth-form-field-utils",
function(b){function a(a){a.prop("disabled",!1);a.removeClass("a-form-disabled");a.find("input").prop("disabled",!1)}function e(a){a.removeClass("a-button-disabled");a.find("input").prop("disabled",!1)}function d(a){a.prop("disabled",!0);a.addClass("a-form-disabled");a.find("input").prop("disabled",!0)}function c(a){a.addClass("a-button-disabled");a.find("input").prop("disabled",!0)}var f=b.$;return{enableTextInput:a,enableButton:e,enableInput:function(c){0<c.closest(".a-button").length?e(c):(c.hasClass("a-input-text")||
c.hasClass("a-input-text-wrapper"))&&a(c)},disableTextInput:d,disableButton:c,disableInput:function(a){0<a.closest(".a-button").length?c(a):(a.hasClass("a-input-text")||a.hasClass("a-input-text-wrapper"))&&d(a)},inputsToJson:function(a){return a.map(function(){var a=f(this);if(a.is("input")){var c={};c[a.attr("name")]=a.val();return c}}).toArray().reduce(function(a,c){return f.extend(a,c)})}}});h.when("page-util").register("client-side-counters-util",function(b){function a(a,d){var c=
l.ue;c&&"function"===typeof c.count&&(d||(d=(c.count(a)||0)+1),c.count(a,d))}return{incrementCounter:function(b){a(b)},insertCounter:a,getCounterNameWithDeviceAndPageType:function(a){return a+b.determineDeviceType()+b.determinePageType()}}});h.when("A","AuthToolkit","auth-pv-resend-utility","ready").register("auth-cnep-add-password",function(b,a,e){var d=b.$;if(!(1>d("#ap-cnep-add-password-resend-code-button").length)){a.countingDown("#ap-cnep-add-password-resend-code-button");var c=
b.state("auth-cnep-add-password-resend-state");if(c){var f=d("#auth-cnep-add-password-client-side-success-box"),k=d(".auth-pv-client-side-success-messages li"),m=d("#auth-cnep-add-password-client-side-error-box"),g=d(".auth-pv-client-side-error-messages li"),r=d(".auth-server-side-message-box"),h=d("#auth-resend-code-succeeded"),l=d("#auth-there-was-an-error-throttled"),q=d("#auth-there-was-an-error");c.sessionTimeoutUrl=c.cnepUrl;var u=function(){e.successHandler(h,f)},w=function(a){e.errorHandler(a,
c,l,q,m)};d("#ap-cnep-add-password-resend-code-button").click(function(){"#ap-cnep-add-password-resend-code-button".isDisabled||(e.hideMessageBox(f,k,m,g,r),b.ajax(c.resendPinCodeUrl,{method:"post",success:u,error:w}),"undefined"===typeof d("#ap-cnep-add-password-resend-code-button")||d("#ap-cnep-add-password-resend-code-button").hasClass("a-button-disabled")||(d("#ap-cnep-add-password-resend-code-button").addClass("a-button-disabled"),d("#ap-cnep-add-password-resend-code-button").find(".a-button-text").attr("disabled",
"disabled")),d("#ap-cnep-add-password-resend-code-button").find(".a-button-text").data("remaining",c.originalRemaining),a.countingDown("#ap-cnep-add-password-resend-code-button"))})}}});h.when("A","ready").register("counters-name",function(b){return{getCommonCounterNamePrefix:function(){var a="unknown",e=l.location.pathname.split("/");0<e.length&&(a=e[e.length-1]);var e="",d=b.state("auth-csm-page-state");d&&(e=d.assocHandle);return["AuthenticationPortal",a,e].join(":")}}});
h.when("A").register("page-util",function(b){function a(a){a.jquery||c(a);return e(c("form:visible").attr("name"))}function e(a){if(a)return a.replace(/(?:-| |\b)(\w)/g,function(a,c){return c.toUpperCase()})}function d(){return c("html").hasClass("a-mobile")}var c=b.$;return{getFormName:a,toCamelCase:e,determinePageType:function(){for(var c={SignIn:"SignInPage",Register:"RegistrationPage",ForgotPassword:"Fpp"},d=document.getElementsByTagName("form"),b=0;b<d.length;b++){var e=a(d[b]);if(e in c)return c[e]}},
determineDeviceType:function(){return d()?"OnMobile":"OnDesktop"},isMobile:d}});h.when("A","client-side-counters-util","page-util").register("passwordless-auth",function(b,a,e){var d=b.$,c=b.state("login-with-otp-state"),f=d("#ap_login_form #continue");l.loginWithOTPState=c!==n?c.isLoginWithOTPEnabled:!1;d("#auth-skip-reset-password-link").click(function(){b.get("/ap/nocontent/ref=ap_fpp_skip_on_reset_pwd",{});a.incrementCounter("SkipResetPasswordOnResetPage"+e.determineDeviceType())});
b.on("credentialsEntered",function(){!0===l.loginWithOTPState&&(a.incrementCounter("SharedWebCredentialsSubmitted"),f.click())})});h.when("A","client-side-counters-util","a-checkbox","ready").register("auth-remember-me",function(b,a,e){function d(c){c.val()!==k?(e(m).isChecked()&&a.incrementCounter(a.getCounterNameWithDeviceAndPageType("UncheckRMCheckboxForUnrecognizedEmail")),e(m).uncheck()):""!==c.val()&&(e(m).check(),a.incrementCounter(a.getCounterNameWithDeviceAndPageType("BackToCheckedRMCheckboxForRecognizedEmail")))}
b=b.$;var c=b("#ap_email, #ap-credential-autofill-hint"),f=b("#ap_email_icon"),k=c.val(),m=b("input[name=rememberMe]");c.bind("keyup.uncheckRememberMe",function(){""!==k&&d(c)});f.click(function(){d(c)})});h.when("A","client-side-counters-util","page-util","ready").register("auth-remove-mobile-claim",function(b,a,e){b=b.$;var d=b("#auth-remove-phone-claim");b("#ap-remove-mobile-claim-submit-button").click(function(){d.submit();a.incrementCounter("RemoveMobileClaimSubmitAttempt"+e.determineDeviceType())})});
h.when("A","client-side-counters-util","ready").execute(function(b,a){b.on("a:expander:blacklist_password_learn_more:toggle:expand",function(b){a.incrementCounter("BlacklistPasswordInstructionLearnMoreExpand")});b.on("a:expander:blacklist_password_learn_more:toggle:collapse",function(b){a.incrementCounter("BlacklistPasswordInstructionLearnMoreCollapse")})});h.when("A","ready").register("auth-footer-language-picker",function(b){b.on("a:dropdown:selected:languagePicker",function(a){l.location.href=
a.value})});h.when("A").execute(function(b){b.declarative("other-languge-option-click","click",function(a){"input"===a.targetTag&&(l.location.href=a.$target[0].value)})});h.when("A","ready").register("account_conflict_continue_verify",function(b){var a=b.$;a("#auth-account-conflict-continue-verify-url").click(function(b){b.preventDefault();b=a("#ap_account_conflict_warning_customer_actions");b.exists()&&b.submit()});a.fn.exists=function(){return 0!==this.length}});h.when("A").register("handle-ios-redirect",
function(b){document.getElementById("returnToUrl")&&0!==document.getElementById("returnToUrl").getElementsByTagName("a").length&&(l.location.href=document.getElementById("returnToUrl").getElementsByTagName("a")[0].href)});h.when("A","auth-validate-form-common","client-side-counters-util").register("moa-single-claim-input-common",function(b,a,e){function d(c){return a.isNonBlankField(c)?a.isValidPhoneNumberField(c)?f.PHONE:f.EMAIL:f.UNKNOWN}var c=b.$,f={PHONE:"PHONE",EMAIL:"EMAIL",UNKNOWN:"UNKNOWN"};
Object.freeze(f);var k={};k[f.PHONE]="phone-text";k[f.EMAIL]="email-text";k[f.UNKNOWN]="default-text";Object.freeze(k);var m={};m[f.PHONE]="SingleClaimFieldPhone";m[f.EMAIL]="SingleClaimFieldEmail";Object.freeze(m);var g={REGISTER:"registerPage",SIGNIN:"signInPage"};Object.freeze(g);c.fn.auiShow=function(){c(this).removeClass("a-hidden aok-hidden").show();return this};c.fn.auiHide=function(){c(this).addClass("aok-hidden").hide();return this};return{showPasswordInformationMessage:function(a){a=a&&
a.$currentTarget||c(a.target);a.closest(".a-row").parent().find(".auth-inlined-error-message").is(":visible")||a.closest(".a-row").parent().find("#passwordInformationMessage").auiShow()},hidePasswordInformationMessage:function(a){var d=a&&a.$currentTarget||c(a.target);d.closest(".a-row").parent().find("#passwordInformationMessage").auiHide();a.$event&&a.$event.relatedTarget&&"submit"===a.$event.relatedTarget.type&&b.delay(function(){d.closest("form").submit()})},incrementCounterForSelectedClaim:function(a){a=
d(a);e.incrementCounter(e.getCounterNameWithDeviceAndPageType(m[a]))},incrementCounterForPlusSymbolAtStartOfClaim:function(){e.incrementCounter(e.getCounterNameWithDeviceAndPageType("PlusSymbolAtStartOfClaim"))},incrementCounterForToggleCountryPicker:function(a){e.incrementCounter(e.getCounterNameWithDeviceAndPageType(a?"CountryPickerEnabled":"CountryPickerDisabled"))},getClaimType:d,ClaimType:f,PageType:g,ButtonTextToClass:k,isValidEmail:/^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,
invalidPhoneRegex:/^ *\+|[a-zA-Z]|@/}});h.when("A","moa-single-claim-input-field_handler","ready").register("moa-single-claim-input-field",function(b,a){var e=b.$;e("#ap_email");b.declarative("single_claim_handler","focusout keyup",a.inputHandler);b.declarative("single_claim_password_handler","focusout focusin keyup",a.passwordHandler);b.declarative("show-countries","click",a.showCountries);b.on("a:dropdown:auth-country-picker:select",a.updateCountryDisplayText)});h.when("A",
"auth-validate-form-common","client-side-counters-util","moa-single-claim-input-common","a-dropdown").register("moa-single-claim-input-field_handler",function(b,a,e,d,c){function f(a){h("#auth-continue .a-button-text span").auiHide();h("#auth-continue ."+a).auiShow()}function k(a){var c=a.closest(".a-section").find(".country-picker");c&&r(a)?(c=c.outerWidth(),a.css({"padding-left":c+"px"})):a.css({"padding-left":""})}function m(a,b){var d=a.closest(".moa-single-claim-container").find("select").attr("id");
c.getSelect(d).update({status:b})}function g(a){r(a)||(m(a,"enabled"),a.closest(".a-section").find(".country-picker").auiShow(),k(a),d.incrementCounterForToggleCountryPicker(!0))}function r(a){return a.closest(".a-section").find(".country-picker").is(":visible")}var h=b.$;return{inputHandler:function(c){if("focusout"===c.type){var b=c.$currentTarget.find("input");if(!(0>=b.size()))switch(d.getClaimType(b)){case d.ClaimType.PHONE:f(d.ButtonTextToClass.PHONE);break;case d.ClaimType.EMAIL:f(d.ButtonTextToClass.EMAIL);
break;default:f(d.ButtonTextToClass.UNKNOWN)}}if("focusout"===c.type||"keyup"===c.type){var b=c.$target,e=b.val()&&b.val().trim()||"";c=c.$event.which;16<=c&&46>c||(1===e.length&&"+"===e.charAt(0)||"+"===e.charAt(0)&&a.isValidPhoneWithCountryCodeSelector(e.substr(1))?(b.val(b.val().substr(1)),g(b),d.incrementCounterForPlusSymbolAtStartOfClaim()):e&&a.isValidPhoneWithCountryCodeSelector(e)?g(b):r(b)&&(m(b,"disabled"),b.closest(".a-section").find(".country-picker").auiHide(),k(b),d.incrementCounterForToggleCountryPicker(!1)))}},
passwordHandler:function(a){"keyup"===a.type||"focusin"===a.type?d.showPasswordInformationMessage(a):"focusout"===a.type&&d.hidePasswordInformationMessage(a)},showCountries:function(a){a.$currentTarget.closest(".moa-single-claim-container").find(".moa-country-picker-select-container .a-declarative").click()},updateCountryDisplayText:function(a){var c=h(a.selectNode),b=c.closest(".moa-single-claim-container").find(".country-picker"),c=c.closest(".moa-single-claim-container").find("input[name=email]");
a=a.nativeItemNode.text;b.find(".a-declarative").text(a);k(c)}}})});
/* ******** */
